### ISSUE TITLE
X.P.Pass documentation typo

### ISSUE THREAD

**Issue by davama** [xmonad/xmonad-contrib#101]
Small minor typo in haskell doc for this module:

https://hackage.haskell.org/package/xmonad-contrib-0.12/docs/XMonad-Prompt-Pass.html

The `x` :

```
, ((modMask x , xK_p)                              , passPrompt xpconfig)
  , ((modMask x .|. controlMask, xK_p)               , passGeneratePrompt xpconfig)
  , ((modMask x .|. controlMask  .|. shiftMask, xK_p), passRemovePrompt 
```

Thanks

**Comment by pjones** [comment]
Would love to see a PR for this so I can just merge it.  Thanks.

**Comment by davama** [comment]
see: https://github.com/xmonad/xmonad-contrib/pull/165
