### ISSUE TITLE
Borders reappear after fullscreen float with noBorders 

### ISSUE THREAD

**Issue by IvanMalison** [xmonad/xmonad-contrib#107]

**Comment by pjones** [comment]
From what I understand, if a window is floating then it won't be affected by a layout.  That means the `NoBorders` layout won't get a chance to run and remove borders.

@IvanMalison Would you be willing to confirm my assumption and update the documentation?

**Comment by geekosaur** [comment]
"reappear" implies they were off initially? Nothing should be regenerating borders unless the program is using old-style fullscreen (withdrawing or covering the original window and mapping a new fullscreen window). So this could be either a non-EWMH program or one that is being pedantic about advertised EWMH fullscreen. (I'm starting to think `EwmhDesktops` should advertise fullscreen always, even if the user hasn't configured a fullscreen hook.)

**Comment by pjones** [comment]
@IvanMalison can you give more details here?  If not I'm going to close this issue as abandoned

**Comment by IvanMalison** [comment]
I can't reproduce this anymore.
