### ISSUE TITLE
Space in execScriptHook

### ISSUE THREAD

**Issue by louwers** [xmonad/xmonad-contrib#115]
It makes no sense that ``~/.xmonad/hooks startup`` (two files!) are executed if you have

```
   startupHook = execScriptHook "startup"
```
set.

What should happen instead is that ``~/.xmonad/hooks/startup`` gets executed. Right?

This was obviously the [intention](http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Hooks-Script.html) of the author "The script is assumed to be located at ~/.xmonad/hooks.".

**Comment by louwers** [comment]
Submitted a pull request: https://github.com/xmonad/xmonad-contrib/compare/master...louwers:patch-1

**Comment by geekosaur** [comment]
On Tue, Nov 8, 2016 at 9:54 AM, Bart <notifications@github.com> wrote:

> It makes no sense that ~/.xmonad/hooks startup (two files!) are executed
>

I believe it intends to run a script called "hooks" with a parameter
"startup".

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by louwers** [comment]
@geekosaur I didn't think about that... Closed!
