### ISSUE TITLE
X.P.Pass Read Store Passwords using symlink

### ISSUE THREAD

**Issue by davama** [xmonad/xmonad-contrib#117]
So i have identical environment for both my work and laptop computers by synchronizing relevant files/folders (.bashrc, .vimrc, .Xdefaults, etc)
All these synced files exist on a "Synced" folder in HOME. My ~/.bashrc is a symlink  which points to the Synced-folder/bashrc. This is how i have most of my relevant files setup, for example:
> lrwxrwxrwx  1 user     user        57 Nov  8 22:50 .bashrc -> ~/Synced-folder/bashrc

So i just started using gpg and pass to store/manage many of my passwords. ( it's awesome!)

So to go along with my setup i symlinked the ~/.gnupg and ~/.password-store folders to my sync folder. This did not affect access to my stored password and gpgkey

> gpg --list-keys
> pass show

All worked as before. 
The only difference is when i call "mod-p" to select a password i do not see the available passwords to choose from. I just get the prompt
> Select password:

Before it would say:
> group1/pass1  group2/pass2
> Select password:

Obviously this is probably because it's a symlink and not a folder file type. The select password prompt is still functional because i can select the password i want and `passPrompt` fetches it. The only issue is the "list of passwords available" does not exist.

`passGeneratePrompt` and `passRemovePrompt` work as expected

Is this something that can be looked at?
I know it's very specific to my case... but input is appreciated :D 

Thanks
Dave

**Comment by geekosaur** [comment]
On Fri, Nov 11, 2016 at 6:19 PM, Dave <notifications@github.com> wrote:

> Obviously this is probably because it's a symlink and not a folder file
> type. The select password prompt is still functional because i can select
> the password i want and passPrompt fetches it. The only issue is the
> "list of passwords available" does not exist.
>
The simple fix is to adjust the `find` command in `getPasswords` to add the
`-H` option. This is safe; I would be more hesitant about `-L`, if only
because a symlink in the actual gpg files should be considered a potential
security issue.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by davama** [comment]
Thanks for replying @geekosaur 

I attempted your advice but now change:

```
diff xmonad-test/xmonad-contrib/XMonad/Prompt/Pass.hs xmonad-git/xmonad-contrib/XMonad/Prompt/Pass.hs 
150c150
<     "-H", "-type", "f",
---
>     "-type", "f",
```

I even went back to real files for gpg and pass, not symlink, and even with the `-H` change i still got no list of "available passwords"

BTW: with symlinks and without both commands below give out same output:

> find -type f -name *.gpg -printf %P\n
> find -H -type f -name *.gpg -printf %P\n

Hope i did the change right.

Thanks

**Comment by davama** [comment]
Update:
I also tried with the `-L` option but no change.

Since this just my specific use case scenario ill just do a reverse symlink for syncing.

Thank you always for the support

-Dave

**Comment by geekosaur** [comment]
On Mon, Nov 14, 2016 at 8:39 AM, Dave <notifications@github.com> wrote:

> Since this just my specific use case scenario ill just do a reverse
> symlink for syncing.


FWIW I'm still trying to understand this. I'm tempted to ask for a
recursive directory tree, possibly omitting or obscuring file (not
directory) names, to try to understand why it was going wrong. In any case
-L should have followed/resolved all symlinks (which is not the default),
so something odd was definitely happening here.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by davama** [comment]
Thank you for replying @geekosaur 

> In any case -L should have followed/resolved all symlinks (which is not the default),

I would have thought the same too

> so something odd was definitely happening here.

Just to make sure i'm doing this correctly... this is my process flow for testing the symlink:

> cp -r .gnupg gnupg
cp -r .password-store password-store
rm -r .password-store/ .gnupg/
ln -s password-store/ .password-store
ln -s gnupg/ .gnupg
ll .gnupg
lrwxrwxrwx 1 dvmacias dvmacias 6 Nov 23 15:05 .gnupg -> gnupg/
ll .password-store
lrwxrwxrwx 1 dvmacias dvmacias 15 Nov 23 15:05 .password-store -> password-store/
\# recompile with both "-L" and "-H" options separately
\# no change :_( "Select password:" prompt works but the prompt that comes above it with a list of available passwords does not appear at all

The functionality of the `X.P.Pass` is not affected since i can manually type/select the passwords, delete, generate...

This is what `find` outputs using above created symlinks:

>  find -type f -name *.gpg -printf %P\n
gnupg/trustdb.gpgnpassword-store/emoticons/shrug.gpgnpassword-store/dsb/administrator.gpgnpassword-store/dsb/root.gpgn


> find -L -type f -name *.gpg -printf %P\n
gnupg/trustdb.gpgnpassword-store/emoticons/shrug.gpgnfind: ‘./password-store/password-store’: Too many levels of symbolic links
password-store/dsb/administrator.gpgnpassword-store/dsb/root.gpgn.gnupg/trustdb.gpgn.password-store/emoticons/shrug.gpgnfind: ‘./.password-store/password-store’: Too many levels of symbolic links
.password-store/dsb/administrator.gpgn.password-store/dsb/root.gpgn

> find -H -type f -name *.gpg -printf %P\n
gnupg/trustdb.gpgnpassword-store/emoticons/shrug.gpgnpassword-store/dsb/administrator.gpgnpassword-store/dsb/root.gpgn

Im willing to reopen/test further...

Thanks!
