### ISSUE TITLE
Actions.WindowsGo/raiseNextMaybe cycles between 2 workspaces only

### ISSUE THREAD

**Issue by pauleve** [xmonad/xmonad-contrib#120]
As reported some years ago in https://code.google.com/archive/p/xmonad/issues/284 raiseNextMaybe cycles only between 2 workspaces, making impossible to cycle through the entire list of windows.

The reason is that raiseNext calls allWindows from xmonad StackSet, which relies on a list of workspaces built as follows: the current workspace is put first, followed by visible then hidden workspaces. Thus the ordering of workspaces is not preserved while switching between workspaces, which is why raiseNext will 
cycle only between the current and another workspace.

I found the following fix:
- create a allWindowsSorted function in Xmonad.StackSet which relies on a list
of workspaces sorted by their tags
- call W.allWindowsSorted instead of W.allWindows in raiseNext.

The patch is given below for 0.12. Let me know if it is an appropriate way to fix the bug. If so, I can create 
the pull requests for xmonad and xmonad-contrib that apply on current master.
Otherwise, let me know what solution you would prefer. 
It would be nice that 0.13 contains a fix.

[xmonad-fix-raiseNextMaybe.patch](https://github.com/xmonad/xmonad-contrib/files/605921/xmonad-fix-raiseNextMaybe.patch.txt)

**Comment by IvanMalison** [comment]
why does allWindowsSorted need to go into StackSet. Just put it in contrib so that we dont have to deal with needing the latest version of xmonad for this to work.

**Comment by pauleve** [comment]
Ok, the issue is that StackSet does not export workspacesSorted ; hence this leads to some code duplication.
Here would be a patch which applies only on xmonad-contrib, but duplicates workspacesSorted from the main code:

[xmonad-contrib-fix-raiseNext.patch](https://github.com/xmonad/xmonad-contrib/files/624354/xmonad-contrib-fix-raiseNext.patch.txt)

**Comment by pauleve** [comment]
Sorry, actually, wokspacesSorted was introduced by my patch, so no code duplication :-)
I'm creating a pull request right now
