### ISSUE TITLE
Window location with XMonad.Layout.ThreeColumns seems erratic

### ISSUE THREAD

**Issue by oneself** [xmonad/xmonad-contrib#137]
### Problem Description

When using  XMonad.Layout.ThreeColumns windows move around erratically when creating new windows or closing existing windows.

Here is a flow where at first I have one window (a) open then open a second (b) and a third (c), then close them one by one.

```CREATE
1 [   a   ]
2 [b][ a  ]
3 [a][c][b]

CLOSE
1 [a][c][b]
2 [b][ a  ]
3 [   a   ]
```

So, when going from 2 to 3 open windows, window "a" and "b" switch
location for some reason. in step #2 "b" is on the left and "a" is on
the right, but when a third window is added (or removed) they swap
locations.  This is very confusing.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
module Main (main) where

import XMonad
import XMonad.Layout.ThreeColumns

main = xmonad defaultConfig { layoutHook = ThreeColMid 1 (3/100) (1/3) }
```

### Suggestion
There was a suggestion in the mailing list made by Daniel Wagner <dmwit@dmwit.com>:

In XMonad.Layout.ThreeColumns.split3HorizontallyBy, swap the second two elements of the triple in the True branch, so that it reads:

```    then ( Rectangle (sx + fromIntegral r3w) sy r1w sh
         , Rectangle sx sy r3w sh
         , Rectangle (sx + fromIntegral r3w + fromIntegral r1w) sy r2w sh )
```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by byorgey** [comment]
I've confirmed that Daniel's suggested fix does indeed seem to work.

**Comment by oneself** [comment]
Amazing!  Thank you so much.
