### ISSUE TITLE
[feature request] Is it possible to add an action of swapNth, i.e., swap the current window with the nth window

### ISSUE THREAD

**Issue by mogeiwang** [xmonad/xmonad-contrib#14]
The action of [focusNth](http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Actions-FocusNth.html), i.e., focus the nth window of the current workspace, is very helpful when there are a lot of windows in the current workspace.
I am writing to ask that, is it possible to add an action of swapNth, i.e., swap the current window with the nth window of the current workspace?

**Comment by byorgey** [comment]
Yes, this should definitely be possible.  To be honest I was a little surprised that this does not already exist somewhere, but after a quick search I can't find it.

Is this something you would be interested to try implementing yourself?

**Comment by mogeiwang** [comment]
@byorgey My problem is that, I am not that familar with xmonad and Haskell...

**Comment by byorgey** [comment]
OK, no worries.  I might have some time to take a shot at it soon---though if anyone else reading this would like to try, just leave a comment and go right ahead!
