### ISSUE TITLE
`wmctrl -d` doesn't show geometries

### ISSUE THREAD

**Issue by Procrat** [xmonad/xmonad-contrib#150]
### Problem Description

`wmctrl -d` should list the geometries of the desktops. I think this stopped working after the upgrade from v0.12 to v0.13.

`wmctrl -d` now shows
```
0  * DG: N/A  VP: N/A  WA: N/A  1
1  - DG: N/A  VP: N/A  WA: N/A  2
2  - DG: N/A  VP: N/A  WA: N/A  3
3  - DG: N/A  VP: N/A  WA: N/A  4
4  - DG: N/A  VP: N/A  WA: N/A  5
5  - DG: N/A  VP: N/A  WA: N/A  6
6  - DG: N/A  VP: N/A  WA: N/A  7
7  - DG: N/A  VP: N/A  WA: N/A  8
8  - DG: N/A  VP: N/A  WA: N/A  9
```
`wmctrl -d -v` shows this on stderr
```
envir_utf8: 1
Invalid type of _NET_DESKTOP_GEOMETRY property.
Cannot get common size of all desktops (_NET_DESKTOP_GEOMETRY).
Invalid type of _NET_DESKTOP_VIEWPORT property.
Cannot get common size of all desktops (_NET_DESKTOP_VIEWPORT).
Invalid type of _NET_WORKAREA property.
Invalid type of _WIN_WORKAREA property.
Cannot get _NET_WORKAREA property.
Total number of desktops: 9
Current desktop ID (counted from zero): 0
```

### Configuration File

```haskell
import XMonad
import XMonad.Config.Desktop

main :: IO ()
main = xmonad desktopConfig
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)
    I couldn't get this to work because of some linking error when running `stack build`.

**Comment by Procrat** [comment]
This is probably related to #79 and #143.
In these discussion the comparison was made with awesome, qtile and i3. However, [awesome sets `_NET_DESKTOP_GEOMETRY`](https://github.com/awesomeWM/awesome/blob/9c020877dd1357d7d42a29526d3567586f3db330/ewmh.c#L52) and [i3 sets `_NET_DESKTOP_VIEWPORT`](https://github.com/i3/i3/blob/8158e4c4155e15ea9442acd960a194376400788b/src/ewmh.c#L120).
Looking at the debug trace of `wmctrl -d -v`, it seems that setting one of these would fix this issue.

**Comment by pjones** [comment]
@Procrat Thanks for tracking this down.  Any chance you have some time to work on this?

**Comment by Procrat** [comment]
@pjones I currently solved it *for my specific case* by putting something like this in the startup hook:
```haskell
setEWMHDesktopGeometry = withDisplay $ \dpy -> do
    wm <- asks theRoot
    cardinalType <- getAtom "CARDINAL"
    desktopGeometryProp <- getAtom "_NET_DESKTOP_GEOMETRY"
    io $ do
        windowAttributes <- getWindowAttributes dpy wm
        let width = fromIntegral $ wa_width windowAttributes
            height = fromIntegral $ wa_height windowAttributes
        changeProperty32 dpy wm desktopGeometryProp cardinalType propModeReplace
                         [width, height]
```

I think there are some issues with this and it raised a couple of questions for me:
- In [the EWMH specs](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm140130317694112) I see that `_NET_DESKTOP_GEOMETRY` is defined as "the common size of all desktops". I don't know what this is supposed to mean when screens have different resolutions.
- I am not sure I get how XMonad handles multiple screens. What the function above does, is setting `_NET_DESKTOP_GEOMETRY` to the size of the root window. I see in [the XMonad startup code](https://github.com/xmonad/xmonad/blob/76f4a162587a8c6b58afe3d76341336cfe3c9aa3/src/XMonad/Main.hs#L174) that this is the root window of the default screen. I don't know how this would behave for multiple screens with different resolutions. I don't have a secondary screen, so I haven't been able to test this.

I would love to try to tackle this problem. It's only that I'm not so sure about the things I mentioned above.

**Comment by geekosaur** [comment]
There's two things going on here.

First, EWMH believes that desktops span monitors, and cannot be convinced otherwise. You can never provide proper EWMH information from xmonad (or dwm) because our workspace model is not compatible with EWMH,

Second: multiple monitors in X11 is a hack, and this is exposing that hack to some extent. The bounding box of the root window covers all of the monitors; `getScreenInfo` gives you the bounding boxes within the root window of the actual monitors. (This is why, if you run a program that is not Xinerama/XRANDR aware, it will draw itself across all monitors.) This bounding box may include regions that cannot be displayed, if the monitors are not all the same size and/or not all in line.

**Comment by pjones** [comment]
@Procrat As you pointed out previously, one way to solve this is to look at the source code for awesome or i3wm and replicate what they do.

**Comment by Procrat** [comment]
@geekosaur Thanks for the extensive background information. Everything makes much more sense now.

I looked a bit more into this. Awesome actually stopped setting all three properties.

| WM | DG | VP | WA | Model |
| - | - | - | - | - |
| awesome | | | | N/A |
| bspwm | | :heavy_check_mark: | | Workspace is a viewport on the screen |
| Fluxbox | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | Screen = Desktop = Viewport |
| herbstluftwm | | :heavy_check_mark: | | Screen = Viewport |
| i3 | | :heavy_check_mark: | | Workspace is a viewport on the screen |
| Metacity | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | Screen = Desktop = Viewport |
| Openbox | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | Screen = Desktop = Viewport |
| wmii | | :heavy_check_mark: | | Screen = Viewport |

To be honest, seeing that there is so much disagreement between these WMs, I get the feeling that this standard doesn't have much value.

Actually, the reason why I use the output of `wmctrl -d` is because I wanted a WM-independent way to know where to put a dzen/dmenu window on the focused monitor. I guess I'll just give up that dream.

If you agree that this is a pointless exercise, you can close this issue if you want.

**Comment by jonhoo** [comment]
As an additional data point here, `_NET_DESKTOP_VIEWPORT` is (afaict) the only way to determine what monitor a given workspace is being displayed on using EWMH. Without, it's difficult to do things like track which workspaces are currently visible (jaagr/polybar#950) or show which workspaces belong on which monitors (https://github.com/jaagr/polybar/issues/840#issuecomment-346576918).

**Comment by liskin** [comment]
Looks like there's been some "recent" development in this direction: https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/22

**Comment by slotThe** [comment]
Closing as "this probably won't happen upstream" :(
