### ISSUE TITLE
Online documentation source links broken - 404s

### ISSUE THREAD

**Issue by chrissound** [xmonad/xmonad-contrib#154]
http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Hooks-ManageDocks.html#t:AvoidStruts

All the 'Source' links appear broken: for example: http://xmonad.org/xmonad-docs/xmonad-contrib/src/XMonad-Hooks-ManageDocks.html#docksEventHook returns a 404

**Comment by pjones** [comment]
Thanks for reporting this.  Any chance you want to help get this fixed?

**Comment by chrissound** [comment]
Why don't we just redirect to hackage?

**Comment by pjones** [comment]
@chrissound at this point I think this would be the best option.  @geekosaur liked the idea of keeping the documentation on xmonad.org up to date with the master branch, but ultimately we don't have enough volunteers to maintain extra stuff like this.

@geekosaur, how do you feel about just redirecting to hackage?

Now, if that's something we decide to do, the next issue is figuring out how to do it.  xmonad.org is hosted by GitHub, I'm not sure how to do arbitrary redirects.  Any ideas?

**Comment by chrissound** [comment]
Cool, so I found the repo here: https://github.com/xmonad/xmonad-web
And the same issue is posted here: https://github.com/xmonad/xmonad-web/issues/4

If we do go the hackage route, possibly we could just set the HTML base https://developer.mozilla.org/en/docs/Web/HTML/Element/base to https://hackage.haskell.org/package/xmonad-0.13 I'm not really familiar with haddock but it might be a quick fix.

Though it would be nice to still sort out the existing 404s so we don't end up with dead links.

**Comment by geekosaur** [comment]
On Sun, Apr 9, 2017 at 1:31 PM, Peter J. Jones <notifications@github.com>
wrote:

> @geekosaur <https://github.com/geekosaur>, how do you feel about just
> redirecting to hackage?
>
>
I thought we were already agreed to do that; the local hosting was only
because hackage's doc builder was down for a while.


-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by f1u77y** [comment]
> keeping the documentation on xmonad.org up to date with the master branch

I think it's hardly useful because usually practically noone uses **exactly** the HEAD of master branch. Some of them do also use or test the modifications, so it's better to build documentation locally for them. 

And I support the idea of redirecting to hackage from xmonad.org.

**Comment by dmwit** [comment]
Done, see https://github.com/xmonad/xmonad-web/issues/4 for details.
