### ISSUE TITLE
spawnOnce does not run after re-login

### ISSUE THREAD

**Issue by favonia** [xmonad/xmonad-contrib#155]
### Problem Description

`spawnOnce` will not run the command after logout and login. It seems the records inserted by `spawnOnce` stay in `xmonad.state` forever. I am using `xmonad-contrib` version 0.13.

### Configuration File

```haskell
module Main where

import XMonad
import XMonad.Util.SpawnOnce

main :: IO ()
main = xmonad def { startupHook = spawnOnce "firefox" }
```

**Comment by pjones** [comment]
This is a bug caused by xmonad/xmonad#86

Thank you for reporting.  I'm going to close this as a duplicate.
