### ISSUE TITLE
worspacecompare getSortByXineramaPhysicalRule only sorts by (y,x)

### ISSUE THREAD

**Issue by thomasf** [xmonad/xmonad-contrib#157]
### Problem Description

Using the pictured layout DP-3 is sorted as the third screen instead of the first:

![image](https://cloud.githubusercontent.com/assets/330847/23832863/b219c744-073d-11e7-9b7e-88d059053c59.png)

To get a working situation quickly for myself I just copied the physical screen rule functions and reversed the sorting order to x,y instead of y,x but that probably causes problems with other configurations so it's not a general solution.

```diff
-  where rect i = let (Rectangle x y _ _) = screens !! fromIntegral i in (y,x)
+  where rect i = let (Rectangle x y _ _) = screens !! fromIntegral i in (x,y)
```

**Comment by geekosaur** [comment]
What does the `xrandr` command report about your screen configuration?

**Comment by thomasf** [comment]
```
Screen 0: minimum 8 x 8, current 7253 x 2160, maximum 32767 x 32767
DVI-D-0 connected 1313x2100+5940+60 left (normal left inverted right x axis y axis) 474mm x 296mm
   1680x1050     59.95*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
HDMI-0 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-0 connected primary 3840x2160+2100+0 (normal left inverted right x axis y axis) 708mm x 399mm
   3840x2160     60.00*+  30.00  
   2560x1440     59.95  
   1920x1080     60.00    59.94    50.00    60.05    60.00    50.04  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 connected 2100x1313+0+424 (normal left inverted right x axis y axis) 474mm x 296mm
   1680x1050     59.95*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
```

**Comment by thomasf** [comment]
maybe I misunderstood things but isn't the problem for the sorter that my `DP-3` is below the `DP-0` top Y position and therefore is put last?

**Comment by thomasf** [comment]
I guess that something more like the Nav2d sortedScreens function would maybe do the proper job for most situations...

**Comment by strokyl** [comment]
:+1: I would to be able to make it short comparing x and then y instead of y and then x

**Comment by pjones** [comment]
I'm not sure that changing the sort function is the correct solution.  Someone needs to look at this closer and understand the desired behavior and how xmonad could make that happen.

**Comment by geekosaur** [comment]
I think to handle this right xmonad would need to track exactly how things are positioned. For this you'd need to know if screens are horizontally vs. vertically stacked; but then you have the question of 2D stacks with different-sized monitors. (But I think in that case `getSortByXineramaRule` is going to have problems for much the same reason `Complex Double` doesn't have an `Ord` instance. You can't guess whether the user wants row or column major.)

If you stick to the 1D case then the correct way to go is probably to start with the root window's size (bounding box) and then figure out how screens are stacked (horizontal/sort by X vs. vertical/sort by Y), and possibly abort with an informative message if they're not strictly linear.

Alternately you could split this into two functions, horizontal vs. vertical; then you can also deal with the 2D case by treating the H/V as which one to sort by first. (Likely with a doc warning that there are no guarantees in the 2D case.)

**Comment by strokyl** [comment]
IMO, I think user would be happy if they could totally personalize the order by providing a function that receive two screen informations (id and top/left and bottom/right point coordinate) and return an Ordering.
Like that user will be able to totally customing sorting (using id and absolute sorting for the weirdest case). I have been told that is what Awesome do

**Comment by pjones** [comment]
@strokyl If you want to work on this please do!  I'll assign this issue to you.

**Comment by strokyl** [comment]
I will be very happy to

Le mer. 12 avr. 2017 14:26, Peter J. Jones <notifications@github.com> a
écrit :

**Comment by strokyl** [comment]
Here is a proposal PR: https://github.com/xmonad/xmonad-contrib/pull/182.

**Comment by strokyl** [comment]
Done https://github.com/xmonad/xmonad-contrib/pull/182
