### ISSUE TITLE
gridSelectWorkspace loses focus

### ISSUE THREAD

**Issue by MasseR** [xmonad/xmonad-contrib#16]
If I have gridSelectWorkspaces from XMonad.Actions.GridSelect active and I click a window on another screen, the gridselect loses focus and it can't be restored. If the gridselect has lost focus, you can't click it, can't type anything and can't escape out of it. The only way I've found to fix it is by restarting xmonad.

**Comment by f1u77y** [comment]
maybe adding grabPointer to gridselect will solve your problem. but i'm not sure is this solution or just a workaround
