### ISSUE TITLE
X.Prompt: Tab completing a second word erases the first

### ISSUE THREAD

**Issue by pjones** [xmonad/xmonad-contrib#164]
### Problem Description

I inadvertently introduced a bug in commit 57c00b1086359b0061ae5ce33aafc8b615e43ddb while attempting to improve the feedback of tab completion.

The bug: If `alwaysHighlight` is enabled and the user presses the completion key, Prompt will attempt to expand the completion and highlight the matching menu item.  If you then enter a space, type some more characters, then press the completion key again, the entire input line will be replaced with the completion of the second word.  Instead, the first word should remain unaffected while the second and subsequent words are completed successfully. 

Easy way to reproduce:

  * Configure the shell prompt to use `alwaysHighlight`

  * Bring up the shell prompt

  * Tab complete a shell command name that expects an argument

  * Enter a space, start typing the first argument (probably a file name), and hit tab

  * Notice that the command name was removed from the input buffer and replaced with the expanded argument.

**Comment by mavant** [comment]
Fixed by https://github.com/xmonad/xmonad-contrib/pull/170, I think.

**Comment by NickHu** [comment]
Yeah, this issue is fixed.
