### ISSUE TITLE
Support mpv by allowing it to remove `--x11-netwm=yes` option.

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad-contrib#176]
### Problem Description

Cuirrently, to get proper fullscreen support for mpv in XMonad, I have to pass `--x11-netwm=yes` to mpv.
Otherwise, mpv window becomes larger than the screen by border widths in fullscreen mode.

`man mpv` complains about XMonad for breaking X.

Perhaps, xmonad should fix this?

**Comment by f1u77y** [comment]
#109

**Comment by crocket** [comment]
Oh, I'm closing it. It seems it is a duplicate of that issue.
