### ISSUE TITLE
Firefox doesn't become a fullscreen window properly.

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad-contrib#183]
### Problem Description

Operating System : Gentoo Linux
Firefox : 53.0 built on Gentoo
xmonad : 0.13
xmonad-contrib : 0.13

When I press F11 in firefox, tabs disappear, but firefox doesn't become a fullscreen window.

![2017-05-19_fri_11 57 24](https://cloud.githubusercontent.com/assets/748856/26247475/fffdaeb4-3cd8-11e7-9805-40e277a8c959.png)

If I try to make a youtube video become a fullscreen window, I see

![2017-05-19_fri_11 57 34](https://cloud.githubusercontent.com/assets/748856/26247016/fa35c37e-3cd6-11e7-9a9d-3f896819a1a3.png)

https://bugzilla.mozilla.org/show_bug.cgi?id=1189622 says `RESOLVED FIXED in Firefox 46`, but I'm still experiencing the issue. Weirdly, tor browser, which is based on firefox, can become a proper fullscreen window.

### Configuration File

I tried both `XMonad.Hooks.EwmhDesktops` and `XMonad.Layout.Fullscreen`. They produce the same result. In the configuration below, I commented out `import qualified XMonad.Layout.Fullscreen as LF` to test `XMonad.Hooks.EwmhDesktops`'s fullscreen support.

```haskell
{-# LANGUAGE DuplicateRecordFields #-}
import XMonad
import qualified XMonad.StackSet as W
-- xmonad-contrib
import XMonad.Actions.PerWorkspaceKeys (chooseAction)
import XMonad.Actions.CycleWS ( findWorkspace, Direction1D(..)
                              , WSType(..), nextScreen, prevScreen
                              , shiftNextScreen, shiftPrevScreen)

import XMonad.Hooks.ManageDocks (docks, avoidStruts)
import XMonad.Hooks.DynamicLog ( dynamicLogWithPP, xmobarPP
                               , PP(..), xmobarColor
                               , shorten )
import qualified XMonad.Hooks.ManageHelpers as MH
import XMonad.Hooks.EwmhDesktops (ewmh, fullscreenEventHook)

import XMonad.Layout.NoFrillsDecoration (noFrillsDeco)
import XMonad.Layout.SimpleDecoration (shrinkText)
import XMonad.Layout.Spacing (smartSpacingWithEdge)
import XMonad.Layout.Tabbed (tabbed, addTabs)
import qualified XMonad.Layout.NoBorders as NB
import qualified XMonad.Layout.SubLayouts as SL
import XMonad.Layout.WindowNavigation (windowNavigation, Direction2D(..))
import XMonad.Layout.Renamed (renamed, Rename(Replace, CutWordsLeft))
-- import qualified XMonad.Layout.Fullscreen as LF
import XMonad.Layout.Accordion (Accordion(..))
import XMonad.Layout.Simplest (Simplest(..))
import qualified XMonad.Layout.BoringWindows as BW

import XMonad.Prompt.ConfirmPrompt (confirmPrompt)

import XMonad.Util.Run (spawnPipe)
import XMonad.Util.NamedActions ( showKm, subtitle
                                , addName, addDescrKeys', (^++^)
                                , NamedAction, sendMessage' )
import XMonad.Util.EZConfig ( mkNamedKeymap )
import XMonad.Util.WorkspaceCompare ( getSortByIndex
                                    , getSortByXineramaRule )
-- GHC
import System.IO (hPutStrLn)
import System.Exit (exitWith, ExitCode(..))
import qualified Data.Map.Strict as M
import Data.List (isPrefixOf, intercalate)
import Control.Monad (when, join)
import Text.Printf

myModMask :: KeyMask
myModMask = mod4Mask

main :: IO ()
main = do
  xmproc <- spawnPipe "xmobar"
  xmonad $ ewmh $ docks $ def
    { terminal = "/usr/bin/st"
    , modMask = myModMask
    , borderWidth = 2
    , layoutHook = myLayoutHook
    , logHook = dynamicLogWithPP $
                xmobarPP
                { ppOutput = hPutStrLn xmproc
                , ppTitle = xmobarColor "#d1f442" "" . shorten 50
                , ppSort = getSortByXineramaRule
                }
    , focusFollowsMouse = True
    , clickJustFocuses = False
    , manageHook =  myManageHook
                    -- <+> LF.fullscreenManageHook
    -- , handleEventHook = LF.fullscreenEventHook
    , handleEventHook = fullscreenEventHook
    , startupHook = spawn "compton"
    }

-- Windowing Policy
myManageHook = composeAll
  [ MH.isDialog --> MH.doCenterFloat
  , appName =? "xmessage" --> MH.doCenterFloat
  , appName =? "ibus-setup" --> MH.doCenterFloat
  , className =? "mpv" --> doFloat
  , appName =? "gxmessage" --> doFloat
  -- gimp
  , isPrefixOf "gimp-toolbox" <$> role --> doFloat
  , isPrefixOf "gimp-dock" <$> role --> doFloat
  ]
  where role = stringProperty "WM_WINDOW_ROLE"

-- Layout elements
myLayoutHook =
  -- LF.fullscreenFull $ -- fullscreen support for tiled windows
  -- LF.fullscreenFloat $ -- fullscreen support for floating windows
  -- remove borders from fullscreen floating windows
  NB.lessBorders NB.OnlyFloat $
  avoidStruts $ addTopBar $
  BW.boringWindows tabbedTall ||| BW.boringWindows tabs

tabbedTall = renamed [Replace "Tall"] $ windowNavigation $
  addTabs shrinkText def $
  SL.subLayout [] (Simplest ||| Accordion) $
  smartSpacingWithEdge 7 $
  NB.noBorders $ -- Remove borders from tiled windows
  Tall 1 (3/100) (53/100)

tabs = renamed [Replace "Tabbed"] $
  NB.noBorders $ -- Remove borders from tiled windows
  tabbed shrinkText def

addTopBar = renamed [CutWordsLeft 1] . noFrillsDeco shrinkText def
```

**Comment by crocket** [comment]
@sgf-dma I removed the parts that require `G` and `T`. They are not essential.

**Comment by sgf-dma** [comment]
Still doesn't compile:

    Preprocessing executable 'xmonad' for sgf-xmonad-1.2.2...
    [1 of 1] Compiling Main             ( src/xmonad.hs, .stack-work/dist/i386-linux/Cabal-1.24.0.0/build/xmonad/xmonad-tmp/Main.o )

    /home/test-xmonad/sgf-xmonad-config/src/xmonad.hs:64:21: error:
        Variable not in scope: workMain :: String

    /home/test-xmonad/sgf-xmonad-config/src/xmonad.hs:64:31: error:
        Variable not in scope: workDraw :: String

    /home/test-xmonad/sgf-xmonad-config/src/xmonad.hs:64:41: error:
        Variable not in scope: workLang :: String

    /home/test-xmonad/sgf-xmonad-config/src/xmonad.hs:74:64: error:
        Variable not in scope: scratchpads :: NamedScratchpads

**Comment by f1u77y** [comment]
You shouldn't mix fullscreen hooks from X.L.Fullscreen and X.H.EwmhDesktops. See docs for X.L.Fullscreen for setting it up and remove fullscreenEventHook from EwmhDestops. Or just use the last one but I think it's buggy, so you should use X.L.Fullscreen

**Comment by crocket** [comment]
@sgf-dma I deleted `scratchpads` and `workspaces`. You can try again.

@f1u77y I noticed that `X.H.EwmhDesktops.fullscreenEventHook` was poorer than `X.L.Fullscreen`.
I didn't mix fullscreen hooks from `X.L.Fullscreen` and `X.H.EwmhDesktops`. In my config above, `X.L.Fullscreen` is fully commented out.

**Comment by sgf-dma** [comment]
@crocket your config from 1st post works for me with following patch:

    $ diff -u xmonad-orig.hs xmonad.hs
    --- xmonad-orig.hs      2017-06-09 17:38:05.449568503 +0300
    +++ xmonad.hs   2017-06-09 17:36:47.707114675 +0300
    @@ -44,6 +44,8 @@
     import Control.Monad (when, join)
     import Text.Printf

    +import Data.Maybe (maybeToList)
    +
     myModMask :: KeyMask
     myModMask = mod4Mask

    @@ -67,7 +69,7 @@
                         -- <+> LF.fullscreenManageHook
         -- , handleEventHook = LF.fullscreenEventHook
         , handleEventHook = fullscreenEventHook
    -    , startupHook = spawn "compton"
    +    , startupHook = spawn "compton" >> addEWMHFullscreen
         }

     -- Windowing Policy
    @@ -104,3 +106,19 @@
       tabbed shrinkText def

     addTopBar = renamed [CutWordsLeft 1] . noFrillsDeco shrinkText def
    +
    +addNETSupported :: Atom -> X ()
    +addNETSupported x   = withDisplay $ \dpy -> do
    +    r               <- asks theRoot
    +    a_NET_SUPPORTED <- getAtom "_NET_SUPPORTED"
    +    a               <- getAtom "ATOM"
    +    liftIO $ do
    +       sup <- (join . maybeToList) <$> getWindowProperty32 dpy a_NET_SUPPORTED r
    +       when (fromIntegral x `notElem` sup) $
    +         changeProperty32 dpy r a_NET_SUPPORTED a propModeAppend [fromIntegral x]
    +
    +addEWMHFullscreen :: X ()
    +addEWMHFullscreen   = do
    +    wms <- getAtom "_NET_WM_STATE"
    +    wfs <- getAtom "_NET_WM_STATE_FULLSCREEN"
    +    mapM_ addNETSupported [wms, wfs]

It's a known issue, see #109 (note, this patch may not be enough) and [GLFW fullscreen](https://mail.haskell.org/pipermail/xmonad/2017-March/015224.html) .

**Comment by kc-kc** [comment]
Does anyone know if there has been any progress regarding this issue recently? I have implemented the proposed patch, and while it does fix Firefox, it breaks the full screen of other applications such as Minecraft. I have also tried using `ewmhFullscreen` option added in https://github.com/xmonad/xmonad-contrib/pull/109, however this does not seem to fix Firefox compatibility (yet it still breaks the fullscreen of other applications).

**Comment by liskin** [comment]
@kc-kc I use `ewmhFullscreen` and don't experience any problems. Firefox works, mpv works, many Steam games work. Are you using it the way it's documented?

**Comment by kc-kc** [comment]
@liskin Well, this is what I am using, and it seems to work with everything **except** Firefox (zathura, sxiv, discord). Is there anything that seems to be off?
```hs
main = do 
    xmproc <- spawnPipe "xmobar -x 0"
    xmonad $ docks $ ewmhFullscreen $ ewmh defaults {
        logHook = dynamicLogWithPP $ xmobarPP {
            ppOutput = hPutStrLn xmproc,
            ppCurrent = xmobarColor "#ff69b4" "",
            ppTitle = xmobarColor "pink" "" . shorten 60,
            ppSep = " | "
        }
        , manageHook = manageDocks <+> manageHook def
    }
```
If you want to see the entire config, I've got it hosted on my [dotfiles repository](https://github.com/kc-kc/dotfiles/blob/03b3bf93a682f0b0ae68db2884fa86efd2044015/.xmonad/xmonad.hs)

**Comment by liskin** [comment]
@kc-kc I tried your config and fullscreen in Firefox works like a charm.

The only thing off in your config is the unnecessary `manageDocks` that's already handled by `docks`, but that is entirely unrelated and I left it there when trying.

You also said that “yet it still breaks the fullscreen of other applications” but then you said “it seems to work with everything except Firefox” so I'm really confused about whether it works or not, and what your expectations about what “works” means are.

**Comment by liskin** [comment]
(The versions of xmonad and xmonad-contrib that I'm testing this with are here: https://github.com/liskin/dotfiles/tree/home/.xmonad/dep. They're slightly older and with non-upstream patches, but as far as EWMH and fullscreen is concerned, there shouldn't be any differences.)

**Comment by kc-kc** [comment]
> @kc-kc I tried your config and fullscreen in Firefox works like a charm.
> 
> The only thing off in your config is the unnecessary `manageDocks` that's already handled by `docks`, but that is entirely unrelated and I left it there when trying.
> 
> You also said that “yet it still breaks the fullscreen of other applications” but then you said “it seems to work with everything except Firefox” so I'm really confused about whether it works or not, and what your expectations about what “works” means are.

Sorry about the confusion, using `ewmhFullscreen` still does break Minecraft (and only Minecraft _so far_), but this is more of a minor complication when compared to the Firefox issue (for my personal use). Regardless, I will keep trying different things. Thanks for testing out my config, it helps me narrow down some possible problems.

**Comment by kc-kc** [comment]
Well, I have been attempting to install different versions using cabal, however everything cabal-install related doesn't seem to want to work. Regardless, I just wanted to let you know that I am currently using the `xmonad-git` and `xmonad-contrib-git` AUR packages in Arch Linux. I also am using the latest Firefox release in the Extra arch repos.

**Comment by kc-kc** [comment]
Alrighty, well I switched to Gentoo and cloned the current code in this repository to test. It seems to work perfectly with Firefox, so maybe there are some issues with the AUR package? Regardless, thank you for the help!

**Comment by podiki** [comment]
Works here too, on Arch with the AUR -git packages. I sometimes run into git packages that don't update (using yay) and require manual intervention, so that could be what happened here.

**Comment by slotThe** [comment]
Seems to be fixed; closing.
