### ISSUE TITLE
[question] emacsclient won't play with XMonad.Actions.SpawnOn.spawnOn

### ISSUE THREAD

**Issue by pbogdan** [xmonad/xmonad-contrib#184]
Adding:

```
spawnOn "emacs" "emacsclient -c --no-wait"
```

to the startup hook spawns it on the currently active workspace instead of shifting it to "emacs". I thought it could be due to emacsclient reporting itself as emacs:

```
WM_CLASS(STRING) = "emacs", "Emacs"
WM_NAME(STRING) = "emacs@laptop"
```

so I tried:

```
spawnAndDo
  (composeAll [className =? "Emacs" --> doShift "emacs"])
  "emacsclient -c --no-wait"
```

but this has no effect as well. Any ideas what could be going wrong or how to troubleshoot this further?

**Comment by geekosaur** [comment]
`spawnOn` expects that the window that will be opened will have `_NET_WM_PID` the same as the pid of the `emacsclient` process. But `emacsclient` sends a command to a running `emacs`, which gives the new window a `_NET_WM_PID` matching the `emacs`, not the `emacsclient`. See https://wiki.haskell.org/Xmonad/General_xmonad.hs_config_tips#Terminal_emulator_factories which is about fancy terminal emulators doing the same thing.

**Comment by pbogdan** [comment]
@geekosaur Thank you. And please forgive my ignorance - are you saying that even if I try to match against `WM_CLASS` as per my second snippet that still won't work due to  `PID` mismatch?

**Comment by geekosaur** [comment]
Correct because it's still the same `emacs` creating the window, and all such windows will have the same `className` and `appName`. In theory they could have different `WM_WINDOW_ROLE` values, but you'd have to write custom elisp to do it; emacs does not support it by default.

**Comment by geekosaur** [comment]
`emacsclient` supports those options for the case where it spawns a new `emacs`, btw, they do not and can not apply to an _existing_ `emacs` instance.

**Comment by pbogdan** [comment]
Thanks again! Gonna close this as it sounds there is no solution here that involves XMonad. Thanks again for your help.
