### ISSUE TITLE
XMonad.Util.Run.spawnPipe is unable to handle UTF-8 characters. safeSpawn destroys UTF-8 characters.

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad-contrib#187]
### Problem Description

```haskell
import XMonad.Util.Run (spawnPipe)

_gxMsgOpts :: String -> X ()
_gxMsgOpts msg = do
  h <- spawnPipe $ "gxmessage -file -"
  liftIO $ hPutStr h msg
  liftIO $ hClose h
  return ()
```

If msg contains UTF-8 characters, `_gxMsgOpts` destroys them. Look at the screenshot below. A message box containing "Close these windows" contains broken characters.

![2017-05-25_thu_01 57 27](https://cloud.githubusercontent.com/assets/748856/26440763/c27e8d6c-4168-11e7-82e2-7ccd1868758d.png)

The following two implementations handle UTF-8 characters smoothly.

```haskell
import XMonad.Util.Run (runProcessWithInput)

_gxMsgOpts :: MonadIO m => String -> m ()
_gxMsgOpts msg = do
  _ <- xfork $ do
    _ <- runProcessWithInput "gxmessage" ["-file", "-"] msg
    return ()
  return ()
```

```haskell
import System.Process (createProcess, proc)

_gxMsgOpts :: MonadIO m => String -> m ()
_gxMsgOpts msg = io $ do
  _ <- createProcess (proc "gxmessage" [msg])
  return ()
```

![2017-05-25_thu_07 40 50](https://cloud.githubusercontent.com/assets/748856/26440813/f0e38cfc-4168-11e7-8cc9-50a1616be274.png)

By just replacing `spawnPipe` with `runProcesswithInput` or `createProcess`, UTF-8 characters are handled properly.

I tried `safeSpawn`, too. It destroys UTF-8 characters via encodeString.

**Comment by crocket** [comment]
Do I need to fork `runProcessWithInput` with `xfork`? `runProcessWithInput` alone doesn't seem to freeze XMonad.

**Comment by slotThe** [comment]
I'd expect this to be fixed with e.g. `spawnPipeWithUtf8Encoding`; @crocket can you confirm?

**Comment by crocket** [comment]
I migrated to sway. I can't confirm. I don't have xmonad config.

**Comment by slotThe** [comment]
I will close this for now then; haven't heard of this bug ever since these were merged.  Feel free to re-open if you ever happen to jump back to xmonad and are still experiencing this on your system!
