### ISSUE TITLE
RFE: allow spawnOnce with spawnOn

### ISSUE THREAD

**Issue by fommil** [xmonad/xmonad-contrib#195]
### Problem Description

I want to spawn applications on startup, designated to specific workspaces. However, spawnOn and spawnOnce are mutually exclusive.

### Configuration File

My full config is https://github.com/fommil/dotfiles/blob/master/.xmonad/xmonad.hs

The relevant part is

```
startup :: Bool -> X ()
startup initial = do
                  when initial $ do
                    spawnOn "1" "urxvt"
                    spawnOn "2" "emacs"
                    spawnOn "3" "chromium"
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by f1u77y** [comment]
You could make rules in your `manageHook` to move your applications to corresponding workspaces instead

**Comment by fommil** [comment]
yeah, I though about that but I don't *always* want these apps on those workspaces. It's more like this is the base setup I expect when I log in.

**Comment by f1u77y** [comment]
`manageHook` moves them only initially but doesn't force them to be there forever.

**Comment by geekosaur** [comment]
ongy is looking into making a contrib module, which could eventually be merged to core, which provides a "new session"/"session restarted" flag in persistent `ExtensibleState`. This would replace the old parameter checking stuff, which was always a bit hacky (for example, won't work with `--replace`) and got significantly harder to use when https://github.com/xmonad/xmonad/commit/307b82a53d519f5c86c009eb1a54044a616e4a5c landed.

**Comment by marcsaegesser** [comment]
I just created pull request #239 that adds this functionality and a little more. @fommil does that look it does what you're looking for?

**Comment by fommil** [comment]
Oh awesome, thanks!
