### ISSUE TITLE
DynamicLog claims to configure ManageDocks

### ISSUE THREAD

**Issue by geekosaur** [xmonad/xmonad-contrib#215]
The `statusBar` combinator, and therefore `dzen` and `xmobar`, configure `avoidStruts` but not the other necessary hooks. This mostly worked before 0.12, but from 0.12 on its `avoidStruts` is ineffective without the other dock hooks. See xmonad#147.

The quick fix is probably to make it use `docks`. I am not sure that's a great idea in the case that the user's config already uses `docks` or individual hooks; duplicating hooks isn't a very good idea, especially `docksStartupHook` which has no choice but to enumerate all windows with `XQueryTree` in order to preload the strut cache.

**Comment by geekosaur** [comment]
Come to think of it, we also should have a `docksOn` whioch uses `avoidStrutsOn`.

**Comment by slotThe** [comment]
`statusBar` and variants have been using `docks` for quite some time, closing this.

**Comment by liskin** [comment]
That, and https://github.com/xmonad/xmonad-contrib/pull/406 restored the pre-0.12 behaviour of not requiring the startup hook.
