### ISSUE TITLE
XMonad.Prompt freezes if alwaysHighlight= True and maxComplRows is not Nothing

### ISSUE THREAD

**Issue by fabiodl** [xmonad/xmonad-contrib#217]
### Problem Description

Especially for XMonad.Prompt.Prompt (but the bug holds for XMonad.Prompt.Window) I set alwaysHighlight to True (to avoid the necessity of pressing tab for selection) but to keep the prompt window reasonably small I set maxComplRows to Just 3
If I have enough choices, so that some of them are not shown, and I keep pressing tab, when I select the first "off screen" one, the prompt freezes. To be specific, the prompt stays there, other xmonad keybindings become available (for instance, switching workspace) while applications do not receive keystrokes anymore (the mouse can be used, however).
stdout reports

user error (Pattern match failure in do expression at XMonad/Prompt.hs:911:3-14)

Expected behavior: as when alwayHighlight is false, complete the prompt with the first invisible entry. 
### Configuration File

, ((myModKey .|. shiftMask, xK_b     ), windowPrompt def{maxComplRows=Just 3,alwaysHighlight = True} Bring allWindows)
### Checklist

  - I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

**Comment by byorgey** [comment]
What version of xmonad are you using?

**Comment by fabiodl** [comment]
0.13, installed from cabal

**Comment by byorgey** [comment]
And when you run the version compiled from github, does it still give the same error `Pattern match failure in do expression at XMonad/Prompt.hs:911:3-14`?

**Comment by fabiodl** [comment]
Sorry, for the git version it becomes row 914
user error (Pattern match failure in do expression at XMonad/Prompt.hs:914:3-14)

**Comment by fabiodl** [comment]
I found out that when the error occurs, d seems not valid. Specifically, if I print d I get 
Display Prelude.!!: index too large. 
However, i have no idea where dpy is set

**Comment by geekosaur** [comment]
https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Prompt.hs#L420 and later stuffed into the `XPState`. But I don't see why this would be relevant to `(!!)` unless there are two different uses of `d` with one shadowing the other. `dpy` is not meaningful to anything but Xlib and the X server.

**Comment by fabiodl** [comment]
When the error does not occur, it contains what appears to be a pointer.

**Comment by geekosaur** [comment]
It's a pointer obtained from C to the Xlib `Display` structure, which is supposed to be opaque to anything other than Xlib internals (but is actually partially exposed if you know which knobs to turn). We obtain it from `openDisplay` aka `XOpenDisplay()` and then pass it to other Xlib routines, which is all that an Xlib consumer is allowed to do. (Similar constraints exist on the xcb version.)

**Comment by geekosaur** [comment]
And I don't think it should ever come from a list, since we can only manage one Xlib Display / Screen at a time. But `(!!)` arising here means something is being done lazily to get it. I'm not sure what, since the only things I see in `Prompt` using it are `XPState` field lookups.

**Comment by fabiodl** [comment]
Really thank you very much, that perfectly solved the issue!
