### ISSUE TITLE
manageDocks doesn't set event mask on already-(un)managed windows on mod-q restart

### ISSUE THREAD

**Issue by geekosaur** [xmonad/xmonad-contrib#221]
If you start a dock and then mod-q, the dock will continue to be unmanaged via the relayed `StackSet` and will not be run through the `manageHook` again, and `docksStartupHook` does not itself set the window's event mask to notify us if it is resized or it changes its strut property. So we will no longer detect changes to that dock unless it is restarted or unmapped/remapped so it goes through the `manageHook` again.

**Comment by geekosaur** [comment]
Also note that mod-q will force the strut cache to update to match the current window state, so this will not make it obvious that we're no longer monitoring for changes.

**Comment by liskin** [comment]
Fixed in #492, I believe.
