### ISSUE TITLE
Actions.Minimize may use something other than iconicState

### ISSUE THREAD

**Issue by xaengceilbiths** [xmonad/xmonad-contrib#224]
### Problem Description

I found that XMonad.Actions.Minimize set the window state to iconicState to make a window disappear. XMonad.Operations also use this method when switch to another workspace. This is rather confusing because other software(like libwnck, or gnome-panel's workspace-switcher) can't differentiate the two actions and do something like draw the right layout of inactive workspace.

My workspace-switcher use modified libwnck like this:
```diff
diff --git a/libwnck/pager.c b/libwnck/pager.c
index 53e9f6a..8d696c6 100644
--- a/libwnck/pager.c
+++ b/libwnck/pager.c
@@ -899,7 +899,7 @@ get_windows_for_workspace_in_bottom_to_top (WnckScreen    *screen,
   for (tmp = windows; tmp != NULL; tmp = tmp->next)
     {
       WnckWindow *win = WNCK_WINDOW (tmp->data);
-      if (wnck_pager_window_get_workspace (win, TRUE) == workspace_num)
+      if (wnck_pager_window_get_workspace (win, FALSE) == workspace_num)
        result = g_list_prepend (result, win);
     }
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

**Comment by slotThe** [comment]
> This is rather confusing because other software(like libwnck, or gnome-panel's workspace-switcher) can't differentiate the two actions and do something like draw the right layout of inactive workspace.

I'm not sure what this means.

Isn't setting the iconic state exactly what X.A.Minimize _should_ do?  [The spec](https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.4) states that

> IconicState - The client's top-level window is iconic (whatever that means for this window manager). The client can assume that its top-level window is not viewable, its icon_window (if any) will be viewable and, failing that, its icon_pixmap (if any) or its WM_ICON_NAME will be displayed.

This would seem to fit with "a window is minimized and therefore unmapped" and "a window is on another workspace and therefore unmapped"

**Comment by TheMC47** [comment]
I agree with @slotThe, the spec doesn't differentiate between "minimized" and "in another workspace". Maybe it's possible to do something on the `XMonad.Hooks.EwmhDesktops` side.
