### ISSUE TITLE
Haddock generation currently fails on X.P.FuzzyMatch

### ISSUE THREAD

**Issue by LSLeary** [xmonad/xmonad-contrib#249]
### Problem Description

Haddock generation currently fails, also causing any cabal build without haddock generation disabled to fail.

The problem is a parse error on the first import in XMonad.Prompt.FuzzyMatch. It appears that the imports need to come before the $usage block—I tried shifting them there and now it's building.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by byorgey** [comment]
Makes sense - would you be willing/able to open a pull request to fix it?
