### ISSUE TITLE
WindowGo/runOrRaiseNext must cycle through all client workspaces

### ISSUE THREAD

**Issue by alesandar** [xmonad/xmonad-contrib#251]
### Problem Description

Not an issue, but a feature request. If some client has been copied to another workspace by using the CopyWindow plugin functionality, runOrRaiseNext will not focus any other workspace, except the first one where the client occurs. In my opinion, it will be good if runOrRaiseNext switches between all client workspaces instead. Anyone with the knowledge how to implement that? I am not that good with Haskell.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by LSLeary** [comment]
I don't use the X.A.WindowGo so I'm not familiar with the source, but I took a look at a few functions and I think I think I know how you can accomplish what you want. Take this with a grain of salt:

The problem isn't really `runOrRaiseNext` so much as it is `W.focusWindow`. Luckily the module exports a more general version by the name of `raiseNextMaybeCustomFocus` which allows you to use a focusing function other than `W.focusWindow`. You could write such a function in your config that took the workspace traversal order as an extra parameter then used it to decide which workspace's copy of the window to focus on. Good use of existing functions could make this a lot easier; e.g. it might suffice to make the chosen workspace current with `W.view` or `W.greedyView` before using `W.focusWindow` as normal. The extra parameter can later be eliminated by writing another X () action that asks for the information (something like `order <- asks (workspaces . config)` before passing it on.

**Comment by alesandar** [comment]
Thanks a lot for your advice, @LSLeary. I will take a closed look in `W.focusWindow` and `W.view`.

**Comment by slotThe** [comment]
This seems solved; @alesandar feel free to re-open if it's not.
