### ISSUE TITLE
X.L.Spacing reload error after update

### ISSUE THREAD

**Issue by davama** [xmonad/xmonad-contrib#267]
### Problem Description

Hello, i've recently updated my xmonad repositories [crontrib](https://github.com/xmonad/xmonad-contrib), [xmonad](https://github.com/xmonad/xmonad), [extras](https://github.com/xmonad/xmonad-extras) to the latest commit. After a reload i received this error:

```
Error detected while loading xmonad configuration file: /home/dvmacias/.xmonad/xmonad.hs

xmonad.hs:222:63: error:
    • Couldn't match expected type ‘Integer’ with actual type ‘Int’
    • In the first argument of ‘spacing’, namely ‘s’
      In the second argument of ‘(.)’, namely ‘(spacing s)’
      In the expression:
        (gaps [(U, s), (R, s), (L, s), (D, s)]) . (spacing s)
    |
222 | gapper s = (gaps [(U, s), (R, s), (L, s), (D, s)]) . (spacing s)
    |                                                               ^

xmonad.hs:235:46: error:
    • Couldn't match expected type ‘Int’ with actual type ‘Integer’
    • In the second argument of ‘grid’, namely ‘myBorderSpace’
      In the second argument of ‘named’, namely
        ‘(grid G.T myBorderSpace)’
      In the first argument of ‘(|||)’, namely
        ‘named "TT" (grid G.T myBorderSpace)’
    |
235 |                     ||| named "TT" (grid G.T myBorderSpace) -- grid ; Top ; spacing
    |                                              ^^^^^^^^^^^^^

Please check the file for errors.

xmonad: xmessage: executeFile: does not exist (No such file or directory)
```
### Configuration File

```
gapper s = (gaps [(U, s), (R, s), (L, s), (D, s)]) . (spacing s)
grid orientation s = gapper s $ G.SplitGrid orientation 1 1 (1/2) (16/9) (5/100)
 
myLayoutHook = onWorkspace (myWorkspaces !! 8) (avoidStruts (imLayout) ||| avoidStruts (standardLayouts))
...
         $ onWorkspaces ["DEV1","DEV2"] (avoidStruts (threeLayout) ||| avoidStruts (standardLayouts))
             $ avoidStruts (standardLayouts) ||| fullscreen
  where
    standardLayouts = named "+" (spacing myBorderSpace $ reflectHoriz $ G.Grid (16/10)) -- grid
                    ||| named "TT" (grid G.T myBorderSpace) -- grid ; Top ; spacing
                    ||| named "[]-" (grid G.L myBorderSpace) -- grid ; left ; spacing
                    ||| named "_+_" (grid G.B myBorderSpace) -- grid ; bottom ; spacing
                    ||| named "-[]" (grid G.R myBorderSpace) -- grid ; right ; spacing
    chatLayout = named "IML" $ withIM 0.4 (Role "pop-up") $ reflectHoriz $ withIM 0.3 (Role "pop-up") (trackFloating (grid G.T 0)) -- pop-up is WhatApp and Google Hangouts; whoever opens first
    gimpLayout = named "GimpL" $ withIM 0.2 (Role "gimp-dock") $ reflectHoriz $ withIM 0.3 (Role "gimp-dock") (trackFloating (grid G.T 0)) -- Gimp Layout
```

This particular config in my `xmonad.hs` has existed since [2016](https://github.com/davama/xmonad/commit/53ef04015b7fdcced8ab0b36ea69e206881e7f67#diff-902995c1e013489f16d46c844c93af9f) and now it's failing. 

What may have caused this? Any input on how to resolve it?
Thank you in advance

-dave

**Comment by davama** [comment]
@LSLeary 
thank you for the reply and useful info.
> work every now and then. When that happens it's best to either track down the cause and see what actions need to be taken, or temporarily revert to a checkout from a month or two back (your config will probably start working again at some point).

Yes, i forget that sometimes, my apologies. I'll revert my clone back to see when it starts working again

Should i close this or simply wait?

**Comment by LSLeary** [comment]
I can notify you here when the work on `X.L.Spacing` looks complete; I'd say wait and see whether or not your config is still broken then.

**Comment by davama** [comment]
Sounds good!
Thank you

**Comment by davama** [comment]
If it's of any use, i had to rollback to https://github.com/xmonad/xmonad-contrib/commit/108431d03db0558978e56ab740a5b90be2d2cb95 for my config to work

**Comment by LSLeary** [comment]
@davama X.L.Spacing should be stable now.

**Comment by davama** [comment]
Just an update:

Had to make some edits to xmonad-extras.cabal file to build.

https://github.com/xmonad/xmonad-extras/pull/16

X.L.Spacing works as before
