### ISSUE TITLE
Fails to compile with GHC 8.4.3/8.4.2

### ISSUE THREAD

**Issue by mosteli** [xmonad/xmonad-contrib#268]
### Problem Description

I'm trying to get Xmonad set up with a configuration file but I can't get it to compile.
I realize it is X11-xft that is failing, but that package seems dormant so I'm posting here.

### Configuration File

N/A

cabal install . --with-ghc=ghc-8.4.2
Resolving dependencies...
Configuring X11-xft-0.3.1...
Building X11-xft-0.3.1...
Failed to install X11-xft-0.3.1
Build log ( /home/emost/.cabal/logs/X11-xft-0.3.1.log ):
Configuring X11-xft-0.3.1...
Preprocessing library for X11-xft-0.3.1..
Building library for X11-xft-0.3.1..
[1 of 2] Compiling Graphics.X11.Xrender ( dist/build/Graphics/X11/Xrender.hs, dist/build/Graphics/X11/Xrender.o )

Graphics/X11/Xrender.hsc:23:1: warning: [-Wtabs]
    Tab character found here, and in 95 further locations.
    Please use spaces instead.
   |
23 |         v <- peekByteOff ptr (fromIntegral off)
   | ^^^^^^^^
[2 of 2] Compiling Graphics.X11.Xft ( dist/build/Graphics/X11/Xft.hs, dist/build/Graphics/X11/Xft.o )

Graphics/X11/Xft.hsc:10:1: warning: [-Wtabs]
    Tab character found here, and in 143 further locations.
    Please use spaces instead.
   |
10 |                         , xftcolor_pixel
   | ^^^^^^^^
cabal: Error: some packages failed to install:
X11-xft-0.3.1 failed during the final install step. The exception was:
user error (Couldn't parse the output of 'setup register
--gen-pkg-config':NoParse "license" 5)
xmonad-contrib-0.13 depends on X11-xft-0.3.1 which failed to install.

**Comment by mosteli** [comment]
Yes, I used the version including #236. I'm new to Cabal so that could be part of the issue.
I couldn't get either xmonad or xmonad-contrib to compile from the latest respective repo cloned from GitHub.

**Comment by BadDecisionsAlex** [comment]
I have gotten xmonad, xmonad-contrib, and xmonad-extras to install with ghc-8.6.2 (cabal install xmonad-contrib --flags="-use-xft")
Which is running perfectly. However, xmobar fails to install because of this exact error. (license 5 on X11-xft)

Let me know if y'all found a solution.

**Comment by IvanMalison** [comment]
This should be closed, contrib and xmonad both compile with these and newer ghc.
