### ISSUE TITLE
All windows invisible when using fullscreenSupport

### ISSUE THREAD

**Issue by cumber** [xmonad/xmonad-contrib#278]
### Problem Description

After I upgraded to Xmonad 0.14 (and xmonad-contrib 0.14), all my application windows (including a taffybar panel) became completely invisible. I can tell that they're there (and that xmonad is responding to keyboard shortcuts that e.g. open a terminal window) by switching to a text console and running `ps`. It doesn't seem to be possible to give any of the running processes keyboard focus from within xmonad (e.g. by using `mod-j`).

I managed to isolate the problem to using `fullscreenSupport` from `XMonad.Layout.Fullscreen` (which I've been using for years). If I remove that from my configuration the problem disappears.

### Configuration File

```haskell
module Main
  ( main )
where

import XMonad ( def, launch )
import XMonad.Layout.Fullscreen ( fullscreenSupport )

main :: IO ()
main = launch . fullscreenSupport $ def
```

(I'm running xmonad on a Nixos system, tracking the nixos-unstable channel. I compile xmonad as a static executable into the nix store, rather than letting xmonad recompile itself from ~/.xmonad, which is why I use `launch`).

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by orbisvicis** [comment]
I don't see how the changes to `XMonad.Layout.Fullscreen` could have caused behaviour other than what you describe in this bug report. Can you test the following changes?
```haskell
import qualified XMonad.Util.Rectangle as R
```
```haskell
  pureModifier (FullscreenFull frect fulls) rect _ list =
    (visfulls' ++ rest', Nothing)
    where (visfulls,rest) = partition (flip elem fulls . fst) list
          visfulls' = map (second $ const rect') visfulls
          rest' = if null visfulls'
                  then rest
                  else filter (not . R.supersetOf rect' . snd) rest
          rect' = scaleRationalRect rect frect

```

**Comment by cumber** [comment]
I've patched that into xmonad-contrib locally and rebuilt, and yes that makes my configuration usable again with `fullscreenSupport`.

**Comment by orbisvicis** [comment]
@cumber I opened a PR (needs review) that I haven't tested, do you mind testing it and leaving your feedback there?

**Comment by cumber** [comment]
@orbisvicis Thanks again for fixing it!

Should I close this issue now the PR's been merged, or leave it open until a release is made?

**Comment by byorgey** [comment]
@cumber Yes, typically you would close this issue once a fix has been merged into master.
