### ISSUE TITLE
Missing bounds on containers & base

### ISSUE THREAD

**Issue by hvr** [xmonad/xmonad-contrib#28]
Otherwise this breaks for pre `containers-0.5` releases:

```
XMonad/Actions/DynamicProjects.hs:48:18:
    Could not find module `Data.Map.Strict'
    Use -v to see a list of the files searched for.
```

Moreover,

```
XMonad/Actions/DynamicProjects.hs:50:21:
    Module `Data.Monoid' does not export `(<>)
```

limits `xmonad-contrib-0.12` to `base >= 4.5`

I've already edited them in on Hackage, see http://hackage.haskell.org/package/xmonad-contrib-0.12/revisions/

**Comment by byorgey** [comment]
Thanks!
