### ISSUE TITLE
Layout.NoBorders doesn't remove some borders in multihead setup

### ISSUE THREAD

**Issue by volfyd** [xmonad/xmonad-contrib#280]
### Problem Description

Layout.NoBorders fails to remove borders on inactive screens in the following scenario:

Use smartBorders
On one monitor, fullscreen chrome. The borders disappear.
Then press mod-e to move to another monitor. The borders on chrome reappear.

Reverting https://github.com/xmonad/xmonad-contrib/commit/c6cdb77e3b3d6a3842b914a0cf64357f03fcf0c1 fixes the issue. The code related to the regression is probably under the section 

```
 It seems more efficient to have each layout manage
            -- its own floating windows - and equally valid though untested
            -- against a multihead setup.

```

**Comment by liskin** [comment]
Can you please try if https://github.com/xmonad/xmonad-contrib/pull/440 fixes this?
