### ISSUE TITLE
Advertising fullscreen support in XMonad.Layout.Fullscreen

### ISSUE THREAD

**Issue by flupe** [xmonad/xmonad-contrib#288]
As said in xmonad/xmonad#54 regarding `XMonad.Hooks.EWMHDesktops` :

> We do have one shortcoming in EWMH support: because the handleEventHook
(and functions in general) can't be introspected, we can't add the atom for
fullscreen support to the EWMH support advertisement. 

This explains why in `XMonad.Hooks.EWMHDesktops.`, `_NET_WM_STATE_FULLSCREEN` is not added to `_NET_SUPPORTED` since someone might not actually handle fullscreen in their XMonad config.

The same reasons have been given in #109, with some discussion about providing more options in  `XMonad.Hooks.EWMHDesktops`, and some [homemade fixes](https://gist.github.com/sgf-dma/a609f855bbacf1a0292e660c32a5a04e) to support applications that do check if fullscreen is supported, like [sxiv](https://github.com/muennich/sxiv).

My question is the following: Why don't we advertise support for fullscreen in `XMonad.Layout.Fullscreen` itself? Since the single purpose of this module is to add fullscreen support, it seems to me that adding the following startup hook would not hurt:

```haskell
fullscreenStartupHook :: X ()
fullscreenStartupHook = withDisplay $ \dpy -> do
    r <- asks theRoot
    a <- getAtom "_NET_SUPPORTED"
    c <- getAtom "ATOM"
    f <- getAtom "_NET_WM_STATE_FULLSCREEN"
    io $ do
        sup <- (join . maybeToList) <$> getWindowProperty32 dpy a r
        when (fromIntegral f `notElem` sup) $
            changeProperty32 dpy r a c propModeAppend [fromIntegral f]
```
This fixed fullscreen support for sxiv, and I think people using `XMonad.Layout.Fullscreen` should expect fullscreen to be advertised in `_NET_SUPPORTED`.

Waiting for more opinions on this, I'd be glad to prepare a PR if needed.

**Comment by texttheater** [comment]
+1 - I added this startup hook to my `xmonad.hs` and it fixes the fullscreen issue with Firefox. Would be nice to have this in `XMonad.Layout.Fullscreen`.

For the benefit of those who want to add it to your config now, you need these additional imports:

```
import Control.Monad
import Data.Maybe
```

**Comment by liskin** [comment]
Well, we might want to merge https://github.com/xmonad/xmonad-contrib/pull/109 at long last.

**Comment by audunska** [comment]
Author of X.L.Fullscreen here. I like this idea! Sorry for not seeing it earlier. I would support a PR.

**Comment by flupe** [comment]
Hey @audunska, I'm sadly no longer an xmonad user, but I think @liskin's PR #109 got merged last november.
https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Layout/Fullscreen.hs#L82
It seems as though this issue has been resolved and should now be closed.

**Comment by audunska** [comment]
Yeah, sorry, I am also not using xmonad actively anymore, so I didn't notice :)
