### ISSUE TITLE
[XMonad.Layout.Spacing] Missing boundary checks in shrinkRect

### ISSUE THREAD

**Issue by bb-h8** [xmonad/xmonad-contrib#32]
There are boundary checks missing in shrinkRect. Too small rectangles before pureModifier cause an underflow when substracting the spacing in shrinkRect. The resulting absurd rectangle dimensions crash the windows that are paired with them. This happens mostly in Layout like BSP and Spiral.

Is:
```
shrinkRect :: Int -> Rectangle -> Rectangle
shrinkRect p (Rectangle x y w h) = Rectangle (x+fi p) (y+fi p) (w-2*fi p) (h-2*fi p)
```
Should be:
```
shrinkRect :: Int -> Rectangle -> Rectangle
shrinkRect p (Rectangle x y w h) = Rectangle (x+fi p) (y+fi p) (fi $ max 1 $ fi w-2*p) (fi $ max 1 $ fi h-2*p)
```

**Comment by byorgey** [comment]
Why are the extra calls to `fi` after `max` necessary?

In any case, I think you are right.  Would you be interested in making a pull request?

**Comment by bb-h8** [comment]
`w`  and `h` are of type Dimension, so unsigned, `p` is an Int. The results of the differences has to be signed for the underflow not to happen, so `w` and `h` are converted to Int. But the width and height of the resulting Rectangle have to be Dimension again, so the results of max are converted back again.

I have somewhat limited knowledge about git in general and github in particular, but I'll look into it.
