### ISSUE TITLE
CycleRecentWS doesn't ignore the (supposedly) hidden workspace NSP

### ISSUE THREAD

**Issue by poscat0x04** [xmonad/xmonad-contrib#332]
### Problem Description

The workspace NSP is not ignored by CycleRecentWS and triggering `scratchpadSpawn` will cause it to become the second most recent workspace.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment]
A priori, `CycleRecentWS` and `NamedScratchpad` don't know of each others existence and so you will probably need to reconcile them yourself.  Luckily the `recentWS` function in that module already expects some sort of filter as an argument.

For example, rewriting `cycleRecentWS` to something that ignores the NSP workspace:

```haskell
import           XMonad.Actions.CycleRecentWS (cycleWindowSets, recentWS)
import qualified XMonad.StackSet              as W

cycleRecentWSIgnoreNSP :: [KeySym] -> KeySym -> KeySym -> X ()
cycleRecentWSIgnoreNSP = cycleWindowSets $ recentWS ((/= "NSP") . W.tag)
```

**Comment by slotThe** [comment]
I will close this for now, @poscat0x04 feel free to re-open if the above snippet doesn't fix your issue.
