### ISSUE TITLE
subLayout/subTabbed stuck in full screen?

### ISSUE THREAD

**Issue by tamis-laan** [xmonad/xmonad-contrib#341]
I'm trying out xmonad for the first time and I'm not sure if this is a bug or if I'm doing something wrong.

I'm working with the subTabbed  layout modifier, when I start xmonad I get suck in full screen mode. I can move focus from window to window but I can no longer switch layout. I get the same behavior when using subLayout.

As an example using the following layout:
```haskell
myLayout = windowNavigation $ subTabbed $
  tiled ||| Mirror tiled ||| Full
  where
     -- default tiling algorithm partitions the screen into two panes
     tiled   = Tall nmaster delta ratio
     -- The default number of windows in the master pane
     master = 1
     -- Default proportion of screen occupied by master pane
     ratio   = 1/2
     -- Percent of screen to increment by when resizing panes
     delta   = 3/100
```

I would expect to start with the tiled, Mirror tiled and Full layout. Then when I do a pullGroup operation I merge two windows into a tabbed subLayout. 

However this is not the case I just get stuck into full screen unable to switch layout.

These are the modifier key's I'm either using or tried out:
```haskell
    --, ((modm .|. controlMask, xK_h), sendMessage $ pullGroup L)
    --, ((modm .|. controlMask, xK_l), sendMessage $ pullGroup R)
    --, ((modm .|. controlMask, xK_k), sendMessage $ pullGroup U)
    --, ((modm .|. controlMask, xK_j), sendMessage $ pullGroup D)
    --, ((modm .|. controlMask, xK_m), withFocused (sendMessage . MergeAll))
    --, ((modm .|. controlMask, xK_u), withFocused (sendMessage . UnMerge))
    --, ((modm .|. controlMask, xK_period), onGroup W.focusUp')
    --, ((modm .|. controlMask, xK_comma), onGroup W.focusDown')
    --, ((modm,                 xK_Right), sendMessage $ Go R)
    --, ((modm,                 xK_Left ), sendMessage $ Go L)
    --, ((modm,                 xK_Up   ), sendMessage $ Go U)
    --, ((modm,                 xK_Down ), sendMessage $ Go D)
    --, ((modm .|. controlMask, xK_Right), sendMessage $ Swap R)
    --, ((modm .|. controlMask, xK_Left ), sendMessage $ Swap L)
    --, ((modm .|. controlMask, xK_Up   ), sendMessage $ Swap U)
    --, ((modm .|. controlMask, xK_Down ), sendMessage $ Swap D)
    , ((modm .|. controlMask, xK_Left), (sendMessage . pullGroup) L)
    , ((modm .|. controlMask, xK_Right), (sendMessage . pullGroup) R)
    , ((modm .|. controlMask, xK_Up), (sendMessage . pullGroup) U)
    , ((modm .|. controlMask, xK_Down), (sendMessage . pullGroup) D)
```

In case relevant all the imports I'm using:
```haskell
import XMonad
import Data.Monoid
import System.Exit
import qualified XMonad.StackSet as W
import qualified Data.Map        as M
import XMonad.Layout.PerWorkspace
import XMonad.Layout.Tabbed
import XMonad.Layout.SubLayouts
import XMonad.Layout.WindowNavigation
import XMonad.Util.NamedScratchpad
import XMonad.Util.SpawnOnce
import XMonad.Layout.Simplest
import XMonad.Layout.Circle
```

Wondering If i'm doing something wrong or if this is related to some bug?

**Comment by tamis-laan** [comment]
It seams the problem is not with subLayout as the following works:
```haskell
myLayout = windowNavigation $ boringWindows $ subLayout [] (Accordion) 
                    $ Tall 1 0.2 0.5 ||| Full 
```
However when I'm using tabs I end up stuck in full screen mode:
```haskell
myLayout = windowNavigation $ boringWindows $ subLayout [] (simpleTabbed) 
                    $ Tall 1 0.2 0.5 ||| Full 
```
Even using simple tabbed on it's own get's me stuck:
```haskell
myLayout = simpleTabbed
```
What gives?

**Comment by geekosaur** [comment]
When one of those layouts fails by itself, it usually means tab
drawing crashed (threw an exception) because a font is missing. Some
linux distributions no longer install the "fixed" font by default, so
there is no guaranteed-to-be-installed font we can rely on on all
supported platforms any more.

You can fix this by installing the "fixed" font, aliasing it to "Mono"
in fontconfig, or specifying another font for Decoration to use.

On 5/22/20, Tamis <notifications@github.com> wrote:
> It seams the problem is not with subLayout as the following works:
> ```haskell
> myLayout = windowNavigation $ boringWindows $ subLayout [] (Accordion)
>                     $ Tall 1 0.2 0.5 ||| Full
> ```
> However when I'm using tabs I end up stuck in full screen mode:
> ```haskell
> myLayout = windowNavigation $ boringWindows $ subLayout [] (simpleTabbed)
>                     $ Tall 1 0.2 0.5 ||| Full
> ```
> Even using simple tabbed on it's own get's me stuck:
> ```haskell
> myLayout = simpleTabbed
> ```
> What gives?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/xmonad/xmonad-contrib/issues/341#issuecomment-632749297


-- 
brandon s allbery kf8nh
allbery.b@gmail.com

**Comment by tamis-laan** [comment]
So if I set the font to an existing font it should work? i.e.
```Haskell
myTabConfig = def { inactiveBorderColor = "#FF0000"
                  , activeTextColor = "#00FF00"
                  , fontName="Hack"}
myLayout = tabbed shrinkText myTabConfig
```
Because I then still have the same problem, stuck in full screen without tabs.

**Comment by geekosaur** [comment]
Check the session log (where this is depends on your system but *may*
be ~/.xsession-errors). It's also possible that it's not using
fontconfig depending on how it was built, but that seems unlikely.

This said, at minimum you need both a name and a size ("Hack-10" or
similar, or see either fontconfig or XLFD for other ways to specify
fonts).

-- 
brandon s allbery kf8nh
allbery.b@gmail.com
