### ISSUE TITLE
Change border color of neighboring windows to focus window?

### ISSUE THREAD

**Issue by tamis-laan** [xmonad/xmonad-contrib#342]
The border color of a neighboring window next to the focused window seams to inherit a softer version of the myFocusedBorderColor. 

Is it possible to turn this feature off? 

I would like all the windows to have a border color of myNormalBorderColor unless focused then it should have a border color of myFocusedBorderColor.

**Comment by geekosaur** [comment]
It's showing both borders next to each other, because the border is part of
the window, not outside of it. There is no way to change this or merge
borders in general.

**Comment by tamis-laan** [comment]
Uhm not sure if we are talking about the same thing, just in case I made a screenshot to illustrate what I'm talking about:
https://postimg.cc/bZb8fMDC
You can see that the master window is in focus and has a very bright border. While at the same time the adjacent terminal has the same color but less bright. Non adjacent terminals have a black border color.

I'd like to disable this feature were adjacent terminals have a less bright color similar to the focused window, is this possible?

**Comment by geekosaur** [comment]
That shouldn't happen, unless the window itself is trying to handle
(possibly fake) transparency and remembering the old border color. You
might check the documentation for your terminal emulator.

-- 
brandon s allbery kf8nh
allbery.b@gmail.com

**Comment by tamis-laan** [comment]
This not terminal related it happens on a all windows. Also I don't use transparency, never liked it. 

When I shift focus from one window to another window the surrounding windows that have never been in focus before also get this very light focus colour. 

Clearly it's an indication that you can jump from the currently focused window to those surrounding windows. 

I'm not sure where this feature comes from and how to turn it off.

**Comment by ivanbrennan** [comment]
@tamis-laan Are you using anything from XMonad.Layout.WindowNavigation in your config? I'm experiencing similar behavior since adding `windowNavigation` to my layoutHook.

**Comment by ivanbrennan** [comment]
In my case, the neighboring window borders were inheriting a softer version of the focused window's border color due to the default behavior in XMonad.Layout.WindowNavigation.

https://github.com/xmonad/xmonad-contrib/blob/51bc4f8c2f39c331c59a09b090b313ce2ac8c771/XMonad/Layout/WindowNavigation.hs#L76
https://github.com/xmonad/xmonad-contrib/blob/51bc4f8c2f39c331c59a09b090b313ce2ac8c771/XMonad/Layout/WindowNavigation.hs#L94

It's configurable, and I was able to get things back to normal by replacing (in my layoutHook),
```haskell
windowNavigation
```
with
```haskell
configurableNavigation noNavigateBorders
```

**Comment by slotThe** [comment]
@tamis-laan does this fix your issue?

**Comment by slotThe** [comment]
@tamis-laan I will close this for now; feel free to chime in in case things are still unclear
