### ISSUE TITLE
Add updating XMonad.Docs.Extending to CONTRIBUTING and maybe PR Checklist

### ISSUE THREAD

**Issue by elkowar** [xmonad/xmonad-contrib#352]
### Problem Description

Currently, when adding a new module to xmonad-contrib, there is no obvious reminder to document that module in Extending.hs.
Should there be a note in CONTRIBUTING, and also maybe a additional checkbox in the PR template, noting that you should update Extending.hs when appropriate?

I, for example, did not remember to add my recent `XMonad.Util.TiledWindowDragging` module (#344) to that document. As a result of that PR still having been merged this module will now either stay undocumented, or someone will have to now add the entry after the fact.

**Comment by psibi** [comment]
Sounds good to me. 

Probably adding a checklist here would be better: https://github.com/xmonad/xmonad-contrib/blob/master/.github/PULL_REQUEST_TEMPLATE.md (rather than updating the Contributing.MD)

Do you want to create an MR updating that ? Thanks!

**Comment by elkowar** [comment]
done! see #353
