### ISSUE TITLE
Tabs do not physically show up when using the tabbed layout.

### ISSUE THREAD

**Issue by copper4eva** [xmonad/xmonad-contrib#358]
### Problem Description
https://www.reddit.com/r/xmonad/comments/hcapkf/my_tabbed_layout_doesnt_actually_show_any_tabs/
I made a reddit post about this issue. I only bring that up because my post there is a little more detailed. This issue only occurs on one of my two laptops, and I cannot figure out where the difference is. Basically my tabbed layout acts just like full. It does not show any tabs. Both the case for simpleTabbed and just normal tabbed. I installed xmonad on my other laptop to find that it works there just fine.

Both laptops are running Artix. Although the one I'm having the issue with is much more newly installed. I haven't even installed a bar on this machine of any kind, just for example.

### Configuration File
I had a more expanded upon config file that I've now backed up. The one I'm currently using is just the template with tabbed imported and thrown in the layout hook. I'm just showing the changed I made to the template config, rather than upload the whole config.

```haskell
import XMonad.Layout.Tabbed
```
```haskell
myLayout = tiled ||| tabbed shrinkText def
  where


     -- default tiling algorithm partitions the screen into two panes
     tiled   = Tall nmaster delta ratio

     -- The default number of windows in the master pane
     nmaster = 1

     -- Default proportion of screen occupied by master pane
     ratio   = 1/2

     -- Percent of screen to increment by when resizing panes
     delta   = 3/100
```

**Comment by geekosaur** [comment]
This is the layout throwing an exception, usually due to a missing font.
Find the package with the X11 "fixed" bitmap font, or configure a different
one. Many Linux distributions stopped providing "fixed" by default, which
is supposed to be required as a fallback font.

**Comment by copper4eva** [comment]
That fixed it thanks. I feel dumb, the first guy on reddit suggested a missing font, and I screwed up configuring the fonts I think. Still new to XMonad, and I'm just now getting into the habit of checking xmonad.errors after every recompile/restart.

**Comment by copper4eva** [comment]
Not strictly important. But do you know the package name on Arch that has this default font? I was not able to find it personally. 
While obviously manually configuring the font works fine, it'd be convenient to still have the default font.

**Comment by dadaurs** [comment]
For me, adding 
```
fontName = "xft:monospace:size=9"
``` 
fixed it.
