### ISSUE TITLE
Rounded corners in XMonad

### ISSUE THREAD

**Issue by michaljanocko** [xmonad/xmonad-contrib#361]
I would really love to have rounded corners on my computer.
However, solutions, which use compton, picom, or similar, suck. They just do. No border rounding or (not so important) shadow rounding.

[Example setup using compton](https://www.reddit.com/r/unixporn/comments/fs8trg/oc_comptonpicom_fork_with_both_tryone144s_dual/)

Some WMs already have patches for them to support corner rounding and anti-aliasing.

[bspwm example](https://www.reddit.com/r/unixporn/comments/cvk4xz/bspwmpolybar_my_arch_setup_with_bspwm_rounded/)

Is there a way to do this with XMonad.

**Comment by geekosaur** [comment]
This would require using an external frame window, which would break
extensions that assume there isn't one. The current border is an X11
intrinsic that always sticks to a rectangle.

**Comment by karetsu** [comment]
@geekosaur the X11 primitives Segment and Arc are available to us though, is there really no way to retain Rectangle but create an instance which uses things from X.U.XUtils like paintAndWrite to create some kind of pseudo-decorations within a defined Rectangle?

**Comment by geekosaur** [comment]
Not easily. We have the primitives, but drawing inside the app window will
conflict with the app itself and outside requires either extra bookkeeping
or a frame window which will mess up various extensions that don't expect
one.

**Comment by karetsu** [comment]
So a decoration counts as 'inside the app window'? I haven't looked at the inner workings of decorations too much but I would just want to draw inside a decoration as a means to an end (would ofc have to completely bound the inner window rectangle in that case)

**Comment by geekosaur** [comment]
The current borders are just the X11 border_width property of each window.
Decoration windows are outside the app window, but have shortcomings.

**Comment by karetsu** [comment]
I wonder if this would be better off as something like "make Rectangle drawing (rendering?) more flexible" - i.e. a little more abstract? 

The windows themselves are hopefully just specified as Rectangles (I admit I haven't delved into the depths of how it draws windows). I assume it gets really messy but if we would be able to create a mask on that rectangle using the other primitives how would that not work (assuming border width would be set to 0 on the outer rectangle.

I would like there to be a lot more flexibility in this but can completely understand a "its a tilingWM, if its not filling the space you're doing it wrong" but lots of us like our WMs to be functional and pretty at the same time! ^^
Even just being able to draw transparent windows and filling them with other things would be a plus.


So my questions are these:

* which part of the plumbing is this? Would we need to rewrite the xmonad interface to xlib or something within xmonad? 
* if I wanted to simply modify the decorations components to be more flexible, where would I look to try to do that? I can see in X.L.Decorations no reference to actually painting the windows so would this be a huge chunk in X.Core?

**Comment by geekosaur** [comment]
You would have to rewrite the part of the X server that draws window
internal borders. Xmonad just sets the internal border width and color and
leaves the rest to the server. Note also that the rest of window rendering
is between the app and the X11 server; window managers are about window
placement, not rendering. And a Rectangle is just a screen region, not
about rendering or drawing.

**Comment by slotThe** [comment]
I'm going to close this as out-of-scope; xmonad is really just a window manager, after all.
