### ISSUE TITLE
Xmonad TreeSelect defaultconfig.

### ISSUE THREAD

**Issue by apoorv569** [xmonad/xmonad-contrib#362]
```
tsDefaultConfig :: TS.TSConfig a
tsDefaultConfig = TS.TSConfig { TS.ts_hidechildren = True
                              , TS.ts_background   = 0xdd292d3e
                              , TS.ts_font         = myFont
                              , TS.ts_node         = (0xffd0d0d0, 0xff202331)
                              , TS.ts_nodealt      = (0xffd0d0d0, 0xff292d3e)
                              , TS.ts_highlight    = (0xffffffff, 0xff755999)
                              , TS.ts_extra        = 0xffd0d0d0
                              , TS.ts_node_width   = 200
                              , TS.ts_node_height  = 20
                              , TS.ts_originX      = 90
                              , TS.ts_originY      = 90
                              , TS.ts_indent       = 80
                              , TS.ts_navigate     = myTreeNavigation
                              }
```
In the above section , changing the values for TS.ts_originY and TS.ts_originX does nothing, indent works, node height and width also works. I want the Tree view to display center screen or maybe bottom of the screen. Or maybe this is not what I'm thinking it is, and according to [this](https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Actions-TreeSelect.html#t:TSConfig) site, it changes tree X or Y position on the screen in pixels, I have tried different values from 9 to 99 to 999 😜, nothing works

**Comment by dwt1** [comment]
I have the same issue with ts_originY and ts_originX in the treeSelect module.  Changing the values does nothing.

**Comment by TomSmeets** [comment]
Hi @apoorv569  and @dwt1,

This module was originally created by me. I haven't been using XMonad for some time since then. I just recently discovered that you have this issue.

After a quick investigation, I concluded that those config values `ts_originX` and `ts_originY` are actually never used by this module. :facepalm: It should be fixed with https://github.com/xmonad/xmonad-contrib/pull/385 .
