### ISSUE TITLE
_NET_CURRENT_DESKTOP not set before switching

### ISSUE THREAD

**Issue by Procrat** [xmonad/xmonad-contrib#363]
### Problem Description

Before switching desktops, `_NET_CURRENT_DESKTOP` doesn't get set. You can check with `xprop -root`.

Perhaps it has been like this since that attribute got cached: 92fe5f34ffff408fa859f116273bd073dc0eb367 That would make sense to me, since the default value in the cache is 0 and we start at workspace 0, so `whenChanged` doesn't trigger the side-effect of setting `_NET_CURRENT_DESKTOP`.

### Configuration File

```haskell
module Main (main) where

import           XMonad
import           XMonad.Config.Desktop (desktopConfig)

main :: IO ()
main = xmonad desktopConfig
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing). It works for fine there, but that repo is still using an outdated version xmonad and xmonad-contrib as far as I can tell.

**Comment by liskin** [comment]
Good catch, thanks! :+1:

**Comment by Procrat** [comment]
Awesome, thanks for fixing!
