### ISSUE TITLE
XMonad.Layout.Tabbed doesn't have WM_CLASS

### ISSUE THREAD

**Issue by Tanish2002** [xmonad/xmonad-contrib#369]
### Problem Description

I am using the tabbed layout with a fork of picom(compositor) which provides rounded corner, and I want to disable rounded corners for the tabs but when I use `xprop` to find the `WM_CLASS` string there is none

Output of `xprop`
https://i.fiery.me/nR4vo.png

### Configuration File

Here is how I use the layout

```haskell
import XMonad.Layout.Tabbed

myLayout = fullscreenFull $ avoidStruts $ (dwindle ||| tabs ||| tall ||| Mirror tall ||| Full)
  where
    tabs =
      named "Tabbed"
      . spacingRaw False (Border 20 20 20 20) True (Border 0 20 0 20) False
      $ tabbedBottom shrinkText tabTheme
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment]
Fixed by https://github.com/xmonad/xmonad-contrib/pull/546
