### ISSUE TITLE
Broken prompt tab completion with numlock modifier

### ISSUE THREAD

**Issue by kurnevsky** [xmonad/xmonad-contrib#37]
After commit 727e21419569ecf39f352f4ab86a8f8810bcd4ec we can specify only one modifier. But it would be good if tab completion will work with and without mod2Mask (=numlock mask).

**Comment by kurnevsky** [comment]
@psibi what do you think?

**Comment by kurnevsky** [comment]
(I suppose there is the same issue with scroll lock = mod3)

**Comment by f1u77y** [comment]
mask should be cleaned just like [in core](https://github.com/xmonad/xmonad/blob/master/src/XMonad/Main.hs#L287)

**Comment by psibi** [comment]
@kurnevsky  I think I'm not able to understand what is breaking. Can you clarify ? If you don't want a modifier, just pass `0` as attribute for the modifier. Something like this: `completionKey = (0, xK_Tab)` should make it work.

**Comment by f1u77y** [comment]
@psibi it won't work if numlock is active. But it mustn't pay attention on numlock, so it should be stripped from mask like I said before.

**Comment by kurnevsky** [comment]
@psibi when numlock is active ev_state=16 (=mod2Mask) even if you just type Tab without other keys.

**Comment by psibi** [comment]
@f1u77y @kurnevsky  Ah okay. Does anyone of you want to go ahead and give a patch ? If not, I can send it in one or two days.
