### ISSUE TITLE
debugStack is reversed

### ISSUE THREAD

**Issue by ivanbrennan** [xmonad/xmonad-contrib#379]
### Problem Description

The `debugStack` function provided by `XMonad.Hooks.DebugStack` lists the windows on the stack in reverse order. Is this a bug or the intended behavior?

The cause appears to be:
https://github.com/xmonad/xmonad-contrib/blob/58feba91d96fee8339d7cf56fb33537be819eb4b/XMonad/Hooks/DebugStack.hs#L110
where elements are cons'd onto accumulated results (`a`) in a left fold.

### Configuration File

```haskell
import XMonad
import XMonad.Hooks.DebugStack (debugStack)
import qualified Data.Map as M

main :: IO ()
main = xmonad def
  { keys = const . M.fromList $
      [ ((mod4Mask, xK_o), spawn (terminal def)),
        ((mod4Mask, xK_equal), debugStack)
      ]
  }
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing) (see [commit](https://github.com/ivanbrennan/xmonad-testing/commit/f51ab2f9110d15dd128db3967f9d2ae823171a66))

**Comment by geekosaur** [comment]
It's basically whether you want the focused window at the top or the
bottom; I found it somewhat more convenient at the bottom where it was
closer to the behavior I wanted to debug via ManageDebug, which I split it
from while I was developing the debug hooks.

**Comment by ivanbrennan** [comment]
@geekosaur Thanks for clearing that up. Borrowing an idea from this [comment](https://github.com/xmonad/xmonad-contrib/issues/211#issuecomment-473581066), I've added this to my local config, so I can get the stack in order I wanted:
```haskell
debugStackString
  >>= trace . unlines . uncurry (++) . second reverse . splitAt 1 . lines
```
This works around the issue for my needs. Since the order was intended, I'll close out this issue.
