### ISSUE TITLE
How to run automated tests?

### ISSUE THREAD

**Issue by ivanbrennan** [xmonad/xmonad-contrib#381]
### Problem Description

It's unclear how contributors can run any of the automated tests. This decreases their value and discourages adding new ones.

I recently wanted to add some QuickCheck property tests for a module I was adding. I eventually managed to run my tests as documented in these changes: https://github.com/ivanbrennan/xmonad-contrib/compare/master...ivanbrennan:sift-test

The approach I used is probably not very re-usable or robust, but it demonstrates that it is _possible_ to run the tests, and shows some of the challenges involved in doing so.

I'm curious whether there's an established pattern for how tests can/should be run, and I'd be happy to document it if so. It would be nice if xmonad-contrib.cabal had a test-suite target, though I suspect that would require changes in xmonad to expose the instances/utils in its [tests](https://github.com/xmonad/xmonad/tree/master/tests) directory.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by TheMC47** [comment]
Better late than never: now you can run `stack test` to run the test-suite

**Comment by ivanbrennan** [comment]
@TheMC47 That's great to hear, thanks!
Should this be mentioned in the readme?

**Comment by TheMC47** [comment]
@ivanbrennan  I feel that it should be mentioned somewhere, but I'm not sure where that somewhere is... I think the best place would be https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md

**Comment by ivanbrennan** [comment]
> @ivanbrennan I feel that it should be mentioned somewhere, but I'm not sure where that somewhere is... I think the best place would be https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md

That seems reasonable.

**Comment by TheMC47** [comment]
@ivanbrennan  so it's now mentioned in the CONTRIBUTING.md, I guess we could close the issue

**Comment by ivanbrennan** [comment]
@TheMC47 Thanks for setting up the test suite!
