### ISSUE TITLE
Layout modifiers application order

### ISSUE THREAD

**Issue by f1u77y** [xmonad/xmonad-contrib#40]
Many layout modifiers work as expected with each other only when applicated in certain order. Searching for that order can be difficult for many users, especially when they use many layout modifiers. I think there should be some documentation(or maybe other way) to prevent users from wrong application order.

**Comment by aavogt** [comment]
https://github.com/xmonad/xmonad-extras/tree/master/XMonad/Config/Alt does that, but somebody would have to write functions like those in XMonad/Config/Alt/Desktop.hs to apply modifiers at the right precedence number.
