### ISSUE TITLE
X.L.IndependentScreens' `marshallSort` always sorts lexically

### ISSUE THREAD

**Issue by geekosaur** [xmonad/xmonad-contrib#420]
fizzie 16:16:42
I'm thinking the problem with IndependentScreens' marshallSort may be exactly that it handles marshalling and unmarshalling the physical workspace names, so that the sort function just sees the plain "1", "2", ..., but then the default sort function will fail to find indices for any of those because the config's workspace list will be "0_1", "0_2", ... and so on.

fizzie 16:17:53
In which case it would in fact fall back to lexicographically sorting the names, because of mconcat [indexCompare `on` wsIndex, compare], and indexCompare Nothing Nothing = EQ.

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by dmwit** [comment]
I guess I don't know the context of this, but my gut reaction is that this is why `workspaces'` exists: to get a list of the virtual workspaces available. So whatever sort function you're passing to `marshallSort` should use `workspaces'` instead of `workspaces`, and then this should Just Work?

**Comment by liskin** [comment]
> I guess I don't know the context of this, but my gut reaction is that this is why `workspaces'` exists: to get a list of the virtual workspaces available. So whatever sort function you're passing to `marshallSort` should use `workspaces'` instead of `workspaces`, and then this should Just Work?

This would require substantial changes in `XMonad.Util.WorkspaceCompare` to allow overriding the `workspaces` it uses. Wouldn't it be better if `marshallPP` just worked with the default `ppSort`: `getSortByIndex`, which uses the real (not virtual) workspace names, and then have an optional pair of primed functions that work with virtual names for anyone who needs those?

The approach taken in #501 is probably also fine: keep the existing behaviour in `marshallPP` and `marshallSort` and add a primed pair of functions that work with real workspace names and clearly document that with the default `ppSort`, these should be used.

**Comment by oogeek** [comment]
My way in the pull request is to keep the physical workspaces and let `getSortByIndex` or whatever sort it.
However, it is also find if we first sort it with `getSortByXXX`, then unmarshall it. I don't think it will make a big difference.

**Comment by oogeek** [comment]
Any suggestions?
