### ISSUE TITLE
Restart xmobar/dzen without relying on pipes

### ISSUE THREAD

**Issue by TheMC47** [xmonad/xmonad-contrib#433]
### Problem Description

As mentioned in #408 , property-based logging should be encouraged. However, there still isn't a way to restart processes without relying on pipes or PIDs.
This was suggested by @liskin in the IRC:
> <Liskni_si> anyway xmobar sets _NET_WM_PID on its window
> <Liskni_si> so we can just queryTree root windows, look for xmobars, read _NET_WM_PID, check if it matches persistent state, kill
> <Liskni_si> dzen does that as well

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by TheMC47** [comment]
PS: I'm trying to familiarize myself with the code-base, and this seemed like a manageable task. Tips are highly appreciated :smile:

**Comment by liskin** [comment]
Tips: there's saving and killing of xmobars in my dotfiles, as well as some queryTrees looking for xmobars to lowerWindow them below trayer. Feel free to steal all of that and just add the pid check.

**Comment by TheMC47** [comment]
Closed by #434
