### ISSUE TITLE
KeyRemap without flickers

### ISSUE THREAD

**Issue by Curiosidad-Racional** [xmonad/xmonad-contrib#436]
### Feature Description

With KeyRemap module pressing key in KeymapTable window flickers losing focus: Terminal's cursor blinks, emacs with unfocus transparency '(alpha . (90 . 50)) blinks.

The same in others window managers, example [i3 Avoid keybindings from taking input focus](https://github.com/i3/i3/issues/1490). However EXWM works properly using the function `exwm-input--fake-key` sending event to `XCB`. I know `xmonad` use `Xlib`.

Would it be possible?

XMonad is amazing. Thank you.

### Configuration File

```haskell
...
import XMonad.Actions.KeyRemap
...
emacsKeyRemap :: KeymapTable
emacsKeyRemap = KeymapTable [ ((controlMask, xK_b), (0, xK_Left))
                            , ((controlMask, xK_f), (0, xK_Right))
                            , ((controlMask, xK_p), (0, xK_Up))
                            , ((controlMask, xK_n), (0, xK_Down))
                            ]
...
myKeys conf@(XConfig {XMonad.modMask = modm}) = M.fromList $
    [ ((modm .|. shiftMask, xK_Return), spawn $ XMonad.terminal conf)
...
    ]
    ++ buildKeyRemapBindings [emacsKeyRemap,emptyKeyRemap]
...
myStartupHook = do
  setDefaultKeyRemap emacsKeyRemap [emacsKeyRemap, emptyKeyRemap]
...
```

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
The flickers come from how xmonad and i3 handle input, via passive key grabs. There is no alternative input mechanism in xmonad.

**Comment by slotThe** [comment]
I'm going to close this for now; I deem it highly unlikely that xmonad will ever change its core _that_ much
