### ISSUE TITLE
multiple windows are highlighted as active when using X.L.Minimize

### ISSUE THREAD

**Issue by f1u77y** [xmonad/xmonad-contrib#46]
Steps to reproduce:
- Add `minimize` and `boringWindows` to layout
- Open 2 or more windows on workspace
- Minimize one of them
- Restore it with `sendMessage RestoreNextMinimizedWin`
  Two windows(one is that what active before last step and other is restored window) will be highlighted as active

**Comment by pjones** [comment]
It seems this will be fixed with #102 so I'm going to close it.
