### ISSUE TITLE
Resize the gifs in XMonad.Util.Hacks

### ISSUE THREAD

**Issue by TheMC47** [xmonad/xmonad-contrib#488]
### Problem Description

The gifs included in `windowedFullscreenFix` are too big, which makes them unsuitable for Hackage. We need to resize those!

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by oogeek** [comment]
Do you mean geometry size or file size? I don't know how to deal with GIF file size other than making a new one. Also, for which size is suitable for Hackage?

**Comment by slotThe** [comment]
On Mon, Apr 12 2021 01:29, oogeek wrote:
> Do you mean geometry size or file size? I don't know how to deal with
> GIF file size other than making a new one. Also, for which size is
> suitable for Hackage? I can not find a standard from googling.

Geometry.  Hackage sadly does not have a way (at least that we know of)
to resize embedded images and since these are very big it completely
messes up the page layout.

**Comment by oogeek** [comment]
One gif is now 1002x425, another remains 888x712. Is that ok, or should I shrink it a bit further? Also, after resizing the gif, how can I open a PR for this file?

**Comment by slotThe** [comment]
> One Gif is now 1002x425, another remains 888x712. Is that OK, or should I shrink it a bit further? 

You can build the documentation with e.g. `stack haddock --no-haddock-deps`; if it looks good to you then feel free to submit it.

> Also, after resizing the Gif, how can I open a PR for this file? Where should the Gifs be stored? @TheMC47

I think having the .gif's hosted by github is fine, much like the current ones are.  So just open a pr that changes the URLs there

**Comment by oogeek** [comment]
> I think having the .gif's hosted by github is fine, much like the current ones are. So just open a pr that changes the URLs there

![2021-04-20-15-11-05](https://user-images.githubusercontent.com/79924233/115353277-e9b05a00-a1ea-11eb-8bf8-b315dcf5acdc.png)

**Comment by oogeek** [comment]
I am a bit worried to put it in personal git repo. Since if someone delete the repo, then the link will be 404.

**Comment by TheMC47** [comment]
> One Gif is now 1002x425, another remains 888x712. Is that OK, or should I shrink it a bit further? Also, after resizing the Gif, how can I open a PR for this file? Where should the Gifs be stored? @TheMC47

I think we have a couple of options: GitHub, the GitHub wiki of xmonad, or on the website

**Comment by slotThe** [comment]
Closed via #522
