### ISSUE TITLE
Add an action that repeats the last action

### ISSUE THREAD

**Issue by TheMC47** [xmonad/xmonad-contrib#489]
### Feature Description

In vim/emacs there's a keybinding that repeats the last command. We could add a module that wraps every bound action in a function that saves it in the extensible state. It should be straightforward to implement, I think it's suitable for new contributors. Feel free to ask for help :tada: 

### Example
Here's a rough sketch of how this should work. (`rememberActions` should work with both `EZConfig` and normal keybindings)
```haskell

myKeys = rememberActions [("M-q", kill), ....]
    ++ [("M-.", repeatLast)]

```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  ~- [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~

**Comment by yusi1** [comment]
This would be a really cool feature!
