### ISSUE TITLE
XMonad.Layout.SubLayouts mergeDir behaviour

### ISSUE THREAD

**Issue by timakro** [xmonad/xmonad-contrib#494]
### Problem Description

I'm not sure if this is a bug or I just don't understand how this works. In the [XMonad.Layout.SubLayouts docs for `mergeDir`](https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Layout-SubLayouts.html#v:mergeDir) there's an example usage: `withFocused (sendMessage . mergeDir W.focusDown')`. As I understand it this is supposed to merge the current window into a group with the window that would otherwise be selected if you pressed `j`. But that's not consistently working for me. For example with the standard tall layout I have firefox as the master and then 5 terminals numbered 1 to 5 from top to bottom in the right column. Now I focus terminal number 3 and run the command. I'd expect this to merge terminals number 3 and 4 but instead it merges 3 and 5.
### Steps to Reproduce

See above.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
import XMonad
import XMonad.Util.EZConfig
import qualified XMonad.StackSet as W
import XMonad.Layout.Tabbed
import XMonad.Layout.Simplest
import XMonad.Layout.SubLayouts

main = xmonad $ def
    { layoutHook = myLayoutHook
    } `additionalKeysP` myKeys

myKeys =
    [ ("M-C-j", withFocused (sendMessage . mergeDir W.focusDown'))
    , ("M-C-k", withFocused (sendMessage . mergeDir W.focusUp'))
    ]

myLayoutHook = addTabs shrinkText tabTheme $ subLayout [] Simplest $ Tall 1 (3/100) (1/2)
 where tabTheme = def { fontName = "xft:fixed" }
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment]
Well, the doc says: “merge the window that would be focused by the function when applied to the W.Stack of all windows, **with the current group removed**”, which probably explains what you're seeing. I have `mergeDir id` in my config, which doesn't do exactly what `j` does, but it always merges with the next window which is pretty close and it's okay for my usecases.

(I agree that SubLayouts is tricky to understand and use efficiently. I have some open PRs related to it and some additional WIP commits in my personal fork, but nothing really significant, just scratching my own itches.)

**Comment by timakro** [comment]
Okay, makes sense. So I changed the key bindings to this now:

```haskell
myKeys =
    [ ("M-C-j", withFocused (sendMessage . mergeDir id))
    , ("M-C-k", withFocused (sendMessage . mergeDir W.focusUp'))
    ]
```

The original scenario works like I want it now. Now with same setup as before, I focus terminal number 5 and run the new `M-C-j` command. Any theories on why this merges terminal number 5 and 4 instead of 5 and master? Also if I focus 5 and run the `M-C-k` command it merges 5 and 3 instead of 5 and 4.

Both bindings work like expected for all other windows than terminal number 5. Maybe there is something strange going on because it's the last window in the stack?

**Comment by timakro** [comment]
Actually upon second though both behaviors make sense by the logic described in the docs. I guess we can still keep this open as a feature request?

**Comment by liskin** [comment]
That's because mergeDir uses XMonad.StackSet.filter which has this weird behaviour of moving focus up or down when the focused window gets filtered out, which it always does in this case as the currect group is being filtered out.

https://github.com/xmonad/xmonad-contrib/blob/78d526d/XMonad/Layout/SubLayouts.hs#L266
https://github.com/xmonad/xmonad/blob/f5bd77a/src/XMonad/StackSet.hs#L314
https://github.com/xmonad/xmonad/blob/f5bd77a/src/XMonad/StackSet.hs#L463-L479

**Comment by liskin** [comment]
Oh I see you figured this out by yourself in the meantime. :+1: 

If we want to keep this open as a feature request, we'd better specify what the desired behaviour is. ;-)
(I agree that the current situation isn't ideal, but it isn't entirely clear what the ideal situation looks like.)

**Comment by timakro** [comment]
So I came up with this now:

```haskell
myMergeDir :: (W.Stack Window -> W.Stack Window) -> Window -> GroupMsg Window
myMergeDir f w = WithGroup g w
 where g cs = do
        let onlyOthers (W.Stack f ls rs) = Just $ W.Stack f (L.filter (`notElem` W.integrate cs) ls)
                                                            (L.filter (`notElem` W.integrate cs) rs)
        flip whenJust (sendMessage . Merge (W.focus cs) . W.focus . f)
            =<< fmap (onlyOthers =<<) currentStack
        return cs

mergeDown = myMergeDir W.focusDown'
mergeUp   = myMergeDir W.focusUp'
```

This is close to what I want but it's still not perfect: Most of the time this pulls the next/previous group in like it should, but in some special cases it pushes the current group into the next/previous group. This is all I can do with my limited haskell knowledge. Maybe this helps someone out.
