### ISSUE TITLE
tag window doesn't disappear when X.L.showWName and X.A.CycleRecentWS are used together

### ISSUE THREAD

**Issue by oogeek** [xmonad/xmonad-contrib#504]
### Problem Description
When using `X.A.CycleRecentWS` and `X.L.showWName`, the window created to show workspace name does not fade away (disappear). New window showing workspace tags are drawn above each other. 

It behaves the same with and without compositor. 
After some time, the area grew dark and new tags are still drawn above it. 
Before it grew dark, the tag window is shown on top of the focused window, covered an area of the window. 
After it grew dark, the tag window didn't block the view of window anymore. But one can still see it when all windows are closed in a workspace.
The dark area is shown over all the workspaces.

I have encountered this issue before I got interested in IndependentScreens. With 9 workspaces and single screen, this issue persists.

The only way I find to solve it tentatively is to exit xmonad and start again.

### Steps to Reproduce
1. Add `myl = showWName myLayoutHook` and then set `layoutHook =myl`
2. Using `cycleRecentWs`

### Configuration File
```
myKeys :: [(String, X ())]
myKeys = [("M1-<Tab>", cycleRecentWS [xK_Alt_L] xK_Tab xK_grave)]

myl = showWName myLayoutHook

main :: IO ()
main = do
    xmonad $ ewmh myConfig'
        { logHook =workspaceHistoryHook, layoutHook = myl }
```

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment]
On Tue, Apr 06 2021 00:42, oogeek wrote:
> ### Problem Description
> When using `X.A.CycleWs` and `X.L.showWName`, the window created to
> show workspace name does not fade away (disappear). New window showing
> workspace tags are drawn above each other. 

The first module doesn't have `cycleRecentWS`, I'm assuming you mean
X.A.CycleRecentWS. 

> It behaves the same with and without compositor. 
> After some time, the area grow dark and new tags are still drawn above
> it.

The problem seems to be that CycleRecentWS doesn't switch tell the
StackSet to view a particular workspace, but simply creates a new one
where another workspace happens to be focused instead.  

A quick diff that fixes the problem is available at [1].  The only
signature change that we care about in terms of backwards compatibility
(anything else was added after 0.16) is that of `cycleWindowSets`, which
is kind of unavoidable in this situation I feel like.

[1]: http://ix.io/2VcI

**Comment by oogeek** [comment]
I am not sure if I get it correct, but you say that for compatibility, we can not change the type signature of `cycleWindowSets`, and therefore we can not fix it. Or it is easy to fix and we can just change the file according to the diff.

**Comment by slotThe** [comment]
On Sun, Apr 11 2021 01:35, oogeek wrote:
> I am not sure if I get it correct, but you say that for compatibility,
> we can not change the type signature of `cycleWindowSets`, and
> therefore we can not fix it. Or it is easy to fix and we can just
> change the file according to the diff.

Well, we _can_ fix it, just that it would necessarily be a breaking
change.  Whether that's worth it or not would be a matter of debate, so
I'm eager to hear more opinions on the matter

**Comment by oogeek** [comment]
I see. Thanks for explanation.

**Comment by slotThe** [comment]
@liskin @TheMC47 what do you think?  The change in question would be from

``` haskell
cycleWindowSets :: (WindowSet -> [WindowSet]) -> [KeySym] -> KeySym        
```

to 
 
``` haskell
cycleWindowSets :: (WindowSet -> [WorkspaceId]) -> [KeySym] -> KeySym         
```

While it is one of the two only functions exported by the module, I feel like its use-case is rather obscure and so it's probably fine to change it.

**Comment by TheMC47** [comment]
I'll try to look at this soon-ish and tell you what I think

**Comment by liskin** [comment]
I don't think the use is all that obscure. It's there to allow the user to specify a different notion of "recent" than what `cycleRecentWS`/`cycleRecentNonEmptyWS` provide. Any config that uses the `recentWS` helper will just continue to work unchanged. Yes, `cycleWindowSets` could also be used to switch to a new workspace that wasn't present in the windowset, and that use-case is indeed very obscure, error-prone and not at all worth supporting in `XMonad.Actions.CycleRecentWS`.

The change of `cycleWindowSets` type signature isn't a bad thing. It's a core part of the fix itself. Cycling using `WindowSet -> [WindowSet]` can't be implemented safely as long as any state is kept inside the `Workspace`, and xmonad does keep state in there, and so do many layouts in -contrib. There's no need to worry about changing the type. Just write a changelog entry and submit a PR, please. :-)

(`toggleWindowSets` is safe even with `WindowSet -> [WindowSet]`, but I expect most users to use the `recentWS` helper, so trying to keep the old type signature here would do more harm than good.)
