### ISSUE TITLE
custom colorizer black

### ISSUE THREAD

**Issue by ixzh** [xmonad/xmonad-contrib#516]
### Problem Description

My custom colorizer has a black bg for inactive cells though red/blue colors for inactive bg were specified.

### Steps to Reproduce
a black grid-select when called out

### Configuration File

I have defined:

```haskell
gsconfig2 colorizer = (buildDefaultGSConfig colorizer) { gs_font="xft:source han     sans cn:size=10",gs_cellwidth=200 }
 
 myColorizer = colorRangeFromClassName
                      (0xE6,0x3E,0x3E) -- lowest inactive bg
                      (0x19,0x15,0x6E) -- highest inactive bg
                      (0xFF,0xFF,0x00) -- active bg
                      white            -- inactive fg
                      black            -- active fg
   where black = minBound
         white = maxBound
```
and call it with:
```haskell
   -- Show grid selector
   , ((modMask, xK_g), goToSelected $ gsconfig2 myColorizer)
```
The lowest/highest are not recognized, but the active bg (yellow) is rendered correctly.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by oogeek** [comment]
What's the version of your xmonad-contrib? I have tested it with 
```
xmonad-contrib (git) 
xmonad (git)
```
and
```
xmonad-contrib (0.16) 
xmonad (0.15)
```
and can not reproduce the problem.

**Comment by ixzh** [comment]
> What's the version of your xmonad-contrib?

I have:
![image](https://user-images.githubusercontent.com/14981695/114689000-d95e3200-9d47-11eb-91ae-d5bf3e52cded.png)
using yay -S

**Comment by ixzh** [comment]
I haven't figured out a way to screenshot when grid is called out...

**Comment by oogeek** [comment]
> I haven't figured out a way to screenshot when grid is called out...

My suggestion is that you can try using xmonad-contrib git version and see if the problem goes away. For me, I use stack-static from AUR and git clone the repo in ~/.xmonad.

**Comment by ixzh** [comment]
> try using xmonad-contrib git version

Thanks I switch to the git version and the color is back!

**Comment by ixzh** [comment]
![test](https://user-images.githubusercontent.com/14981695/114991918-b9a44680-9ecc-11eb-80d3-229ba3bec077.png)
