### ISSUE TITLE
X.L.WindowSwitcherDecoration and X.L.DraggingVisualizer stops working

### ISSUE THREAD

**Issue by oogeek** [xmonad/xmonad-contrib#517]
### Problem Description
`X.L.WindowSwitcherDecoration` and `X.L.DraggingVisualizer stops working` work well with
```
xmonad 0.15
xmonad-contrib 0.16
```
But not working for
```
xmonad git
xmonad-contrib git
```
or 
```
xmonad 0.15
xmonad-contrib git
```
### Configuration File
```
myvisualL = windowSwitcherDecoration shrinkText def (draggingVisualizer myLayoutHook)

myLayoutHook = avoidStruts $ mouseResize $ windowArrange $ T.toggleLayouts floats
               $ mkToggle (NBFULL ?? NOBORDERS ?? EOT) myDefaultLayout
             where
               myDefaultLayout =     tall
                                 ||| floats
                                 ||| noBorders tabs
                                 ||| grid
                                 ||| spirals
                                 ||| Accordion
```
### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by oogeek** [comment]
I have tried to `git diff` for a while but can not find the issue.

**Comment by liskin** [comment]
Can you please elaborate on what `stops working work well` means?

**Comment by oogeek** [comment]
> Can you please elaborate on what "stops working work well" means?
> 
> (Also, I believe `git bisect` might be a better tool for this than `git diff`. ;-))

Behavior it used to be:

    left click the window bar (top) and the hold it while moving the whole window to overlap another one

    these two windows change position

Now it simply does not work.

**Comment by liskin** [comment]
Yes, I can reproduce this. As this seems to be a regression since last version, we definitely want to fix this in the next release, so I added it to the milestone/project.

If you have some free time, a git bisect of xmonad-contrib between the v0.16 and master would definitely help us. I (or anyone who beats me to it) will get to this sooner or later, but there's loads of other higher priority stuff, some of which is even in progress.

**Comment by oogeek** [comment]
> If you have some free time, a git bisect of xmonad-contrib between the v0.16 and master would definitely help us. I (or anyone who beats me to it) will get to this sooner or later, but there's loads of other higher priority stuff, some of which is even in progress, so I'd rather not put more on my plate right now.

I am currently working on it. Still git bisecting

**Comment by oogeek** [comment]
ec146171238b10eacc220bef3d6d2123ff27d3ad is the first bad commit
commit ec146171238b10eacc220bef3d6d2123ff27d3ad
Author: Tomas Janousek <tomi@nomi.cz>
Date:   Tue Mar 23 01:39:34 2021 +0000

    X.H.ManageDocks: React to strut updates of override_redirect docks

    We only requested PropertyChange events from docks in the `manageDocks`
    manageHook, but that only gets called for normal windows, not
    override_redirect ones. Therefore, xmobar in its default configuration
    wouldn't get its struts refreshed on changes. This resulted in gaps not
    updating after xmobar repositions itself on xrandr changes.

    If one wanted to handle that repositioning in xmonad, it was possible to
    configure xmobar with `overrideRedirect = False`, which is meant for
    window managers with proper EWMH stacking order support [1], so in
    xmonad it resulted in xmobar covering fullscreen windows. That can be
    worked around by adding `checkDock --> doLower` to manageHook, but it
    starts to smell of too many workarounds.

    [1]: https://specifications.freedesktop.org/wm-spec/wm-spec-1.5.html#STACKINGORDER

    The fix is to request PropertyChange events for all windows that we
    treat as docks.

    Related: https://github.com/xmonad/xmonad-contrib/pull/490

 CHANGES.md                  | 11 ++++++++++-
 XMonad/Hooks/ManageDocks.hs | 15 ++++++++++-----
 2 files changed, 20 insertions(+), 6 deletions(-)

**Comment by oogeek** [comment]
I use 
```
xmonad 0.15
xmonad-contrib git
```
Cause when bisecting, using xmonad (git) is just painful. Really painful.

**Comment by liskin** [comment]
Oh, thanks a lot! Seems that even though i tried to be careful with that `selectInput` to not override an already set mask, I failed anyway. Now that the cause is clear, a fix should hopefully be quick and easy. Stay tuned for a PR. :-)

**Comment by oogeek** [comment]
> Oh, thanks a lot! Seems that even though i tried to be careful with that `selectInput` to not override an already set mask, I failed anyway. Now that the cause is clear, a fix should hopefully be quick and easy. Stay tuned for a PR. :-)

Thanks. I am waiting for it.

**Comment by oogeek** [comment]
> Oh, thanks a lot! Seems that even though i tried to be careful with that `selectInput` to not override an already set mask, I failed anyway. Now that the cause is clear, a fix should hopefully be quick and easy. Stay tuned for a PR. :-)

Thanks. I am waiting for it.

**Comment by oogeek** [comment]
So any updates now? @liskin
