### ISSUE TITLE
XMonad freezes when using statusBarHandleConfig from X.H.DynamicLog

### ISSUE THREAD

**Issue by oogeek** [xmonad/xmonad-contrib#519]
### Problem Description

After probably 6 seconds, xmonad freezes.
Can not:
1. swith to other workspaces,
2. can not even switch focus of window in the current workspace
3. all keybindings are not working, except for `2` sometimes.

```
xmonad git
xmobar git
xmonad-contrib git
```
Right now I am at the commit 88b9c806184421400c361af76505a3bc50517001, as mentioned in https://github.com/xmonad/xmonad-contrib/issues/517
I have to switch back to my previous solution with several `spawnPipe`s.
### Steps to Reproduce

Use the config below.
I do read the newly added tutorial by @slotThe and others and have checked carefully to turn `UnsafeStdinReader` to `UnsafeXMonadLog` with my `xmobarrc0` and `xmobarrc1`. I have double checked that.

Now I have to `pkill xmobar` in another `tty` and then xmonad works again, but without the `xmobar`s

### Configuration File
```
main = do
    xmobar1    <- statusBarHandleConfig "xmobar -x 0 $HOME/.config/xmobar/xmobarrc0" myXmobarConfig
    xmobar2    <- statusBarHandleConfig "xmobar -x 1 $HOME/.config/xmobar/xmobarrc1" myXmobarConfig
    xmonad =<<
xmonad . withUrgencyHook dzenUrgencyHook { args = ["-bg", "darkgreen", "-p", "1"] } 
              . ewmhFullscreen
              . ewmh =<<  makeStatusBar (xmobar1 <> xmobar2) myConfig
```

I use the above config from the source code of `X.H.DynamicLog`
As a user of `X.L.IndependentScreens`, I use two monitors, two xmobar process.

Have also tried:
```           
n <- countScreens
hs :: [statusBarConfig]
hs =   traverse (\(S n) -> statusBarHandleConfig ("xmobar -x " ++ show n ++ " ~/.config/xmobar/xmobarrc" ++ show n) myXmobarConfig) [0..n-1]
xmonad . withUrgencyHook dzenUrgencyHook { args = ["-bg", "darkgreen", "-p", "1"] } 
              . ewmhFullscreen
              . ewmh =<< makeStatusBar (mconcat hs) myConfig'
 ```
### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment]
On Thu, Apr 15 2021 23:21, oogeek wrote:
> statusBarHandleConfig

Where are you getting this function from?  I grepped our entire code
base, but could not find any reference to it.  Have you checked out the
current $HEAD?

**Comment by oogeek** [comment]
> On Thu, Apr 15 2021 23:21, oogeek wrote: statusBarHandleConfig
> Where are you getting this function from? I grepped our entire code base, but could not find any reference to it. Have you checked out the current $HEAD?

Let me do a quick check. Maybe I have made a mistake
