### ISSUE TITLE
General question about warnings during stack build

### ISSUE THREAD

**Issue by oogeek** [xmonad/xmonad-contrib#524]
### Problem Description
Every time I compile xmonad-contrib from source code with `stack build`, there are warnings such as:
1. `case of` not complete
2. something `shadows` something else
3. some usage are `deprecated`, use something else instead
4. something `defined but not used`

I am wondering if some of them exist for backward compatibility or something else. 
Or can some of them be fixed. I know that xmonad-contrib still functions as usual, just curious.:grinning:

### Steps to Reproduce
git clone and compile with stack
### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by TheMC47** [comment]
Not sure if you closed this by mistake, but I guess we should leave it open so we don't forget about it

**Comment by oogeek** [comment]
Oh thanks.

**Comment by liskin** [comment]
The only warnings that are intentionally keps for backward compat are the "unused import" ones, and these should be handled by https://github.com/xmonad/xmonad-contrib/commit/53903b086f356b96d68b3c560b96e47ac7ec4508. The other warnings are just tech debt that we'd like to tackle eventually.

There was a discussion about this on IRC some time ago. My opinion was that creating PRs with all the warning fixes would create a lot of noise and waste peoples time, and the best course of action is for someone who known what they're doing to just go and fix them and push the fixes.

**Comment by TheMC47** [comment]
> There was a discussion about this on IRC some time ago. My opinion was that creating PRs with all the warning fixes would create a lot of noise and waste peoples time, and the best course of action is for someone who knows what they're doing to just go and fix them and push the fixes.

👍. It would be good to see the different lints, decide on which we want to fix, create a .hlint file and push the changes.

**Comment by oogeek** [comment]
> +1. It would be good to see the different lints, decide on which we want to fix, create a .hlint file and push the changes.

I have put the output of stack build here: https://fars.ee/OhaP

**Comment by slotThe** [comment]
This is done so I'm closing.  For details see #537
