### ISSUE TITLE
XMonad.Prompt xprop

### ISSUE THREAD

**Issue by ceigh** [xmonad/xmonad-contrib#526]
### Problem Description

I recently started using xmonad prompt, and I also use picom as a composite manager.
So, using picom, I set shadows for windows, but on xmonad prompt, I would like to remove the shadow, usually this is done by adding the window class to the list in picom.

But when I try to get information about the prompt window (as usual with xprop), xprop returns an empty result.
If someone has encountered a similar problem, please tell me how to define prompt in picom. Thanks.

### Configuration File

[xmonad](https://github.com/ceigh/dotfiles/blob/f137cf4ccd55a4469af03710f40811a21bef83d1/.xmonad/xmonad.hs#L80)
[picom](https://github.com/ceigh/dotfiles/blob/master/.config/picom/picom.conf)

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
I don't think the prompt window currently gets any identifying information; ideally it should at least have a valid `WM_CLASS` assigned (`XMonad`,`xmonad-prompt` or similar) so things like this will work.

**Comment by geekosaur** [comment]
Since it's unusual for windows to not have `WM_CLASS`, you may be able to match the window with `!WM_CLASS:8s`. This might also match other windows, but it seems unlikely. (Normally the pattern would have an `@`, but xmonad is non-reparenting so there should be no distinction.)

**Comment by ceigh** [comment]
Yes, thanks it works!
According to this guide, I used `"!WM_CLASS:s"`:

```conf
shadow-exclude = [
  "!WM_CLASS:s"
];
```

**Comment by geekosaur** [comment]
I'm going to leave this open because we should really have a proper `WM_CLASS` on the window.

**Comment by ceigh** [comment]
Yes, I think this is correct, thank you again.

**Comment by geekosaur** [comment]
I also think I reversed the resource and class names above, whoops.

**Comment by slotThe** [comment]
Seems like `xSetClassHint` is not implemented by X11, so that would
probably have to be done first.

**Comment by slotThe** [comment]
The necessary functionality is now implemented by xmonad/X11/pull/76; but that's not released quite yet.  

It would also require us to up the lower bound on X11 to that newly released version (1.10, I think?), but I don't think that's a problem, as xmonad/xmonad/pull/273 and xmonad/xmonad/pull/274 are also based on 1.10.

**Comment by liskin** [comment]
Fixed by https://github.com/xmonad/xmonad-contrib/pull/546
