### ISSUE TITLE
New Feature: Add killOthers to XMonad.Actions.WithAll (place not decided yet)

### ISSUE THREAD

**Issue by oogeek** [xmonad/xmonad-contrib#527]
### Note

This issue is intended for new contributors to xmonad :tada: . Feel free to ask for help when working on this by commenting below or saying Hi in the IRC channel smiley

The place to put the function is not decided yet.

Hints:
You can check the code for `KillAll` from `X.A.WithAll` and `Integrate'` from `XMonad.StackSet`

### Feature Description

When someone needs to close all other windows in a workspace and leave the focused one alone, multiple `kill1`s from `XMonad.Actions.CopyWindow` are just too much. It will be nice to have a `killOthers` function to do so.

### (Potential) Usage example
```
killOthers :: X ()
myKeys = [
...
 , ("M-S-a", killOthers)
...
```

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by ssbothwell** [comment]
how about this?

```
-- | Apply an 'X' operation to all unfocused windows, if there are any.
withUnfocused :: (Window -> X ()) -> X ()
withUnfocused f = withWindowSet $ \ws ->
    case peek ws of
        Just w ->
            let unfocusedWindows = XMonad.Prelude.filter (/= w) $ index ws
            in mapM_ f unfocusedWindows
        Nothing -> pure ()

-- | Kill all the unfocused windows on the current workspace.
killOthers :: X ()
killOthers = withUnfocused killWindow
```

It would make sense to me to put `withUnfocused` in `XMonad.Operations` and `killOthers` in `XMonad.Actions.WithAll`

**Comment by slotThe** [comment]
> It would make sense to me to put `withUnfocused` in `XMonad.Operations` and `killOthers` in `XMonad.Actions.WithAll`

X.Operations sounds good to me, but I'm not sure X.A.WithAll really fits the bill of not doing something to all windows.  That said, it's probably the closest module we have and it has to live inside _someting_ so...  Feel free to open the respective PRs :)

**Comment by ssbothwell** [comment]
I agree about `X.A.WithAll`. If we weren't worried about breaking changes we could rename the module and description to something like:

```
-- Provides functions for performing a given action on sets of windows of
-- the current workspace.
-----------------------------------------------------------------------------

module XMonad.Actions.With (
```

**Comment by ssbothwell** [comment]
@slotThe, I've made a PR in the `xmonad` repo: https://github.com/xmonad/xmonad/pull/327

Should I wait until that is merged to make the second commit here?

**Comment by slotThe** [comment]
On Thu, Sep 09 2021 10:31, Solomon Bothwell wrote:
> Should I wait until that is merged to make the second commit here?

That depends on whether you want to get annoyed at emails from GitHub
that the build is failing :)

**Comment by ssbothwell** [comment]
Does the CI use the head of the xmonad master branch or does it use a tagged release? I'll just wait for the other PR to be merged before writing this one.

**Comment by slotThe** [comment]
On Sun, Sep 12 2021 10:23, Solomon Bothwell wrote:
> Does the CI use the head of the xmonad master branch or does it use a
> tagged release? I'll just wait for the other PR to be merged before
> writing this one.

It uses HEAD; xmonad-0.15 does not build against contrib and hasn't been
able to for a while (that's why the current version is 0.16.99999 :)

**Comment by ssbothwell** [comment]
Got it. I'll just wait til we merge the other PR. :)
