### ISSUE TITLE
Example config doesn't build (layouts change?)

### ISSUE THREAD

**Issue by podiki** [xmonad/xmonad-contrib#560]
### Problem Description

In trying to diagnose errors with my own config after recent updates (I think the ||| layout changes?), I decided to just use `Example.hs` without changes as my config, but hit the following error. My normal config works if rolling back to commits before changes to XMonad.Layout.LayoutCombinators here and in XMonad.

```
xmonad.hs:32:43: error:
    • Couldn't match expected type ‘Choose
                                      Tall (Choose (Mirror Tall) Full) Window’
                  with actual type ‘XMonad.Layout.ToggleLayouts.ToggleLayouts
                                      (XMonad.Layout.LayoutModifier.ModifiedLayout
                                         XMonad.Layout.NoBorders.WithBorder Full)
                                      (Choose
                                         ResizableTall
                                         XMonad.Layout.BinarySpacePartition.BinarySpacePartition)
                                      Window’
    • In the first argument of ‘desktopLayoutModifiers’, namely
        ‘myLayouts’
      In the ‘layoutHook’ field of a record
      In the first argument of ‘additionalKeysP’, namely
        ‘desktopConfig
           {modMask = mod4Mask,
            manageHook = myManageHook <+> manageHook desktopConfig,
            layoutHook = desktopLayoutModifiers myLayouts,
            logHook = (dynamicLogString def >>= xmonadPropLog)
                        <+> logHook desktopConfig}’
   |
32 |     , layoutHook = desktopLayoutModifiers myLayouts
   |                                           ^^^^^^^^^

Please check the file for errors.
```

### Steps to Reproduce

On the latest git of xmonad and xmonad-config, building with Stack. Use `Example.hs` as `xmonad.hs` in building.

### Configuration File

Example config in xmonad-contrib.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version git 6a7eb85e84ddc2091706fbce5ff293e859481e51
    - [x] With `xmonad-contrib` version git 5067164d195a899a9e63547e94891919e97e0b74

**Comment by slotThe** [comment]
Well spotted, thanks!  This is fixed by the linked commit (it contains a lengthy explanation as to what happened, so I'll omit that here).

My advise would be to disregard X.C.Desktop completely; it really does not do anything useful anymore.  The example config is certainly an interesting find (I didn't even know that existed)—it certainly needs to be rewritten (perhaps to use the config we build up in the [tutorial](https://github.com/xmonad/xmonad/blob/master/TUTORIAL.md))

**Comment by podiki** [comment]
That was quick, thanks! Can confirm that `Example.hs` works, as well as (more importantly to me, of course) my own config (https://github.com/podiki/dot.me/blob/master/xmonad/.xmonad/xmonad.hs). And thanks for the explanation.

Yes, I see X.C.Desktop doesn't provide much anymore, I guess I can use that to see how a few things are done rather than directly basing my config off of it. It was helpful to have Example.hs to troubleshoot, as I was really at a loss of what was happening as I tried changing things. I think it is also useful to have as a starting point (though the newer tutorial looks really good now!), or something to test off of, or see breaking changes in action as an example of modifications to personal configs.

I don't have any immediate opinions on what to drop/change, but always happy to help test. Overall I think it is great to have a reasonable starting config for what will get people going and have a good experience, that is up to date and from upstream (rather than the many many configs out there of varying quality and what's up to date), and manages to address those frequent questions like fullscreen support.

Anyway, thanks, much appreciated!
