### ISSUE TITLE
X.A.UpdatePointer - pointer warping to lower right outside window when mouse move after update

### ISSUE THREAD

**Issue by ixzh** [xmonad/xmonad-contrib#566]
### Problem Description
X.A.UpdatePointer - pointer warping to lower right outside window when mouse move after update

### Steps to Reproduce

1. SUPER+j/k to change focus (the pointer is upated to the center of each window correctly);
2. Move mouse and pointer will continue moving from the center of the window (not warping);
3. SUPER + j/k  to update the cursor
4. focus back on the same window just now, the pointer position is correct;
5. move mouse again, the pointer will warp to lower right corner and start moving from there;

Strangely in step 5, if I move pointer using touchpad (I'm on a laptop), the pointer will not warp.

So if I use touchpad and mouse alternatively, the pointer will behave correctly, (if mouse went wrong, change to touchpad, and vice versa, for the pointer not to warp after update)

### Configuration File

```haskell
import XMonad.Actions.UpdatePointer
import XMonad.Hooks.DynamicLog
import XMonad.Actions.TiledWindowDragging
import XMonad.Layout.DraggingVisualizer

myLayout = 
           smartBorders .
           mkToggle (NBFULL ?? NOBORDERS ?? EOT) . 
           avoidStruts . 
           spacingRaw False (Border i i i i) True (Border i i i i) True . 
           avoidFloats . 
           layoutHintsToCenter .
           windowNavigation .
           subTabbed .
           draggingVisualizer .
           mkToggle (single REFLECTX) .
           mkToggle (single REFLECTY) .
           mkToggle (single MIRROR) .
           boringWindows .
           hiddenWindows .
           screenCornerLayoutHook .
           onWorkspaces ["2","6"] twoPane .
           showWName' myShowWNameTheme $ 
           myDefaultLayout
      where
           myDefaultLayout = Tall
           i=10

myPlacement = withGaps (0,0,0,0) (fixed (0.5,0.5))

myManageHook = composeAll . concat $
    [ [isDialog --> doCenterFloat]
    , [className =? c --> doCenterFloat | c <- myCFloats]
    , [title =? t --> doFloat | t <- myTFloats]
    , [resource =? r --> doFloat | r <- myRFloats]
    , [resource =? i --> doIgnore | i <- myIgnores]
    ]
    where
    myCFloats = ["Arandr", "Arcolinux-calamares-tool.py", "Arcolinux-tweak-tool.py", "Arcolinux-welcome-app.py", "Galculator", "feh", "Xfce4-terminal"]
    myTFloats = ["Downloads"
                ,"Save As..."
                ,"Media viewer"
                ,"About Mozilla Firefox"
                ]
    myRFloats = []

main :: IO ()
main = do
    xmonad $
     withNavigation2DConfig myNavigation2DConfig .
     ewmhFullscreen . 
     ewmh $
            myBaseConfig
                {startupHook = myStartupHook
, layoutHook = myLayout
, manageHook = 
               placeHook myPlacement <+> 
               floatNextHook <+> 
               manageSpawn <+> 
               myManageHook <+> 
               manageHook myBaseConfig
, logHook = dynamicLog >> updatePointer (0.5, 0.5) (0, 0)
, focusFollowsMouse = myFocusFollowsMouse
} 

```

### Checklist

  - [x ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` 0.16.9999 (commit 13849c6230188cfbc303348ea3b374be4b60b655)
    - [x] With `xmonad-contrib` 0.16.9999 (commit  e30269f)

**Comment by ixzh** [comment]
A side effect of X.A.Updatepointer,  it will prevent the new module X.A.TiledWindowDragging from working.

**Comment by slotThe** [comment]
I can't reproduce the issue in the OP.  I tried with the following config: 

``` haskell
import XMonad
import XMonad.Actions.UpdatePointer
import XMonad.Hooks.DynamicLog

main :: IO ()
main = xmonad $ def { logHook = dynamicLog >> updatePointer (0.5, 0.5) (0, 0) }
```

(It's always good to post a complete minimal example, so people don't have to guess how the rest of your confguration looks)

**Comment by liskin** [comment]
> Strangely in step 5, if I move pointer using touchpad (I'm on a laptop), the pointer will not warp.

This suggests it's more likely a bug (at this point arguably a feature 😐) in the X server than xmonad.

**Comment by ixzh** [comment]
> I can't reproduce the issue in the OP. I tried with the following config:
> 
> ```haskell
> import XMonad
> import XMonad.Actions.UpdatePointer
> import XMonad.Hooks.DynamicLog
> 
> main :: IO ()
> main = xmonad $ def { logHook = dynamicLog >> updatePointer (0.5, 0.5) (0, 0) }
> ```
> 
> (It's always good to post a complete minimal example, so people don't have to guess how the rest of your confguration looks)

Hi I updated the config section with addition of TiledWindowDragging,. Below shows the mouse warping either moving the mouse or after dragging the window, it always jump to lower right corner.  bear with the small pointer:

https://user-images.githubusercontent.com/14981695/123546898-24a5af80-d791-11eb-9446-b17f5d548762.mp4

**Comment by ixzh** [comment]
> > Strangely in step 5, if I move pointer using touchpad (I'm on a laptop), the pointer will not warp.
> 
> This suggests it's more likely a bug (at this point arguably a feature 😐) in the X server rather than xmonad.

could it because I adjusted sensitivity of mouse/touchpad(a less reliable touch occurs). but it consistently moves to lower right,  can it be a hardware problem? 🤔🤔🤔

**Comment by geekosaur** [comment]
XMonad can't tell the difference between the two inputs, so they should behave the same way unless there's something in the hardware or the server interfering. (It's possible to split the inputs, but then you'd have to teach xmonad and most other apps about `XInput2` to use both devices.)

**Comment by ixzh** [comment]
> XMonad can't tell the difference between the two inputs, so they should behave the same way unless there's something in the hardware or the server interfering. (It's possible to split the inputs, but then you'd have to teach xmonad and most other apps about `XInput2` to use both devices.)

hi, 
I have adjusted both touchpad and mouse sensitivity using systems service buy doing: 
```
xinput [mouse id] "transformation matrix" 15 0 0 0 15 0 0 0 0 2.5
xinput [touchpad id] "transformation matrix" 5 0 0 0 5 0 0 0 0 2.5
```
does it count as a server side input splitting ?

**Comment by geekosaur** [comment]
No, but it might conceivably affect this. Splitting the inputs would require first unbinding one or both devices from the "virtual input device" shown in the device tree.

**Comment by ixzh** [comment]
> No, but it might conceivably affect this. Splitting the inputs would require first unbinding one or both devices from the "virtual input device" shown in the device tree.

I see! and the culprit is indeed the sensitivity script! After disabling it, the updatePointer works correctly.  But the TiledWindowDragging is still not working: DraggingVisualizer shows the window dragging, but after releasing the mouse no switch is done. What could be the reason?

**Comment by ixzh** [comment]
> > No, but it might conceivably affect this. Splitting the inputs would require first unbinding one or both devices from the "virtual input device" shown in the device tree.
> 
> I see! and the culprit is indeed the sensitivity script! After disabling it, the updatePointer works correctly. But the TiledWindowDragging is still not working: DraggingVisualizer shows the window dragging, but after releasing the mouse no switch is done. What could be the reason? and how can I increase the sensivity without changing the transformation matrix?
