### ISSUE TITLE
Consider removing user specific modules from contrib

### ISSUE THREAD

**Issue by IvanMalison** [xmonad/xmonad-contrib#595]
It seems really strange to me that user specific configuration is included in xmonad-contrib. My suspicion is that very few people use these prebuilt configs, and it seems kind of ridiculous that everyone is forced to compile/download modules associated with this code.

It seems like a good solution might be to take these user specific configurations and put them in a separate repository that people could use if they want to try these configuration out.

**Comment by slotThe** [comment]
I would imagine these are from the time when "real world" xmonad configs
were not all that available online and it was nice to have a reference.

On Sat, Aug 14 2021 23:26, Ivan Malison wrote:
> It seems like a good solution might be to take these user specific
> configurations and put them in a separate repository that people could
> use if they want to try these configuration out.

We could do this, but I wonder if the trouble of deprecating them,
waiting 2--3 releases (however long that's going to take) and finally
moving them to a new repo is really worth it in this case.

**Comment by TheMC47** [comment]
> It seems like a good solution might be to take these user specific configurations and put them in a separate repository that people could use if they want to try these configuration out.

The website seems like a good candidate for that, we could also maybe add some screenshots

**Comment by ssbothwell** [comment]
I'm pretty new around here but I agree that it doesn't make much sense to have these configs in the repo. I agree with @TheMC47  that the website is a great place to put this type of content.

**Comment by IvanMalison** [comment]
> We could do this, but I wonder if the trouble of deprecating them, waiting 2--3 releases (however long that's going to take) and finally moving them to a new repo is really worth it in this case.

Not clear that this sort of thing ACTUALLY needs to be done.

The new release that is coming is ALL KINDS of backwards incompatible with the last one. I don't see any reason why would need to ease in the removal of these modules. I HIGHLY doubt that many people use them anyway.

**Comment by slotThe** [comment]
> The new release that is coming is ALL KINDS of backwards incompatible with the last one. I don't see any reason why would need to ease in the removal of these modules.

It is true that there are many breaking changes, but most are more of the form "X has been deprecated, use Y instead" or other small changes to the API.  I would classify removing an entire module as a bit of a different thing (though maybe I'm being too careful here).  

> I HIGHLY doubt that many people use them anyway.

I have actually seen the occasional user module importing one of these to use a utility function or two.  It's true that these are probably the among "safest" modules we could remove in terms of users noticing, but it _is_ removing entire modules.  

Perhaps a strategy could be to deprecate them for 0.17 and then (assuming we get another release out in half a years time or so) remove them after just one release

**Comment by geekosaur** [comment]
For what it's worth, `X.L.IndependentScreens` refers to `X.C.Droundy`. We would have to audit for other such references as well.

**Comment by IvanMalison** [comment]
> For what it's worth, X.L.IndependentScreens refers to X.C.Droundy. We would have to audit for other such references as well.

I mean ghc is pretty good at working stuff like that out, right?

**Comment by geekosaur** [comment]
It's in the documentation, not a code reference. I don't think haddock would give us quite as much help with dangling module references.

**Comment by slotThe** [comment]
GHC won't be of much help, but grepping for these module names shouldn't
be very difficult.

I think the only real decision left is to find a good place for these
modules.  The website seems best since we fully control that (perhaps
under the community tab we can add some links to up-to-date configs and
also to these "legacy" ones).

**Comment by liskin** [comment]
> It's in the documentation, not a code reference. I don't think haddock would give us quite as much help with dangling module references.

Haddock does actually generate warnings. Loads of them, in fact, so much so that we don't have any infrastructure in place to report those warnings, as we'd first have to spend hours fixing all the existing warnings. :-/
