### ISSUE TITLE
Expand or shrink master only when at least one window in stack

### ISSUE THREAD

**Issue by addy419** [xmonad/xmonad-contrib#599]
### This is more of a question than an issue.
I'm not sure if this is the correct place to ask this, please redirect me if it isn't

In ResizableTall, with sendMessage expand and sendMessage shrink, I can increase and decrease the size of master. The problem is that even if there is only master (one or multiple), These functions work in the background (the result only becomes visible when a window is added to stack). So if there is no window in stack, do not expand or shrink master.

Also, when all windows in stack (the right side) are removed, the changes done by expand and shrink are still present and become visible when new window enters stack. I want to avoid this. I use resizing for only certain windows (say browser) so I don't want the expand/shrink persistent

I have a solution for this but I don't know enough about xmonad's windowing system to implement this:
Create a function isStackEmpty which tells if the stack in current workspace is empty. Then keybind,
`if !isStackEmpty then sendMessage expand/shrink.`

In the second part, a hook which executes a function when a new window is added or removed from current workspace (or no of windows in master pane inc/dec). This hook will reset the layout (say 0.5 split by default) if isStackEmpty is true.

**Comment by addy419** [comment]
To implement isStackEmpty, I can check if no. of windows in current workspace <= nmaster but idk how to get the values for either

**Comment by slotThe** [comment]
> To implement isStackEmpty, I can check if no. of windows in current workspace <= nmaster but idk how to get the values for either

There is already an [index](https://hackage.haskell.org/package/xmonad-0.15/docs/XMonad-StackSet.html#v:index) function that returns the current stack as a list, so you would only need to check whether that list is empty:

``` haskell
import qualified Data.StackSet as W

isStackEmpty :: X Bool
isStackEmpty = null . W.index <$> gets windowset
```

**Comment by addy419** [comment]
@slotThe Thanks for the help, is the the way to trigger a function on window closed/killed?

**Comment by slotThe** [comment]
> @slotThe Thanks for the help, is the the way to trigger a function on window closed/killed?

The `logHook` runs on every internal state update.  It's not typed very well, so you can't subscribe to certain events or anything like that.  In your case of wanting to check for an empty workspace though, that shouldn't be too expensive to run every time.  

``` haskell
emptyWsLogHook :: X ()
emptyWsLogHook = whenX isStackEmpty $ 
  {- code -}
```

Running something when the number of master windows increases or decreases should be possible by just executing that whenever you press that particular keybinding.  Getting the actual number of master windows will not be so easy, though.  Keeping track of this is essentially the job of the layout and introspection there is difficult

**Comment by addy419** [comment]
@slotThe Thanks for the help
