### ISSUE TITLE
Delete/Auto-generate `XMonad.Doc.Extending` sections

### ISSUE THREAD

**Issue by TheMC47** [xmonad/xmonad-contrib#619]
### Problem Description

Currently, `XMonad.Doc.Extending` lists every module with its description. The descriptions were moved to the corresponding Haddock field in each module's file in #609 (thanks @slotThe!). The problem: now there are two places that need to be updated when the description is tweaked (I'm looking at you, #613). 

#### Proposal
Let's just remove the list of modules `XMonad.Doc.Extending`. Haddock beautifully generates a grouped list of all modules (https://xmonad.github.io/xmonad-docs/xmonad-contrib-0.16.999/), so having the list in `X.D.Extending` isn't really adding anything.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

**Comment by slotThe** [comment]
Agreed, let's kill that list with fire

**Comment by slotThe** [comment]
Closed by https://github.com/xmonad/xmonad-contrib/pull/620 (839302533bed6c6ece709a9d8508cc9b773b3975)
