### ISSUE TITLE
XMonad.Layout.BinarySpacePartition is missing upstream updates

### ISSUE THREAD

**Issue by haasn** [xmonad/xmonad-contrib#64]
https://github.com/benweitzman/BinarySpacePartition/commit/97e5553d2038a2003fb3bd91b5d7d821d82c3d83 is the commit in particular that is missing from xmonad-contrib.

I would appreciate a cherry-pick of this into xmonad-contrib so I don't have to maintain my own out-of-tree package for this updated module.

**Comment by geekosaur** [comment]
It's not up to us to chase down updates to contributed packages; there are too many of them from too many different people. It would be up to the original contributor (...except the repo you pointed to doesn't appear to be the original contributor. So, are we *also* expected to chase all forks of the original down and pick one to be blessed?) to submit updates.

**Comment by byorgey** [comment]
Of course, we are happy to consider a pull request!  But I'd prefer it go through that normal process rather than someone just cherry-picking it in without review.
