### ISSUE TITLE
X.A.Search: rm Google _n_-hits-per-page option - meaning has reversed to now 'no *more* than _n_, total'

### ISSUE THREAD

**Issue by gwern** [xmonad/xmonad-contrib#642]
In `XMonad.Actions.Search`, the plugin line 301:

    google        = searchEngine "google"        "https://www.google.com/search?num=100&q="

needs to be modified to delete the `num=100&` argument:

    google        = searchEngine "google"        "https://www.google.com/search?q="

It no longer does what it was intended to do, and in fact, now does the opposite.

When I wrote X.A.Search back in 2007 or so (porting code from Surfraw which was even older), Google's default of showing 10 or so search hits was radically inadequate for poweruser needs. The 'num' argument was used to force display of more hits (ie _n_ meant 'display at least _n_ hits per page').

Just today, investigating the bizarrely few number of hits for a notable person, I discovered that at some point, 'num' was inverted to mean something catastrophically different: now it apparently means 'display no more than _n_ hits, total'. If you use that parameter, you will get 1 or 2 pages of hits at most reading 'About 98 results' or 'About 99 results' (no matter how many millions are available), and a blurb at the bottom of the final page saying  'In order to show you the most relevant results, we have omitted some entries very similar to the 99 already displayed.' Removing the 'num' parameter then shows you all the hits that were suppressed.

This is bad, and should be removed.

**Comment by slotThe** [comment]
> This is bad, and should be removed.

Sounds reasonable; would you like to do this yourself?

**Comment by gwern** [comment]
I don't believe I have a commitbit on the XMC repo, do I?

**Comment by geekosaur** [comment]
Anyone can submit a PR, though. For this it'd be reviewed and merged pretty quickly.

**Comment by slotThe** [comment]
> I don't believe I have a commitbit on the XMC repo, do I?

Ah, indeed, I must've made assumptions.  Well, as geekosaur said, you can either open a PR or I can push a fix for this directly; whatever you prefer

**Comment by gwern** [comment]
Yeah, just make the change. A PR seems like a lot of ceremony to delete 8 characters.
