### ISSUE TITLE
Build error with failed parsing

### ISSUE THREAD

**Issue by JoshuaJakowlew** [xmonad/xmonad-contrib#656]
### Problem Description

Arch Linux build error

I'm just trying to do regular update, but build fails with unexpected input

```
==> Starting build()...
Warning: xmonad-contrib.cabal:65:20:
unexpected 'd'
expecting space, white space, opening paren, operator, comma or end of input
Setup.lhs: Failed parsing "./xmonad-contrib.cabal".

==> ERROR: A failure occurred in build().
    Aborting...
```

### Steps to Reproduce

Update git-version with regular paru update.

### Configuration File

It's not a problem in config file.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version XXX (commit XXX if using git)
    - [x] With `xmonad-contrib` version XXX (commit XXX if using git)

**Comment by slotThe** [comment]
This seems like an error with the AUR version of `xmonad-contrib`, HEAD builds fine here.  

Judging from the site [here](https://aur.archlinux.org/packages/xmonad-contrib-git/) they need to add `deepseq` to the dependencies (I don't know what it's called on Arch).
