### ISSUE TITLE
X.H.StatusBar.statusBarGeneric doesn't even try to kill bars

### ISSUE THREAD

**Issue by PRESFIL** [xmonad/xmonad-contrib#668]
### Problem Description

I used `genericStatusBar` with a polybar inside Xephyr, and I realized that when I exit XMonad,
the polybar remains, no one kills it. It turned out that no one kills through tty when starting a
session through `startx` polybar doesn't get killed either, and it crashes due to loss of the X-display
(after shutting down the X server).

> -- The above has the problem that xmobar will not get restarted whenever you
> -- restart xmonad ('XMonad.Util.SpawnOnce.spawnOnce' will simply prevent your
> -- chosen status bar from spawning again). Using 'statusBarProp', however, takes
> -- care of the necessary plumbing /and/ keeps track of the started status bars, so
> -- they can be correctly restarted with xmonad. This is achieved using
> -- 'spawnStatusBar' to start them and 'killStatusBar' to kill
> -- previously started bars.

As far as I understand, now `statusBarProp` is implemented through `genericStatusBar`,
but it does not kill processes. But `sbCleanupHook` is specified anyway. `cleanSBs` (which
executes `sbCleanupHook`'s, only used in `dynamicSBs`).

### Steps to Reproduce

For polybar [xmonad-dbus](https://github.com/troydm/xmonad-dbus) shoult be installed.

1. Install `xmonad`, `xmonad-contrib` and `xmonad-dbus` -git versions with `stack`
2. `Xephyr :1` in one terminal emulator
3. `DISPLAY=:1` in another terminal emulator
4. Switch to Xephyr window
5. Lock on it with <kbd>Ctrl-Shift</kbd>
6. Exit XMonad with default keybinding
7. Polybar remains in Xephyr
8. (Exit from Xephyr with <kbd>Ctrl-Shift</kbd>)

or

1. Install `xmonad`, `xmonad-contrib` and `xmonad-dbus` -git versions with `stack`
2. Login tty
3. Start `startx` session
4. Exit session
5. Polybar prints to tty that it has lost connection with the X-display

### Configuration File

- Use <kbd>Mod-Ctrl-D</kbd> to append current bars binds into `/tmp/xmonad.log`.

- X.H.StatusBar need to be patched to export `StatusBarPIDs` and `ExtensionClass`.

```diff
diff --git a/XMonad/Hooks/StatusBar.hs b/XMonad/Hooks/StatusBar.hs
index 3ec54a08..0d79bb26 100644
--- a/XMonad/Hooks/StatusBar.hs
+++ b/XMonad/Hooks/StatusBar.hs
@@ -56,6 +56,10 @@ module XMonad.Hooks.StatusBar (
   spawnStatusBar,
   killStatusBar,
   killAllStatusBars,
+
+  -- * Other
+  StatusBarPIDs(..),
+  ExtensionClass(..)
   ) where

 import Control.Exception (SomeException, try)
diff --git a/stack.yaml b/stack.yaml
index d4e0ead1..9be19b03 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -8,6 +8,7 @@ packages:

 extra-deps:
 - X11-1.10.2
+- X11-xft-0.3.4
 - xmonad-0.17.0

 nix:
```

Or you can not use debugging and remove `debugStuff`, `myAppendFile`,
`logToTmpFile` and `myKeys`.

**Main config:**

```haskell
import XMonad
import qualified XMonad.DBus as D
import qualified DBus.Client as DC
import XMonad.Hooks.DynamicLog
import XMonad.Hooks.StatusBar
import XMonad.Util.NamedActions

import System.IO
import System.Posix.Types (ProcessID)
import qualified XMonad.Util.ExtensibleState as XS

import Control.Monad (when)
import qualified Data.Map as M
import Data.Monoid (All(..))

-- based on: https://unix.stackexchange.com/questions/571208/how-to-debug-xmonad-layout-noborders-smartborders-not-working

debugStuff :: X ()
-- debugStuff = XS.gets (M.elems . getPIDs) >>= io . logToTmpFile . show
debugStuff = XS.gets (M.elems . getPIDs) >>= io . logToTmpFile . show

myAppendFile :: FilePath -> String -> IO ()
myAppendFile f s = do
  withFile f AppendMode $ \h -> do
    hPutStrLn h s

logToTmpFile :: String -> IO ()
logToTmpFile = myAppendFile "/tmp/xmonad.log" . (++ "\n")

myKeys conf@(XConfig {XMonad.modMask = modm}) =
  [ ((modm .|. controlMask, xK_d), addName "debug" $ debugStuff)
  ]

-- logHook for polybar
polybarLogHook :: DC.Client -> PP
polybarLogHook dbus = def { ppOutput = D.send dbus
                     , ppCurrent = wrap ("%{F" ++ yellow ++ "}[") "]%{F-}"
                     , ppUrgent = wrap ("%{F" ++ red ++ "}[") "]%{F-}"
                     , ppHidden = wrap " " " "
                     , ppWsSep = ""
                     , ppSep = " : "
                     , ppTitle =  wrap ("%{F" ++ green ++ "} ") " %{F-}" . shorten 40
                     }
  where green     = "#00ff00"
        red       = "#ff0000"
        yellow    = "#ffff00"

-- generic bar polybar
polybarSB dbusConnection = statusBarGeneric "polybar -r" lh
  where lh = dynamicLogWithPP $ polybarLogHook dbusConnection

main = do
  -- Connect to DBus
  dbus <- D.connect
  -- Request access (needed when sending messages)
  D.requestAccess dbus
  let polybar = withEasySB (polybarSB dbus) defToggleStrutsKey
  -- start xmonad
  xmonad $ polybar (addDescrKeys ((mod4Mask, xK_slash), xMessage) myKeys def
    { modMask = mod4Mask
    })
```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [X] With `xmonad` version 0.17.0.9 (commit e25d090112f2a76364a10b88a729b8586c18145b)
    - [X] With `xmonad-contrib` version 0.17.0 (commit 061faf17485cbeeb9372e68394572ba4d58ab53e)

**Comment by TheMC47** [comment]
Thanks for the extensive issue report, it's refreshing to see this 😁This is however an expected behavior, xmonad doesn't have an exit hook so cleanups happen on restart. I don't think it's a normal use case that should be accounted for either, so I'm closing the issue. If you think otherwise, you can reopen it and we can discuss.

**Comment by PRESFIL** [comment]
Really, I noticed that when you restart XMonad, the polybar also restarts.
It was necessary to understand the word "restarting" -- not as restarting the process,
but as the built-in function of restarting XMonad.

I think it would be better if there were a separate hook, like `shutdownHook`,
for example. What is happening now is not very obvious.

**Comment by TheMC47** [comment]
It might be indeed useful, but it would need to be a change in the core. Maybe we open an issue there, and see if there are enough use cases to warrant adding it?

**Comment by geekosaur** [comment]
<a href="https://github.com/xmonad/xmonad/issues/77">It's already there.</a>

**Comment by PRESFIL** [comment]
Thanks @geekosaur ! I even guessed the name :smile: ! Is this the sagacity or consistency
of XMonad? Who knows...

**Comment by TheMC47** [comment]
And I already commented on it... My memeory is failing me these days

**Comment by geekosaur** [comment]
Consistency, I hope. :)
