### ISSUE TITLE
GitHub Actions: Add separate hlint action

### ISSUE THREAD

**Issue by slotThe** [xmonad/xmonad-contrib#669]
### Problem Description

Due to hlint's [inconsistent packaging of releases](https://github.com/ndmitchell/hlint/issues/1326) it may be better to introduce a separate action for it.  This would enable us to

  + have more fine-grained control over the version that we use (e.g. in a situation like this we could just roll back to the last release),
  + decouple the "hlint" step from the "does it work with some recent versions of GHC" step, which seems conceptually nicer.

For example, the `haskell-language-server` people seem to have already done this [here](https://github.com/haskell/haskell-language-server/pull/2537)

**Comment by ndmitchell** [comment]
The latest release of hlint now has a release binary.

**Comment by slotThe** [comment]
> The latest release of hlint now has a release binary.

That's great news; thanks for the heads up!

**Comment by liskin** [comment]
I'll just note that the actions used in HLS CI are now part of the "official" Haskell GH Actions: https://github.com/haskell/actions/tree/main/hlint-setup, https://github.com/haskell/actions/tree/main/hlint-run so if this ever breaks again, we should try those.

**Comment by liskin** [comment]
Note that even with haskell-ci, we do have fine-grained control over the version we use, see https://github.com/xmonad/xmonad-contrib/commit/154388aa208fdb2e45da8afa6f72c72deb0251b9#diff-eacabc2a664e928ef8b473245e842e4b29b9904fb1e4f64d565abbab93323e5cR12
So this really is only about the decoupling. Not sure if worth it, as we've been back to "just works" for a while.

**Comment by slotThe** [comment]
I didn't know about the `hlint-version` options, you're right that this is probably enough.  Feel free to close if you don't think the decoupling is worth it

**Comment by liskin** [comment]
I just realized it's not just decoupling, but also that the https://github.com/haskell/actions/tree/main/hlint-run action produces annotations that GitHub understands and shows them directly in the PR diff. So this will likely be a quality-of-life improvement after all, and I'll leave this open then.

(I'll deal with https://github.com/xmonad/xmonad/pull/401 and https://github.com/xmonad/xmonad/pull/402 today but won't be spending any more time on hlint this weekend…)
