### ISSUE TITLE
Cannot launch apps using prompt if data dir does not exist

### ISSUE THREAD

**Issue by phunehehe** [xmonad/xmonad-contrib#68]
In addition to the error messages below, the launch never happens. Seems like the command is written to the history file before executing, and gets cancelled by the error.

```
error writing history: /home/phunehehe/.xmonad/history: openFile: does not exist (No such file or directory)
/home/phunehehe/.xmonad/history: setFileMode: does not exist (No such file or directory)
```

**Comment by geekosaur** [comment]
How did you manage to trigger this? The only way you would have XMonad.Prompt usable would require a custom config in ~/.xmonad/xmonad.hs and corresponding compiled version ~/.xmonad/xmonad-<platform>-<os>.

**Comment by phunehehe** [comment]
Ah that explains it. I built a binary with xmonad contrib as a dependency
and added it to PATH (
https://gitlab.com/phunehehe/my-xmonad/blob/master/my-xmonad.cabal). Thus I
don't have ~/.xmonad/xmonad.hs.
