### ISSUE TITLE
..StatusBar get workspace properties like sid in :: PP

### ISSUE THREAD

**Issue by NnAsUnKnOwn** [xmonad/xmonad-contrib#681]
### Problem Description
I have an idea but not the necessary knowledge to carry it out, I have been trying for 48 hours.
the goal is to achieve that xmobars launched in multihead(+2 screens) configuration
show in their workspace pp list the sid or xrandr-name correspondig to ppCurrent and ppVisible, also the display corresponding to the xmobar instance, here is an example
1) with xrandr name
5(LVDS1)  *3(VGA1) 1(VIRTUAL1) 2 4 6 7 8 9 | VGA1 | TITLE.....
2) with sid
5(0)  *3(1) 1(2) 2 4 6 7 8 9 | 1 | TITLE.....
2) with independent screen (Not my case)
LVDS[ 1 *2 ] VGA1[ *1 2 ] VIRTUAL1[ 1 2 *3 ] | VGA1 | TITLE.......

### Configuration File

xmonad.hs
```haskell
import XMonad
import qualified Data.Set as S
import qualified Data.Map as M

import XMonad.Util.EZConfig
import XMonad.Util.Run

import XMonad.Hooks.StatusBar
import XMonad.Hooks.StatusBar.PP
import XMonad.Hooks.ManageDocks

main = xmonad $ docks $ dynamicSBs barSpawner def
       {
         terminal = "xterm"
       , startupHook = do
           spawn "xrandr --output VIRTUAL2 --off --output VIRTUAL1 --off --output LVDS1 --primary --mode 1024x768 --pos 0x1920 --rotate normal --output VGA1 --mode 1920x1080 --$
       }

xmobarCmd = "xmobar -B white -F black"

barSpawner :: ScreenId -> IO StatusBarConfig
barSpawner (S sid) = pure $
  statusBarPropTo ("_XMONAD_LOG_" ++ show sid) ( xmobarCmd ++ " --screen " ++ show sid ++ " ~/.xmobarrc" ++ show sid) (pure myXmobarPP)

myXmobarPP :: PP
myXmobarPP = def {
  ppCurrent          = xmobarColor "red"    "white"  . wrap " " " "
  ,ppVisible         = xmobarColor "gray"   "white"   . wrap " " " "
  ,ppTitle           = xmobarColor "black"  "white"   . shorten 128 . wrap "  " ""
  ,ppWsSep           = xmobarColor "white"  "white"   " "
  ,ppSep             = xmobarColor "black"  "white"   " | "
  }
```

~/.xmobarrc0
```haskell
Config {
  alpha              = 255
  , position         = Top
  , textOffset       = -1
  , iconOffset       = -1
  , lowerOnStart     = True
  , allDesktops      = False
  , overrideRedirect = False
  , pickBroadest     = True
  , persistent       = False
  , sepChar    = "%"
  , commands = [
      Run XPropertyLog "_XMONAD_LOG_0"
      , Run StdinReader
      , Run Date "%d/%m/%Y %H:%M:%S " "date" 10
      ]
  , alignSep   = "}{"
  , template = "%_XMONAD_LOG_0% }{ ..."
  }                                                                                                                                                                              


```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.0
    - [x] With `xmonad-contrib` 0.17

  with GHC 8.8.4
  build-depends:       
                     base >= 4.12
                     , containers
                     , data-default
                     , fuzzy
                     , monoid-subclasses
                     , mtl
                     , process
                     , unix
                     , split
                     , utf8-string
                     , X11 >= 1.9.2
                     , X11-xft >= 0.3.1
                     --, X11-extras >= 0.4
                     , xmobar >= 0.40
                     , xmonad >= 0.16 && < 0.18
                     , xmonad-contrib >= 0.16 && < 0.18
                     , text

**Comment by TheMC47** [comment]
Well, I have _something_, but not totally happy with it:

```haskell

unscreen :: ScreenId -> Int
unscreen (S sid) = sid

currentWithScreen :: X String
currentWithScreen = (<>) <$> current <*> currentScreen
 where
  current       = withWindowSet $ return . W.currentTag
  currentScreen = wrap "(" ")"
    <$> withWindowSet (return . show . unscreen . W.screen . W.current)

visibleWithScreen :: X (WorkspaceId -> String)
visibleWithScreen = do
  ss <- map visibleWithScreens <$> withWindowSet (return . W.screens)
  return $ \wid -> case lookup wid ss of
    Just sid -> wid <> wrap "(" ")" (show sid)
    _        -> "Something went wrong"
 where
  visibleWithScreens s = (W.tag . W.workspace $ s, unscreen . W.screen $ s)

barSpawner :: ScreenId -> IO StatusBarConfig
barSpawner (S sid) = pure $
  statusBarPropTo ("_XMONAD_LOG_" ++ show sid) ( xmobarCmd ++ " --screen " ++ show sid ++ " ~/.xmobarrc" ++ show sid) myXmobarPP

myXmobarPP :: X PP
myXmobarPP = do
  c <- currentWithScreen
  vs <- visibleWithScreen
  return $ def
    { ppCurrent = xmobarColor "red" "white" . wrap " " " " . const c
    , ppVisible = xmobarColor "gray" "white" . wrap " " " " . vs
    , ppTitle   = xmobarColor "black" "white" . shorten 128 . wrap "  " ""
    , ppWsSep   = xmobarColor "white" "white" " "
    , ppSep     = xmobarColor "black" "white" " | "
    }
```

This breaks if you're using `clickablePP`, but I haven't investigated it further (something with the rename). It might be better to rework `visibleWithScreen` in terms of `ppRename`, but I haven't had time to do that

**Comment by NnAsUnKnOwn** [comment]
> Well, I have _something_, but not totally happy with it:
> 
> ```haskell
> unscreen :: ScreenId -> Int
> unscreen (S sid) = sid
> 
> currentWithScreen :: X String
> currentWithScreen = (<>) <$> current <*> currentScreen
>  where
>   current       = withWindowSet $ return . W.currentTag
>   currentScreen = wrap "(" ")"
>     <$> withWindowSet (return . show . unscreen . W.screen . W.current)
> 
> visibleWithScreen :: X (WorkspaceId -> String)
> visibleWithScreen = do
>   ss <- map visibleWithScreens <$> withWindowSet (return . W.screens)
>   return $ \wid -> case lookup wid ss of
>     Just sid -> wid <> wrap "(" ")" (show sid)
>     _        -> "Something went wrong"
>  where
>   visibleWithScreens s = (W.tag . W.workspace $ s, unscreen . W.screen $ s)
> 
> barSpawner :: ScreenId -> IO StatusBarConfig
> barSpawner (S sid) = pure $
>   statusBarPropTo ("_XMONAD_LOG_" ++ show sid) ( xmobarCmd ++ " --screen " ++ show sid ++ " ~/.xmobarrc" ++ show sid) myXmobarPP
> 
> myXmobarPP :: X PP
> myXmobarPP = do
>   c <- currentWithScreen
>   vs <- visibleWithScreen
>   return $ def
>     { ppCurrent = xmobarColor "red" "white" . wrap " " " " . const c
>     , ppVisible = xmobarColor "gray" "white" . wrap " " " " . vs
>     , ppTitle   = xmobarColor "black" "white" . shorten 128 . wrap "  " ""
>     , ppWsSep   = xmobarColor "white" "white" " "
>     , ppSep     = xmobarColor "black" "white" " | "
>     }
> ```
> 
> This breaks if you're using `clickablePP`, but I haven't investigated it further (something with the rename). It might be better to rework `visibleWithScreen` in terms of `ppRename`, but I haven't had time to do that

Friend that's great! thanks.. for now clickablePP is not an issue, now i'm looking for the xrandr  names, find this in https://github.com/disconsis/literate-xmonad-config/blob/master/src/config.org

monitorIds :: IO [(ScreenId, Text)]
monitorIds = do
  output <- toText <$> outputOf "xrandr --listactivemonitors 2>/dev/null | awk '{print $1 $4}'"
  return $ mapMaybe parseMonitor . drop 1 $ lines output
  where
    parseMonitor :: Text -> Maybe (ScreenId, Text)
    parseMonitor text = do
      let (idText, monitorText) = T.breakOn ":" text
      monitor <- T.stripPrefix ":" monitorText
      id <- readMaybe . toString $ idText
      return (S id, monitor)

**Comment by TheMC47** [comment]
I'll definitely re-implement this in `ppRename`, I spent quite some time away so I forgot that the thing even exists lol. I think it's a pretty hand extension, I'll have some code hopefully ready by today or tomorrow. Adding the monitor names should be easy too.

**Comment by TheMC47** [comment]
I think this is worthy of its own module, here's what I got:

```haskell
type WindowScreen
  = W.Screen WorkspaceId (Layout Window) Window ScreenId ScreenDetail

type WorkspaceScreenCombiner = String -> WindowScreen -> String

monitorIds :: IO [(ScreenId, String)]
monitorIds = return [(S 0, "HDMI-0"), (S 1, "eDP-1-1")]


unscreen :: ScreenId -> Int
unscreen (S sid) = sid

combineWithScreenNumber :: X WorkspaceScreenCombiner
combineWithScreenNumber =
  return $ \w sc -> w <> wrap "(" ")" (show . unscreen . W.screen $ sc)

combineWithScreenName :: X WorkspaceScreenCombiner
combineWithScreenName = do
  screenNames <- io monitorIds
  return
    $ \w sc -> w <> wrap "(" ")" (fromJust $ W.screen sc `lookup` screenNames)

renameWithScreen
  :: X WorkspaceScreenCombiner -> X (String -> WindowSpace -> String)
renameWithScreen xCombiner = do
  combiner <- xCombiner
  ss       <- withWindowSet (return . W.screens)
  return $ \s w ->
    maybe s (combiner s) (find ((== W.tag w) . W.tag . W.workspace) ss)

addScreen :: X WorkspaceScreenCombiner -> PP -> X PP
addScreen xcombiner pp =
  renameWithScreen xcombiner <&> \ren -> pp { ppRename = ppRename pp <=< ren }


barSpawner :: ScreenId -> IO StatusBarConfig
barSpawner (S sid) = pure $
  statusBarPropTo ("_XMONAD_LOG_" ++ show sid) ( xmobarCmd ++ " --screen " ++ show sid ++ " ~/.xmobarrc" ++ show sid) myXmobarPP

myXmobarPP :: X PP
myXmobarPP = 
  addScreen combineWithScreenName $ def
    { ppCurrent = xmobarColor "red" "white" . wrap " " " " . const c
    , ppVisible = xmobarColor "gray" "white" . wrap " " " " . vs
    , ppTitle   = xmobarColor "black" "white" . shorten 128 . wrap "  " ""
    , ppWsSep   = xmobarColor "white" "white" " "
    , ppSep     = xmobarColor "black" "white" " | "
    }
```
You can replace `combineWithScreenName` with `combineWithScreenNumber` (I mocked `combineWithScreenName` since I didn't want to add `text` as a dependency)

**Comment by NnAsUnKnOwn** [comment]
> I think this is worthy of its own module, here's what I got:
> 
> ```haskell
> type WindowScreen
>   = W.Screen WorkspaceId (Layout Window) Window ScreenId ScreenDetail
> 
> type WorkspaceScreenCombiner = String -> WindowScreen -> String
> 
> monitorIds :: IO [(ScreenId, String)]
> monitorIds = return [(S 0, "HDMI-0"), (S 1, "eDP-1-1")]
> 
> 
> unscreen :: ScreenId -> Int
> unscreen (S sid) = sid
> 
> combineWithScreenNumber :: X WorkspaceScreenCombiner
> combineWithScreenNumber =
>   return $ \w sc -> w <> wrap "(" ")" (show . unscreen . W.screen $ sc)
> 
> combineWithScreenName :: X WorkspaceScreenCombiner
> combineWithScreenName = do
>   screenNames <- io monitorIds
>   return
>     $ \w sc -> w <> wrap "(" ")" (fromJust $ W.screen sc `lookup` screenNames)
> 
> renameWithScreen
>   :: X WorkspaceScreenCombiner -> X (String -> WindowSpace -> String)
> renameWithScreen xCombiner = do
>   combiner <- xCombiner
>   ss       <- withWindowSet (return . W.screens)
>   return $ \s w ->
>     maybe s (combiner s) (find ((== W.tag w) . W.tag . W.workspace) ss)
> 
> addScreen :: X WorkspaceScreenCombiner -> PP -> X PP
> addScreen xcombiner pp =
>   renameWithScreen xcombiner <&> \ren -> pp { ppRename = ppRename pp <=< ren }
> 
> 
> barSpawner :: ScreenId -> IO StatusBarConfig
> barSpawner (S sid) = pure $
>   statusBarPropTo ("_XMONAD_LOG_" ++ show sid) ( xmobarCmd ++ " --screen " ++ show sid ++ " ~/.xmobarrc" ++ show sid) myXmobarPP
> 
> myXmobarPP :: X PP
> myXmobarPP = 
>   addScreen combineWithScreenName $ def
>     { ppCurrent = xmobarColor "red" "white" . wrap " " " " . const c
>     , ppVisible = xmobarColor "gray" "white" . wrap " " " " . vs
>     , ppTitle   = xmobarColor "black" "white" . shorten 128 . wrap "  " ""
>     , ppWsSep   = xmobarColor "white" "white" " "
>     , ppSep     = xmobarColor "black" "white" " | "
>     }
> ```
> 
> You can replace `combineWithScreenName` with `combineWithScreenNumber` (I mocked `combineWithScreenName` since I didn't want to add `text` as a dependency)

Hi, friend i think the same and also works for get other parameters from workspaces in multihead scheme..

i'm getting this trying this setup :

xmonad.hs:65:30: error:
    • Variable not in scope:
        (<&>) :: X (String -> WindowSpace -> String) -> (t0 -> PP) -> X PP
    • Perhaps you meant one of these:
        ‘<>’ (imported from Prelude), ‘<&&>’ (imported from XMonad),
        ‘<+>’ (imported from XMonad)
   |
65 |   renameWithScreen xcombiner <&> \ren -> pp { ppRename = ppRename pp <=< ren }
   |                                                       ^^^

xmonad.hs:65:70: error:
    • Variable not in scope:
        (<=<)
          :: (String -> WindowSpace -> String)
             -> t0 -> String -> WindowSpace -> String
    • Perhaps you meant one of these:
        ‘=<<’ (imported from Prelude), ‘<=’ (imported from Prelude)
   |
65 |   renameWithScreen xcombiner <&> \ren -> pp { ppRename = ppRename pp <=< ren }
   |                                                                                                                               ^^^

xmonad.hs:81:68: error: Variable not in scope: c :: String
   |
81 |     { ppCurrent = xmobarColor "red" "white" . wrap " " " " . const c
   |                                                                                                        ^

xmonad.hs:82:63: error:
    Variable not in scope: vs :: WorkspaceId -> String
   |
82 |     , ppVisible = xmobarColor "gray" "white" . wrap " " " " . vs
   |                                                                                              ^^
Linking /home/username/.xmonad/dist-newstyle/build/i386-linux/ghc-8.8.4/my-xmonad-0.1.0.0/x/xmonadctl/build/xmonadctl/xmonadctl ...
cabal: Failed to build exe:xmonad from my-xmonad-0.1.0.0.

**Comment by TheMC47** [comment]
Oh, I forgot to remove the old code from the `PP`

```haskell
myXmobarPP :: X PP
myXmobarPP = 
  addScreen combineWithScreenName $ def
    { ppCurrent = xmobarColor "red" "white" . wrap " " " " 
    , ppVisible = xmobarColor "gray" "white" . wrap " " " " 
    , ppTitle   = xmobarColor "black" "white" . shorten 128 . wrap "  " ""
    , ppWsSep   = xmobarColor "white" "white" " "
    , ppSep     = xmobarColor "black" "white" " | "
    }
```

You also need to import `Data.Functor` and `Control.Monad`

**Comment by NnAsUnKnOwn** [comment]
> Oh, I forgot to remove the old code from the `PP`
> 
> ```haskell
> myXmobarPP :: X PP
> myXmobarPP = 
>   addScreen combineWithScreenName $ def
>     { ppCurrent = xmobarColor "red" "white" . wrap " " " " 
>     , ppVisible = xmobarColor "gray" "white" . wrap " " " " 
>     , ppTitle   = xmobarColor "black" "white" . shorten 128 . wrap "  " ""
>     , ppWsSep   = xmobarColor "white" "white" " "
>     , ppSep     = xmobarColor "black" "white" " | "
>     }
> ```
> 
> You also need to import `Data.Functor` and `Control.Monad`

Hi Friend, works perfectly with logTitlesOnScreen and layoutOnScreen :1st_place_medal: 

Thanks

**Comment by TheMC47** [comment]
@NnAsUnKnOwn I cleaned up the code and created a #684
