### ISSUE TITLE
Get our labels in order

### ISSUE THREAD

**Issue by slotThe** [xmonad/xmonad-contrib#693]
This is only something that maintainers (or "collaborators"?) can do but I'm still putting it here so that we don't forget!  It started with this (slightly edited) conversation on IRC:

  > \<liskin\> Solid, mc47, geekosaur: I played with the new github projects a bit today: https://github.com/orgs/xmonad/projects/4
  > \<liskin\> feature-wise, it's really crap as it's missing a few features that the old projects had, but it looks nice
  > \<mc47\>   it does look nice, except for the labels tabs. that's ugly
  > \<liskin\> mc47: I thought that perhaps if we reduced the number of labels we have and just had a few labels that actually provide some useful value, then it might not be too bad
  > \<mc47\>   I can't see all labels without resizing the column :D and yes, the labels have a low information density, but not sure how we can improve that
  > \<liskin\> I'd start by deleting all labels and then add labels when we actually (think we) need them :-)

So let's do that, shall we? :)

**Comment by TheMC47** [comment]
Yes! I think the 9 labels are useful when we have more PRs (e.g. let's say I have a free time to review things, I can skip PRs that have `9.needs: squash commits`). Not sure about the 2 and 3. 6 could be improved. 4 might be useful for new collaborators. 0 seems useful, but we don't really use it. 1 would help us triage, but I don't see its usefulness yet.

Hence: it might be better to start from a clean slate

**Comment by slotThe** [comment]
Sure, starting over from scratch doesn't sound horrible.  What would people like to have in terms of labels?

Things that I think we need for issues:

  - good first issue (this exact wording is necessary for GitHub to pick it up in e.g. https://github.com/xmonad/xmonad-contrib/contribute)
  - help wanted
  - needs: reproducibility  (or `not reproducible` or something like that)
  - bug
  - feature request

For PRs the only thing I can think of would be a few "stalled: *REASON*" labels, so that people seeing all of our open PRs don't get scared away ;)

**Comment by slotThe** [comment]
Well I did a thing.  If people don't like it, feel free to suggest alternatives/just make the changes
