### ISSUE TITLE
Could not find module `XMonad.Hooks.WindowSwallowing`

### ISSUE THREAD

**Issue by sebasijan** [xmonad/xmonad-contrib#698]
### Problem Description

When I try to import into my xmonad.hs

    import XMonad.Hooks.WindowSwallowing

I get this error

> Could not find module `XMonad.Hooks.WindowSwallowing`

### Steps to Reproduce

Give detailed step-by-step instructions on how to reproduce the problem.

### Configuration File

Simply try to `import XMonad.Hooks.WindowSwallowing` in xmonad.hs

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.0.9
    - [ ] With `xmonad-contrib` version 0.17.0.9

**Comment by geekosaur** [comment]
The template asks for your `xmonad` and `xmonad-contrib` versions for a reason: this module only exists in 0.17.0, and it's up to your distribution to package it.

**Comment by geekosaur** [comment]
Sorry, I see you filled the versions in (it's not in 0.16 which is still packaged by most distros).

How do you have your xmonad config set up for building? Are you using stack or cabal? Do other `xmonad-contrib` modules work?

**Comment by geekosaur** [comment]
It definitely belongs here. But if other modules are also missing then we need to figure out if you have `xmonad-contrib` installed correctly.

**Comment by sebasijan** [comment]
@geekosaur  Okay, this is what I am importing to my config atm, and don't seem to have any other issues - what else can I provide?

    import XMonad

    -- import XMonad.Hooks.WindowSwallowing

    import qualified XMonad.StackSet as W

    import XMonad.Config.Desktop

    import XMonad.Util.EZConfig
    import XMonad.Util.Run
    import XMonad.Util.SpawnOnce
    import XMonad.Util.Cursor
    import XMonad.Util.NamedScratchpad

    import XMonad.Hooks.DynamicLog (dynamicLogWithPP, wrap, xmobarPP, xmobarColor, shorten, PP(..))
    import XMonad.Hooks.EwmhDesktops
    import XMonad.Hooks.DynamicLog
    import XMonad.Hooks.ManageDocks
    import XMonad.Hooks.ManageHelpers (isFullscreen, doFullFloat, doCenterFloat)

    import XMonad.Layout.Decoration
    import XMonad.Layout.NoBorders
    import XMonad.Layout.Renamed
    import XMonad.Layout.ResizableTile
    import XMonad.Layout.Spacing
    import XMonad.Layout.Spiral
    import XMonad.Layout.Tabbed
    import XMonad.Layout.ThreeColumns
    import XMonad.Layout.Gaps
    import XMonad.Layout.NoBorders
    import XMonad.Layout.LayoutModifier (ModifiedLayout)

    import qualified Data.Map as M
    import Data.Maybe (fromJust)
    import Data.Monoid

    import Colors.MyScheme

**Comment by slotThe** [comment]
What does `xmonad --version` return?  I still get the feeling that you
are not on 0.17.0.

**Comment by sebasijan** [comment]
@slotThe 

    $ xmonad --version

Outputs

    xmonad 0.17.0.9

**Comment by slotThe** [comment]
@sebasijan That's really curious; the `xmonad` version in $PATH is responsible for recompiling, so my guess was that you forgot to upgrade that one.  I don't really know what to tell you other than "have you tried uninstalling and installing it again?" :)

Just to double check; all of the error messages you posted mention `Monad.Hooks.WindowSwallowing`; I assume that's a typo?

**Comment by geekosaur** [comment]
In my experience the two can get out of sync really easily. In particular, we've had more than one case of someone having both `/usr/bin/xmonad` and `~/.local/bin/xmonad` (or `~/.cabal/bin`, etc.) and the result being rather confused.

**Comment by slotThe** [comment]
On Tue, Apr 05 2022 03:41, brandon s allbery kf8nh wrote:
> In my experience the two can get out of sync really easily. In
> particular, we've had more than one case of someone having both
> `/usr/bin/xmonad` and `~/.local/bin/xmonad` (or `~/.cabal/bin`, etc.)
> and the result being rather confused.

Oh, right, the `xmonad` executable in $PATH when a shell is already
loaded may not be the one that xmonad uses when it was started by e.g. a
display manager.

**Comment by sebasijan** [comment]
@geekosaur  I think you are definitely on to something:

    bassie@Skoot-Top:~$ /usr/bin/xmonad --version
    xmonad 0.15
    bassie@Skoot-Top:~$ ~/.local/bin/xmonad --version
    xmonad 0.17.0.9

Not quite sure how to verify from here which one is actually being executed on launch/recompile though

**Comment by geekosaur** [comment]
I'd just remove the one you don't want, make sure your session can find the other one (this may require adding a like like `source ~/.bash_profile` to your `~/.xsession`), and `xmonad --restart`.

**Comment by geekosaur** [comment]
You're having exactly the problem that was supposed to fix: your DE was using `/usr/bin/xmonad` and that's why it couldn't find the module.

How is your desktop manager configured? Do you have a file `~/.xsession` which runs xmonad, or does it use a file like `/usr/share/applications/xmonad.desktop`?

**Comment by sebasijan** [comment]
@geekosaur I can see `/usr/share/applications/Xmonad` and `~/.xsession` but not sure which one is being used

I will delete each one and see what happens

**Comment by slotThe** [comment]
@sebasijan where do we stand on this?  did you manage to solve it?

**Comment by sebasijan** [comment]
@slotThe  Unfortunately not - I'm not sure what steps to take next

**Comment by slotThe** [comment]
@sebasijan Your DM somehow needs to be aware of `~/.local/bin`, so you can either source the file where you set your `$PATH` in .xsession, add a .desktop file like [here](https://xmonad.org/INSTALL.html#make-xmonad-your-window-manager) or even just symlink `~/.local/bin/xmonad` to `/usr/bin/xmonad`

**Comment by TheMC47** [comment]
Any updates? This isn't really an issue with xmonad/xmonad-contrib. Maybe open a [discussion](https://github.com/xmonad/xmonad/discussions) and let's close this issue

**Comment by slotThe** [comment]
Agreed
