### ISSUE TITLE
Dynamic scratchpads documentation

### ISSUE THREAD

**Issue by tomjpalamattam** [xmonad/xmonad-contrib#699]
### Problem Description

I recently found out XMonad.Util.DynamicScratchpads is now deprecated and got an warning to use  the dynamic scratchpad facility of XMonad.Util.NamedScratchpad instead. However the documentation for XMonad.Util.NamedScratchpad doesn't mention the use of toggleDynamicNSP or dynamicNSPAction.  i don't know if this is the right place to mention this.  Just wanted to bring this to your attention.  
### Checklist

  - [X ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [X ] With `xmonad` version XXX (commit XXX if using git)
    - [ X] With `xmonad-contrib` version XXX (commit XXX if using git)

**Comment by slotThe** [comment]
The documentation on Hackage probably doesn't, but there is [xmonad-docs](https://github.com/xmonad/xmonad-docs), which builds the new documentation nightly(?).  The dynamic part of NamedScratchpads is [here](https://xmonad.github.io/xmonad-docs/xmonad-contrib-0.17.0.9/XMonad-Util-NamedScratchpad.html#g:2)

**Comment by slotThe** [comment]
I will close this for now, as I believe it solved; @tomjpalamattam feel free to chime in if you still have any questions!

**Comment by slotThe** [comment]
On Tue, Apr 05 2022 06:06, tomjpalamattam wrote:
> But, it is deprecated right?

Only the functions in DynamicScratchpads.  The deprecated aspect of this
is that these should be wired into the NamedScratchpad framework and not
their own module.  You can just switch your import of DynamicScratchpads
with NamedScratchpads and things should work exactly as they did before

**Comment by tomjpalamattam** [comment]
>  You can just switch your import of DynamicScratchpads with NamedScratchpads and things should work exactly as they did before

If I use

> import XMonad.Util.NamedScratchpad
> 
> , ("M-s-a", withFocused $ makeDynamicSP "dyn1") , ("M-s-b", withFocused $ makeDynamicSP "dyn2") , ("M-a" , spawnDynamicSP "dyn1") , ("M-b" , spawnDynamicSP "dyn2")

I get errors with my xmonad.hs saying variable not in scope, instead i used these keybindings in my config to make it working.

     , ("M-C-q", withFocused $ toggleDynamicNSP "dyn1")
     , ("M-C-w",  dynamicNSPAction "dyn1") 
     , ("M-C-e", withFocused $ toggleDynamicNSP "dyn2")
     , ("M-C-r",  dynamicNSPAction "dyn2")

**Comment by slotThe** [comment]
Oh you are totally right!  I forgot to update the documentation after I switched the names.  Should be fixed now, thanks for bringing this up!

**Comment by tomjpalamattam** [comment]
Glad i was able to help
