### ISSUE TITLE
Azerty wrong key for `6` and `8` with layout be

### ISSUE THREAD

**Issue by PierreR** [xmonad/xmonad-contrib#70]
With a `be` layout, `XMonad.Config.Azerty` will successfully work with all number keys from 1 to 9 except for the number `6` and `8`.

This is annoying because pressing these 2 keys has no effect .

This is probably due to the fact that `6` and `8` keys are different in a `be` layout compared to the `fr` one. The key `8` for instance is exclamation mark as you can see from this `xmodmap` output:

```
keycode   9 = Escape NoSymbol Escape
keycode  10 = ampersand 1 ampersand 1 bar exclamdown bar
keycode  11 = eacute 2 eacute 2 at oneeighth at
keycode  12 = quotedbl 3 quotedbl 3 numbersign sterling numbersign
keycode  13 = apostrophe 4 apostrophe 4 onequarter dollar onequarter
keycode  14 = parenleft 5 parenleft 5 onehalf threeeighths onehalf
keycode  15 = section 6 section 6 asciicircum fiveeighths asciicircum
keycode  16 = egrave 7 egrave 7 braceleft seveneighths braceleft
keycode  17 = exclam 8 exclam 8 bracketleft trademark bracketleft
keycode  18 = ccedilla 9 ccedilla 9 braceleft plusminus braceleft
keycode  19 = agrave 0 agrave 0 braceright degree braceright
```

I guess `0x2d` and `0x5f` need to be replaced when using a `be` layout but by what ?

**Comment by PierreR** [comment]
So I have find out that this works out `0x2d` needs to be replaced by `0xa7` and `0x5f` by `0x21`.
To it leads to : 
```
        | (i, k) <- zip (workspaces conf) [0x26,0xe9,0x22,0x27,0x28,0xa7,0xe8,0x21,0xe7,0xe0],
```
I guess to fix it properly one way could be to add a layout parameter to the function.

**Comment by thblt** [comment]
My config handles both FR and Be (with a bit of TemplateHaskell magic to choose the correct one). Maybe a more general solution could be to create a defaultConfigIntl which would take a keyboard layout as parameter? I could work on this.

**Comment by pjones** [comment]
@thblt That would be great.  Thanks!

**Comment by thblt** [comment]
Sorry for the delay, here's [a diff adding preliminary support](https://github.com/xmonad/xmonad/compare/master...thblt:handle-intl-keyboards).  It lacks comments but should be reasonably obvious (also, a few layouts are incomplete).   

If this approach seems fine to you, I'll finalize it and add a pull request.

**Comment by thblt** [comment]
On second look, maybe this solution is unnecessarily complex.  A simple:

``` haskell
data IntlKeys = IntlKeys { intlWorkspaceKeys :: [KeySym],
                           intlXineramaKeys :: [KeySym],
                         }
```

should be enough.

**Comment by thblt** [comment]
What do you think, @pjones?
