### ISSUE TITLE
ewmhFullscreen somehow prevents Emacs 29 float rule from working

### ISSUE THREAD

**Issue by ajgrf** [xmonad/xmonad-contrib#702]
### Problem Description

I'm trying to create a `manageHook` that floats certain Emacs windows. Matching the windows works just fine, but xmonad can't seem to float them properly (for example, `doShift` works but `doFloat` doesn't).

I think I've narrowed down the problem to `ewmhFullscreen` and Emacs 29. Older Emacs versions work as expected, and removing `ewmhFullscreen` from my config also resolves the issue.

### Steps to Reproduce

1. Configure xmonad to automatically float Emacs windows.
2. Launch Emacs 29 (with pgtk support). The window appears to flicker. Perhaps it is floating briefly before immediately getting tiled.

### Configuration File

Please include the smallest _full_ configuration file that reproduces
the problem you are experiencing:

```haskell
module Main (main) where

import XMonad
import XMonad.Hooks.EwmhDesktops

main :: IO ()
main = xmonad . ewmhFullscreen $ def
  { manageHook = className =? "Emacs" --> doFloat
  }
```

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [X] With `xmonad` version 0.17.0
    - [X] With `xmonad-contrib` version 0.17.0

**Comment by slotThe** [comment]
As an additional data point: the Emacs maintainers [strongly discourage](https://lists.gnu.org/archive/html/emacs-devel/2022-04/msg00761.html) using PGTK on X11:

> People using X should _never_ use PGTK.  The regular X build does a much better job at supporting that than PGTK ever will.

I'm tempted to close this as WONTFIX, as I've never heard of a program misbehaving due to `ewmhFullscreen` alone and thus it's quite likely the fault is with PGTK

**Comment by ajgrf** [comment]
I've already moved away from the PGTK build except where I need Wayland support (just in WSLg for me). I didn't know PGTK was actually discouraged on X, though. That actually seems bizarre to me.

It's okay with me if you close this. It's an obscure bug for pre-alpha software and it's no longer affecting me anyway.

**Comment by slotThe** [comment]
Fair enough then
