### ISSUE TITLE
_NET_DESKTOP_VIEWPORT Support in ewmh

### ISSUE THREAD

**Issue by Pachin0** [xmonad/xmonad-contrib#708]
Recently I was looking at other panels other than xmobar and saw that panels, such as polybar grab the window name, workspace list, active workspace from the ewmh compliant window managers such as I3, bspwm, etc. But I found out that polybar for instance, does not work smoothly with xmonad's worspaces because xmonad's ewmh module for some reason does not set _NET_DESKTOP_VIEWPORT
Which is vital for polybar and other panels to know how to know, which monitor is displaying what workspace when there is a multi-monitor setup. In the current case, if polybar is run on a multi-monitor setup with xworspaces setup polybar gets confused between which workspace to mark as focused with the workspace on the second or third monitor. For polybar to work in multimonitor setup, there is an option for the xworspaces module that allows polybar to only display the workspace that is on the current screen, that way you run 2 panels and each tells you which workspace is displaying. XMonad I believe could just set _NET_DESKTOP_VIEWPORT. That way we can leverage the more elegant ewmh solution for workspaces in panels. 

Forgive if I don't know how to implement this myself, I read some discussions about polybar's pin-workspace functionality and they mentioned that that works with _NET_DESKTOP_VIEWPORT, then I searched the xmonad ewmh source code and confirmed it wasn't implemented in anyway. 

Here is the polybar discussion about viewport 
https://github.com/polybar/polybar/issues/840

**Comment by slotThe** [comment]
Related: https://github.com/xmonad/xmonad-contrib/issues/150

Perhaps it's worth implementing _NET_DESKTOP_VIEWPORT in some way after all...

**Comment by geekosaur** [comment]
Thank you, I knew I'd seen that request somewhere but didn't think it'd be hidden in an unrelated ticket. Yes, it seems likely we want this.

**Comment by TheMC47** [comment]
Is there anything tricky about this? Shouldn't `getScreenInfo` give the required info?

**Comment by geekosaur** [comment]
There shouldn't be, but that's what we thought about `_NET_WORKAREA` too. (Which I still have to set in my own config for Qt apps to work, for some reason.)

**Comment by Pachin0** [comment]
is the _NET_DESKTOP_VIEWPORT supposed to be set per window? If that is the case, xmonad would get the coordinates of the window's top left corner and check if it is within left monitor rectangle or right monitor's rectangle. If it is in, then xmonad would set _NET_DESKTOP_VIEWPORT to the coordinates of top left corner of the monitor?

**Comment by geekosaur** [comment]
It's set on the root window to indicate the viewport of each desktop, along with _NET_DESKTOP_GEOMETRY. But the documentation seems unclear about this, so I'd want to see how it's actually used which may not match the spec.

**Comment by Pachin0** [comment]
Whats bothers me is that to not show the workspaces in any monitor we must set them outside root window, which seems odd, the protocol should allow for either another workspace list to mask the other workspaces or to allow for negative numbers to set the invisible workspaces.

**Comment by Pachin0** [comment]
Another approach for setting the invisible tags,  would be this one: For invisible tagst that have opened windows on them, switch their viewport to the monitor that is currenly focused. This allows the nearest bar to your eyes to display other tags you might go visit. Then send to -1,-1 all tags without windows so that you don't even see them anywhere. If the user chooses to view all the unocuppied tags along with the occupied tags at the nearest bar we could also make a setting for that.

**Comment by geekosaur** [comment]
Yes, that was part of what I meant about the documentation being unclear; it seems like it was intended for some other use case but has been adopted for this one instead. In particular, it doesn't seem to actually support multi-screen setups where each screen displays a different workspace (specifically, you must violate the (0,0) requirement and it assumes all screens are the same size).

**Comment by Pachin0** [comment]
You don't have to map them outside, just if you don't want the bar to display the unused tags, if that causes slowdown, just set the invisible tags to always follow the focused monitor's viewport. Wayland seems ages away sadly, we'll probably have bigger problems due to the fresh standards.

**Comment by geekosaur** [comment]
(-1,-1) would place a workspace not fully offscreen, but with its topmost and leftmost pixels offscreen.

**Comment by Pachin0** [comment]
https://github.com/xmonad/xmonad-contrib/pull/717

**Comment by compromyse** [comment]
So.. how do I use this? is it implemented when I use `$ ewmh` in xmonad.hs?

**Comment by compromyse** [comment]
So.. how do I use this? is it implemented when I use $ ewmh in xmonad.hs?

**Comment by geekosaur** [comment]
Yes, it should be automatic when using the `ewmh` combinator.

**Comment by compromyse** [comment]
@geekosaur even with `main = xmonad $ ewmh $ defaults` I get ```Disabling module "ewmh" (reason: The WM does not support _NET_DESKTOP_VIEWPORT (required when `pin-workspaces = true`))``` with polybar

**Comment by geekosaur** [comment]
I see the property:
```
skkukuk ⁅xmonad-bsa⁆ Z$ xprop -root | grep VIEWPORT
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 1920, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
```
The xmonad you get from cabal-install won't have it until we next do a release; for now you have to run xmonad from git.

**Comment by geekosaur** [comment]
@liskin, might this be justification to do that 0.17.1 release you wanted?

**Comment by compromyse** [comment]
I used `Build using cabal install` from https://xmonad.org/INSTALL.html, I'm pretty sure it installs from git since i had to clone the repositories first

**Comment by compromyse** [comment]
```
error: Disabling module "ewmh" (reason: The WM does not support _NET_DESKTOP_VIEWPORT (required when `pin-workspaces = true`))
```

I still get this error but it seems like the `_NET_DESKTOP_VIEWPORT` is changing. What's the `(CARDINAL)` part of the name?

**Comment by geekosaur** [comment]
X11-ese to say its type is a list of integers.

**Comment by compromyse** [comment]
okay, any idea what causes this polybar error? or is there an alternative bar that implements the `pin-workspaces` feature in polybar?

**Comment by compromyse** [comment]
I can upload my xmonad config if you'd like

**Comment by geekosaur** [comment]
`_NET_DESKTOP_VIEWPORT` is missing from `_NET_SUPPORTED`.

**Comment by geekosaur** [comment]
If you're familiar with git and github, you can do `git fetch --all` and check out the PR #722 branch to see if it makes polybar happy.

**Comment by liskin** [comment]
> @liskin, might this be justification to do that 0.17.1 release you wanted?

Yeah let's do this after ZuriHac.
