### ISSUE TITLE
X.A.Search Amazon searchengine fails

### ISSUE THREAD

**Issue by davama** [xmonad/xmonad-contrib#71]
Hello,
Not much of an issue here but just something i noticed.

The amazon search goes to:
`https://www.amazon.com/s/157-2226551-1458745?ie=UTF8&index=all&keywords=`

But i receive a "Sorry Couldn't Find the page" messege.

I had worked around this by using a custom searchengine for amazon:
```
((0, xK_a), method $ S.searchEngine "Amazon" "http://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=")
```
Which works.

Any chance we can fix?

I use haskell xmonad 0.12
Honestly didn't test with Git xmonad

Thanks
Dave

**Comment by byorgey** [comment]
Good catch, thanks!
