### ISSUE TITLE
Can't update extensible state value?

### ISSUE THREAD

**Issue by Pachin0** [xmonad/xmonad-contrib#713]
### Problem Description

For some reason, cannot update a value into the extensible state with put from the same hook. For some reason, If I call a function that updates that value from a keybind, it works just fine. But if I have a value that I want to check and update from a log hook, it doesn't update. 

### Steps to Reproduce

Start xmonad from `.xinitrc` with this command
```sh
exec xmonad | tee /tmp/output.log
```
once inside the xmonad environment, open the file in a terminal with and monitor the output
```sh
tail -f /tmp/output.log
```

### Configuration File

```hs
newtype MonitorTags = MonitorTags [WorkspaceId]
  deriving (Show,Eq)
instance ExtensionClass MonitorTags where
  initialValue = MonitorTags []

customLog :: XConfig a -> XConfig a
customLog x = x {logHook = myOtherLogHook <+> logHook x}

myOtherLogHook = withWindowSet $ \s -> do 
  let visibleScreens = W.current s : W.visible s
  let currentTags = map (W.tag . W.workspace) visibleScreens
  
  v <- XS.get :: X MonitorTags

  io $ do
    print "Extensible State Value: " 
    print v 
    
  if v == MonitorTags currentTags
    then 
    io $ print "value is the same, not updating"
    else do
    io $ print "Value has changed, updating to " >> print currentTags
    XS.put (MonitorTags currentTags)
```

To your xmonad's config
```hs
main = xmonad $ customLog $ ... 
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [X] With `xmonad` version 0.17.0
    - [X] With `xmonad-contrib` commit 0e106ccfbee21c90eec46537bfb4341de648c9f7

**Comment by geekosaur** [comment]
It seems to work here, switching from workspace 1 to 4 to 3:
```
"Extensible State Value: "
MonitorTags []
"Value has changed, updating to "
["1"]
"Extensible State Value: "
MonitorTags ["1"]
"value is the same, not updating"
"Extensible State Value: "
MonitorTags ["1"]
"Value has changed, updating to "
["4"]
"Extensible State Value: "
MonitorTags ["4"]
"Value has changed, updating to "
["3"]
xinit: connection to X server lost

waiting for X server to shut down 
```

The `xmonad.hs` I used is
```hs
import XMonad
import qualified XMonad.StackSet as W
import qualified XMonad.Util.ExtensibleState as XS

newtype MonitorTags = MonitorTags [WorkspaceId]
  deriving (Show,Eq)
instance ExtensionClass MonitorTags where
  initialValue = MonitorTags []

customLog :: XConfig a -> XConfig a
customLog x = x {logHook = myOtherLogHook <+> logHook x}

myOtherLogHook = withWindowSet $ \s -> do 
  let visibleScreens = W.current s : W.visible s
  let currentTags = map (W.tag . W.workspace) visibleScreens
  
  v <- XS.get :: X MonitorTags

  io $ do
    print "Extensible State Value: " 
    print v 
    
  if v == MonitorTags currentTags
    then 
    io $ print "value is the same, not updating"
    else do
    io $ print "Value has changed, updating to " >> print currentTags
    XS.put (MonitorTags currentTags)

main = xmonad $ customLog def
```

**Comment by slotThe** [comment]
@Pachin0 any updates?

**Comment by Pachin0** [comment]
I was away from home so I couldn't work on this. I am working on a 2 monitor setup and I can assure that for some reason it wasn't updating the value from the XS.put function in the same hook but for some reason binding the update function to a keybind works just fine. Ill try with another datatype and see. 

I also have a suspicion that the ewmh current desktop updating part does not work due to a similar problem. Ill make another xmonad config from scratch and test with that.

**Comment by geekosaur** [comment]
Are you sure you're not seeing https://wiki.haskell.org/Xmonad/Frequently_asked_questions#Replacing_greedyView_with_view ? I have dual screens and a taskbar which relies on EWMH, and it shows the correct EWMH updates.

**Comment by Pachin0** [comment]
Forget it, I did it with a new config and reinstalled the xmonad-contrib and xmonad libraries and it works now. It updates the state.

**Comment by geekosaur** [comment]
Okay, closing for now. If you repeat it later and can provide more information you can reopen it.
