### ISSUE TITLE
There are problems in package xmonad-contrib-0.17.0.9

### ISSUE THREAD

**Issue by tim-kilian** [xmonad/xmonad-contrib#724]
### Problem Description

Updated my packages on arch linux with pacman and fresh xmonad-git and xmonad-contrib-git, resulting in xmonad is not working... xmonad is the only package I struggle with every time. Wish there where something else on the market, which is like xmonad, but more stable. :(  

### Console output

```
There are problems in package xmonad-contrib-0.17.0.9:
  Warning: haddock-interfaces: /usr/share/doc/xmonad-contrib-git/html/xmonad-contrib.haddock doesn't exist or isn't a file
  Warning: haddock-html: /usr/share/doc/xmonad-contrib-git/html doesn't exist or isn't a directory
  dependency "X11-xft-0.3.4-FsPv4vVXSfkKa8YhCWYNeR" doesn't exist
  dependency "random-1.2.1.1-3wKj9e3u29gD8fix3pODh6" doesn't exist
  dependency "utf8-string-1.0.2-FQ2pl5uqCikATsVEhSxXsC" doesn't exist
```

**Comment by TheMC47** [comment]
We sadly have no control over how xmonad is packaged... A potentially more sane way is to build from source (or use ghcup, I've heard). Check https://xmonad.org/INSTALL.html#download-xmonad-sources or bring the issue with the package maintainer on the AUR.

**Comment by geekosaur** [comment]
We don't have anything to do with Arch (or any other distribution) packaging, and in fact believe Arch in particular does its packaging incorrectly, leading to problems like this. We strongly recommend running from hackage or directly from git, using ghcup and stack instead of any Arch-packaged Haskell tools, because Arch's packaging of Haskell tends to break things.

**Comment by tim-kilian** [comment]
thanks for nothing

**Comment by geekosaur** [comment]
What are we supposed to do, take over the Arch ecosystem?

**Comment by TheMC47** [comment]
@tim-kilian these passive-aggressive comments aren't appreciated. We answered you in a civil way and pointed you to an alternative. I'd expect a certain minimal amount of politeness when asking strangers for help who literally owe you nothing.
