### ISSUE TITLE
X.H.ManageDocks.AvoidStruts breaks dropdown menus on multi-monitor screens

### ISSUE THREAD

**Issue by Narthorn** [xmonad/xmonad-contrib#73]
Starting a few months ago, dropdown menus in some applications sometimes stop working when the window is on one screen, then seem to work again with the window on the other screen - only for them to stop working again after changing to another workspace.

The reason for the bug is that [AvoidStruts](https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Hooks/ManageDocks.hs#L272) calculates _NET_WORKAREA for the root window using the position, dimensions and struts of only one screen, and updates it whenever a window is mapped on that screen. Hence, on multi-monitor setups, when swapping windows from one screen to another, the calculated workarea often ends up not being the correct one for the currently focused window.

This affects several applications, notably [chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=510079#c59), most Qt apps (due to [similar use](http://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/qxcbscreen.cpp#n132) of the workarea rectangle to make dropdowns avoid struts), and it probably also affects all applications that rely on _NET_WORKAREA for any purpose.

This issue was noted before in https://code.google.com/archive/p/xmonad/issues/158 (comment 12), and https://code.google.com/archive/p/xmonad/issues/526. It seems generally agreed that _NET_WORKAREA is unsuited for multi-monitor setups with docks in-between screens, but in this case, applications will break regardless of where the docks are.

I'm not sure what the best solution is for this. One way would be to make xmonad calculate and store the workarea for each screen in _NET_WORKAREA, but this also would require patches to client applications since most of them only ever look at the first 4 values of the property. The other way would be to drop support for _NET_WORKAREA altogether ; this is what [i3](https://github.com/i3/i3/blob/eb837cbd009dab61e713ca12c0d882d707c3f2a3/include/ewmh.h#L91) and [awesome](https://github.com/awesomeWM/awesome/issues/677) ended up doing long ago, basically for the same reasons.

**Comment by geekosaur** [comment]
The problem with just dropping _NET_WORKAREA is that this allows desktop backdrops to position things behind docks (and some desktop-window file managers will spam incessantly about missing _NET_WORAKREA).

For what it's worth, I have been experimentally setting _NET_WORKAREA to a hardcoded constant value which incorrectly claims I have the same docks everywhere, since _NET_WORKAREA assumes the EWMH workspace model which does not map to xmonad's workspace model. Both Qt's menus and Chrome's dropdown menus are working now, where they didn't before.

```haskell
-- @@@@@@@@ HAAAAAAAAAACK
setWorkArea :: X ()
setWorkArea = withDisplay $ \dpy -> do
    a <- getAtom "_NET_WORKAREA"
    c <- getAtom "CARDINAL"
    r <- asks theRoot
    io $ changeProperty32 dpy r a c propModeReplace (concat $ replicate (length workspacen) [0, 26, 3840, 1028])
```

**Comment by Narthorn** [comment]
> _NET_WORKAREA assumes the EWMH workspace model which does not map to xmonad's workspace model.

I'm not entirely sure what EWMH expects to be in _NET_WORKAREA, but wouldn't it be possible just to store the workarea for each visible xmonad workspace in the corresponding slot in _NET_WORKAREA, based on which monitor that workspace is currently on ?

For example, with a dual-monitor setup like this:
```
|‾‾‾‾‾‾‾‾‾‾‾||‾‾‾16px dock‾‾‾|
| 1680x1050 ||               |
|___________||   1900x1200   |
 workspace 2 |_______________|
                workspace 0
```

_NET_WORKAREA would contain this:
```
  /‾‾‾workspace 0‾‾‾‾\              /‾‾workspace 2‾\
 [1680, 16, 1900, 1184, 0, 0, 0, 0, 0, 0, 1680, 1050, 0, 0, 0, ...]
  \___right screen___/              \__left screen_/   
```

This seems to be what [GDK](https://github.com/GNOME/gtk/blob/af5ef152b1c1949f580e96fa0ef125a96ece878e/gdk/x11/gdkscreen-x11.c#L292) expects, as it first retrieves the number of the active workspace through _NET_CURRENT_DESKTOP before using that to get the right workarea.

**Comment by geekosaur** [comment]
On Thu, Aug 11, 2016 at 11:59 AM, Vincent Vinel <notifications@github.com>
wrote:

> I'm not entirely sure what EWMH expects to be in _NET_WORKAREA, but
> wouldn't it be possible just to store the workarea for each visible xmonad
> workspace in the corresponding slot in _NET_WORKAREA, based on which
> monitor that workspace is currently on ?


There are programs that break if you don't have values for the non-visible
workspaces. What you suggest is what I'm looking at for the actual fix
(with defaults for the non-visible workspaces) and corresponds to the EWMH
documentation (this is not surprising, the Gnome devs control the EWMH spec
these days). What worries me is that some programs may cache information,
when it will in fact be variable based on what workspaces are visible.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by geekosaur** [comment]
On Thu, Aug 11, 2016 at 11:59 AM, Vincent Vinel <notifications@github.com>
wrote:

> _NET_WORKAREA assumes the EWMH workspace model which does not map to
> xmonad's workspace model.
>
> I'm not entirely sure what EWMH expects to be in _NET_WORKAREA, but
> wouldn't it be possible just to store the workarea for each visible xmonad
> workspace in the corresponding slot in _NET_WORKAREA, based on which
> monitor that workspace is currently on ?
>

Also, the real problem here is that, since dock visibility is per workspace
but placement is per screen, and workspaces are constrained to monitors,
the numbers end up changing a lot more than EWMH-using programs expect and
sometimes don't fully reflect what xmonad is actually doing.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by OakTwo** [comment]
I'd like to use geekosaur's workaround but I don't have the Haskell skills to integrate that code into my xmonad.hs - does anyone have an xmonad.hs they can publish online that I ( and the others who've hit this issue ) can use as a first step to working around the problem ourselves?

( I've tried myself but searching online for geekosaur and xmonad.hs brings up a *lot* of links of course ... )

**Comment by pjones** [comment]
Fixed in 0.13

**Comment by Narthorn** [comment]
Which commit fixes this?

**Comment by geekosaur** [comment]
https://github.com/xmonad/xmonad-contrib/commit/cd96de53782f04a60adfa5f0bc588e51ff735e40
note that this requires an update to the X11 bindings
