### ISSUE TITLE
`X.P.Unicode`: support Unicode symbols in description

### ISSUE THREAD

**Issue by PRESFIL** [xmonad/xmonad-contrib#733]
### Problem Description

`X.P.Unicode` allows you to work with Emoji in Unicode, but does not allow you to use
non-Latin characters in the description of these Emojis. `X.P.Unicode` works fine, but
cannot display such characters correctly.

![image](https://user-images.githubusercontent.com/20644917/178097187-480416d5-335a-46b1-ab34-38a2e2f8e799.png)

I managed to write a patch to add support, but for this I had to abandon `ByteString`.
I don't know if this is acceptable or necessary achieve operability with `ByteString`...

### Steps to Reproduce

1. Install Noto font
1. Create a file with an Emoji description (`/home/user/.xmonad/unicode-data`):

```
1f47e;alien monster | द एलियन
```

3. Recompile the Xmonad config
4. Sparm Unicode prompt
5. Start typing characters to display completion

### Configuration File

```haskell
import XMonad
import XMonad.Prompt
import XMonad.Prompt.Unicode

import qualified Data.Map as M

-- Prompts
--  default prompt settings
myXPConfig :: XPConfig
myXPConfig = def
  { font = "xft:monospace:size=9,Noto Color Emoji:pixelsize=12:style=Regular,Noto Sans Devanagari UI"
  , height = 17
  , position = Top
  , promptBorderWidth = 0
  , historyFilter = deleteAllDuplicates
  , searchPredicate = fuzzyMatch
  }

myKeys conf@(XConfig {XMonad.modMask = modm}) = M.fromList
  [ ((modm .|. controlMask, xK_u), unicodePrompt "/home/user/.xmonad/unicode-data" myXPConfig)
  ]

main = do
  xmonad = def
    { keys = myKeys <+> keys def
    }
```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version XXX (commit xmonad/xmonad@ed5c866 if using git)
    - [x] With `xmonad-contrib` version XXX (commit ea97c35 if using git)

**Comment by TheMC47** [comment]
> I managed to write a patch to add support, but for this I had to abandon ByteString.
I don't know if this is acceptable or necessary achieve operability with ByteString...

Could you share your patch?

**Comment by PRESFIL** [comment]
My branch:

- https://github.com/PRESFIL/xmonad-contrib#x-p-unicode-unidescriptions

**Comment by PRESFIL** [comment]
@TheMC47 , what do you think about using `String`?

**Comment by TheMC47** [comment]
I'm not sure, I don't know my way around this area. I thought providing a workaround would serve as a discussion basis with more knowledgeable maintainers. Since you have an alternative, feel free to create a PR! It would be more convenient to review code that way
