### ISSUE TITLE
Add xmonadctl to extra-source-files

### ISSUE THREAD

**Issue by ajgrf** [xmonad/xmonad-contrib#734]
### Problem Description

I'm packaging the `xmonadctl` script for NixOS (see NixOS/nixpkgs#181163). To do so, I couldn't reuse the source of the xmonad-contrib package but had to independently fetch it from GitHub. It would make it much easier to keep this package in sync with the xmonad-contrib package if `xmonadctl` were included in the files uploaded to Hackage.

**Comment by liskin** [comment]
As mentioned in the commit message, I actually thought a bit about making this an actual `executable` in xmonad-contrib.cabal last year, but decided against it. Unfortunately I can't remember why. :-/

Maybe I'll remember later, and in the meantime it's added to extra-source-files. And we've been talking about doing a release soon(-ish).
