### ISSUE TITLE
XMonad.Prompt.Pass: Missing generic search feature

### ISSUE THREAD

**Issue by Maeda1** [xmonad/xmonad-contrib#746]
### Problem Description

This is more a feature request than a problem.

Current problem: when opening the prompt in XMonad.Prompt.Pass, one *must type the very first characters of an existing first level folder* in $HOME/.password-store to show/match entries.

Pass utility has the _find_ argument that can search based on a keyword and match *any folder* **or** *any GPG file* that *contains* the keyword, which is much more easier to find a password entry.

### Steps to Reproduce

Assuming you have this $HOME/.password-store example entries:
$HOME/.password-store/www/github/email.gpg
$HOME/.password-store/www/github/password.gpg
$HOME/.password-store/other/mybestwebsite/password.gpg

Using XMonad.Prompt.Pass:
- Type the keybinding to show up the Xmonad pass prompt
- Type a keyword for example _password_
- It will not find anything, except if you type _www_ or _other_

Using pass:
- Type `pass find password`, then ENTER
- It will find below entries:
-> $HOME/.password-store/www/github/password.gpg
-> $HOME/.password-store/other/mybestwebsite/password.gpg
And without knowing the first full path folders.

That is a much better behavior and expected to have the same when using XMonad.Prompt.Pass

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.0-20
    - [x] With `xmonad-contrib` version 0.17.0-20

**Comment by slotThe** [comment]
What you're probably looking for is [X.P.FuzzyMatch](https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Prompt-FuzzyMatch.html)

**Comment by geekosaur** [comment]
Only if you can integrate it with `pass(1)` somehow. I suspect that's what the `find` subcommand to it does.

**Comment by Maeda1** [comment]
fuzzyMatch is indeed very close to what `pass find` does, except that it matches **others** too:

> Example: "spr" matches [FastSPR](https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/FastSPR.html) but also [SuccinctParallelTrees](https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/SuccinctParallelTrees.html) **because it's a subsequence of the latter: "S.......P.r.........."**.

Because of fuzzySort good relevance sorting (e.g., making "spr" matches first), I am adopting fuzzyMatch as a good solution.

**Comment by slotThe** [comment]
> Besides, that should be included by default for Prompt.pass, or highly recommended in the Prompt.pass documentation.

You're probably right; I can't imagine people wanting to type out the whole path to their password every time.  We should probably document this default though, in case users _do_ want that.  Fancy opening a PR?

**Comment by Maeda1** [comment]
You mean pull request by changing [$usage in Pass.hs](https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Prompt/Pass.hs#L85-L108) to add a note about that?

**Comment by slotThe** [comment]
I mean changing `mkPassPrompt` to automatically apply the fuzzy matcher and sorter, as well as document this in the module so that users who do not wish to use these features (or use other search predicates and sorters) know to turn them off.

(This would of course break backwards compatibility, but I think it's a worthwhile trade off to having yet another `mkPassPrompt'`)

**Comment by Maeda1** [comment]
I am afraid that is out of my skills :disappointed:

**Comment by slotThe** [comment]
No worries, I'll (try to, time permitting) prepare something tomorrow then
