### ISSUE TITLE
Old-style scratchpads not working any more

### ISSUE THREAD

**Issue by Maeda1** [xmonad/xmonad-contrib#756]
### Problem Description

After ugrading to
xmonad 0.17.1-10
xmonad-contrib 0.17.1-9

scratchpad (old-style) is not working anymore (nothing happens). That was working when using xmonad-contrib-0.17.0-20 (and xmonad-0.17.0-20).
Anyway, I am now using named scratchpad, which works well.

### Steps to Reproduce

Use a scratchpad (not named).

### Configuration File

This is not the full file, but some relevant parts about the scratchpad configuration. If this is not enough this is the [link to the full file](https://codeberg.org/Maeda/My-Xmonad-Xmobar-Trayer-configuration-files/src/branch/master/xmonad.hs) .

```haskell
import XMonad
import XMonad.Util.Scratchpad
import qualified XMonad.StackSet as W
import XMonad.Util.EZConfig(additionalKeysP)

myKeys =
        [ ("M-w", scratchPad)
        ]
        where
         scratchPad = scratchpadSpawnActionTerminal "urxvt -pe tabbed"

myManageHook = (composeAll
   [ 
   ])
   <+> manageScratchPad

--Scratchpad config
manageScratchPad :: ManageHook
manageScratchPad = scratchpadManageHook (W.RationalRect l t w h)
  where
    h = 0.25   -- terminal height, 25%
    w = 0.98   -- terminal width, 98%
    t = 0.72   -- distance from top edge, 72%
    l = 0.01   -- distance from left edge, 1%

main = xmonad $ def
        { manageHook = myManageHook
        , modMask = mod4Mask     -- Touche Super
        } `additionalKeysP` myKeys
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.1-10
    - [x] With `xmonad-contrib` version 0.17.1-9

**Comment by turboMaCk** [comment]
Interestingly I'm using named scratchpads which also stopped working for me after upgrade. I guess there had to be some more general breaking change.

**Comment by turboMaCk** [comment]
It turned out I was using manage hook from now deprecated legacy version which was the reason for breakage. Switching to `namedScratchpadManageHook` fixed the problem.
