### ISSUE TITLE
[BUG/IMPROVEMENT] Cross Layout is unusable with just 2 or 3 windows opened + windows glitch with mouse over (ever)

### ISSUE THREAD

**Issue by thealio** [xmonad/xmonad-contrib#793]
### Problem Description
Hi,
as reported in the title
XMonad.Layout.Cross is unusable if you open only 2 or 3 windows: if you open only 2 windows: there are only two long & slim windows which one is above the other one.
If you open only 3 widows , there are 3 windows on the right not tiled and not following the layout.
When you use the mouse on this layout, it's kind of a hell.
My distro is Arco Linux (Arch Linux repos)

### Steps to Reproduce
Open just two windows under XMonad.Layout.Cross

### Configuration File
https://xmonad.github.io/xmonad-docs/xmonad-contrib-0.16.999/XMonad-Layout-Cross.html

import XMonad.Layout.Cross(simpleCross)

myLayout =  simpleCross ||| etc..
main = xmonad def { layoutHook = myLayout }

### Issue
- With 2 windows opened
The height of the two windows opened is too low.
The two windows have exact the same poor dimensions, and one is above the other one
The windows are on the top
- With 3 windows opened
The dimensions are better, but  the windows are on the right and even in this case , superimposed
- Mouse hover glitch
When you put the mouse on a window, itìs totally a mess: windows are so glitched that you cannot select them

### What I expected
- Windows disposed with the main windows in the center, and the other one (or the other ones) on the left and/or on the right,  that go in the center when focused (as Cross layout works usually)
- Not glitch when the mouse is hover, maybe it's better to left-click with the mouse for select a windows, instead to put the mouse over it.

![Screenshot-2023-01-15-1673804279_screenshot_1916x982](https://user-images.githubusercontent.com/116115143/212557516-1edcf3ab-a1f4-4506-bfdf-435b467104a7.jpg)
![Screenshot-2023-01-15-1673804294_screenshot_1916x982](https://user-images.githubusercontent.com/116115143/212557553-a8f0b0e6-76e6-4459-9fda-f63b1805ffbc.jpg)
![Screenshot-2023-01-15-1673804302_screenshot_1916x982](https://user-images.githubusercontent.com/116115143/212557585-065bd759-9aa7-47ce-bb46-054b465f31e2.jpg)

**Comment by thealio** [comment]
Hi,
Any news about this issue?

**Comment by slotThe** [comment]
You're right, the cross layout seems to be completely broken; I reckon no one has used this layout in a while and it just bitrotted.  I'm almost tempted to just deprecate it, to be honest, since it seems like there are many other "master pane in the center and stack around it" type of layouts, which also work muc hbetter.

**Comment by thealio** [comment]
> You're right, the cross layout seems to be completely broken; I reckon no one has used this layout in a while and it just bitrotted. I'm almost tempted to just deprecate it, to be honest, since it seems like there are many other "master pane in the center and stack around it" type of layouts, which also work much better.

Hi
can you suggest me some of these layouts?
Currently, I use this instead the Cross Layout

`||| layoutHintsWithPlacement (0.5, 0.5) Circle`

**Comment by geekosaur** [comment]
`ThreeColMid` from `XMonad.Layout.ThreeColumn` may be of interest.

**Comment by thealio** [comment]
> `ThreeColMid` from `XMonad.Layout.ThreeColumn` may be of interest.

I already use it as `ResizableThreeColMid 1 (3/100) (1/2)  [] `

**Comment by geekosaur** [comment]
Also it looks like nobody addressed your mouse glitching. Does "(ever)" mean you see it regardless of layout? We have lots of users (including @slotThe and myself) who don't have such a problem.

- Are you by any chance running a compositor?
- What X11 video driver are you using?

**Comment by thealio** [comment]
hi
- no compositor
- virtual machine on Virtualbox

**Comment by geekosaur** [comment]
Hm. It's not at all unusual for video drivers to have bugs with border rendering that cause effects like this, which can be worked around by using a compositor; but running a compositor in VirtualBox is not at all a good idea. I'm still thinking about this one and may set up a VB environment to test this in.

**Comment by geekosaur** [comment]
It took me a while to get VB set up because it behaves rather oddly on my system (I normally use VMWare Player as a result), but having set it up and gotten a working minimal Ubuntu install going, I can't reproduce video glitching.

**Comment by thealio** [comment]
mmm
Maybe it's just a problem related to my hardware

**Comment by thealio** [comment]
Hi everybody,

I recently tried again ` import XMonad.Layout.Cross (simpleCross)`

Now it works OK for me
