### ISSUE TITLE
asks mouseFocused sometimes returns false in XMonad.Actions.UpdatePointer when change focus by mouse

### ISSUE THREAD

**Issue by kurnevsky** [xmonad/xmonad-contrib#8]
Try to write logHook:
myLogHook = do
  x <- asks mouseFocused
  if x then undefined else return ()
  updatePointer (Relative 0.5 0.5)
With this log hook xmonad never falls :)

**Comment by kurnevsky** [comment]
The main problem - when I use updatePointer hook and focusFollowsMouse is true then if I quick move mouse cursor then it sometimes jumps.

**Comment by kurnevsky** [comment]
Sorry, I was wrong. logHook called twice for some reason - with mouseFocused true and then false.

**Comment by kurnevsky** [comment]
So, it happens because for some reason all my windows have _NET_WM_WINDOW_TYPE_DESKTOP property, and docksEventHook calls refresh on such windows.

**Comment by kurnevsky** [comment]
It happens sometimes even without docksEventHook...

**Comment by pjones** [comment]
@kurnevsky What is the status of this bug.  Did it end up being something in your config?

**Comment by kurnevsky** [comment]
The initial problem was specific for my config - I did something wrong. But with XMonad.Actions.UpdatePointer mouse cursor still jumps to the center of the window when I move it from one window to another. It happens in rare cases - I don't know the reason. And I don't know how to stable reproduce it. The only way - move cursor quickly between corners of 3-4 windows.

**Comment by TheMC47** [comment]
I can reproduce this, exactly as you said (just move the cursor quickly between 3 windows). Not sure if we can/should do anything about it

**Comment by liskin** [comment]
If we can reliably reproduce it then the "can" part is true as long as "anything" includes "try to investigate", and the "should" part becomes clearer once we know what's going on. :-)

**Comment by TheMC47** [comment]
This has been open for 7 years, and no one else really complained. Let's close it
