### ISSUE TITLE
`XMonad.Prelude` incompatible with ghc 9.8's `base`

### ISSUE THREAD

**Issue by geekosaur** [xmonad/xmonad-contrib#826]
### Problem Description

`XMonad.Prelude` needs revision for the `base` that ships with ghc 9.8.

```
[ 31 of 312] Compiling XMonad.Prelude   ( XMonad/Prelude.hs, dist/build/XMonad/Prelude.o, dist/build/XMonad/Prelude.dyn_o )

XMonad/Prelude.hs:18:5: error: [GHC-69158]
    Conflicting exports for ‘unzip’:
       ‘module Exports’ exports ‘Exports.unzip’
         imported from ‘Data.Functor’ at XMonad/Prelude.hs:50:1-37
       ‘module Exports’ exports ‘Exports.unzip’
         imported from ‘Data.List’ at XMonad/Prelude.hs:51:1-37
         (and originally defined in ‘GHC.List’)
   |
18 |     module Exports,
   |     ^^^^^^^^^^^^^^

XMonad/Prelude.hs:22:5: error: [GHC-87543]
    Ambiguous occurrence ‘!?’.
    It could refer to
       either ‘Exports.!?’,
              imported from ‘Data.List’ at XMonad/Prelude.hs:51:1-37
              (and originally defined in ‘GHC.List’),
           or ‘XMonad.Prelude.!?’, defined at XMonad/Prelude.hs:84:1.
   |
22 |     (!?),
   |     ^^^^
```

### Steps to Reproduce

Try to build xmonad-contrib with the ghc 9.8 prerelease.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.2.9 (commit 5c2ba06 if using git)
    - [x] With `xmonad-contrib` version 0.17.1.9 (commit 2df26cf9 if using git)

**Comment by geekosaur** [comment]
We may also want to disable `-Wx-partial` which complains about `head` and `tail` among other things throughout the codebase.

**Comment by slotThe** [comment]
> `XMonad.Prelude` needs revision for the `base` that ships with ghc 9.8.

Mh, I guess some CPP it necessary here :/

> We may also want to disable `-Wx-partial` which complains about `head` and `tail` among other things throughout the codebase.

A more ambitious goal would be to fix all of these occurences, of course :)
