### ISSUE TITLE
Identify a location to download data for XMonad.Prompt.Unicode

### ISSUE THREAD

**Issue by jpolchlo** [xmonad/xmonad-contrib#840]
### Problem Description

[`XMonad.Prompt.Unicode`](https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Prompt/Unicode.hs) requires a data file to function.  It appears that [`unicode-data`](https://github.com/composewell/unicode-data/blob/master/unicode-data/README.md#unicode-database-version-update) is used to generate this data file, but the instructions for doing so are not clear, and I've had trouble generating this file for myself.  Either more specific instructions should be provided, or a downloadable data file should be made available.

### Steps to Reproduce

Not a bug, nothing to reproduce.

### Configuration File

N/A, but the function to be used is
```haskell
import XMonad.Prompt.Unicode

unicodePrompt "/path/to/unicode/data" def
```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [ ] With `xmonad` version XXX (commit XXX if using git)
    - [ ] With `xmonad-contrib` version XXX (commit XXX if using git)

**Comment by geekosaur** [comment]
That module, like everything else in xmonad-contrib, is contributed by someone else (the file header says @nomeata with changes by @nickhu); if they can't help then all we can do is remove the module from the distribution.

**Comment by nomeata** [comment]
That file is a standard file shipped by distributions. On Ubuntu, you’ll find it in the package `unicode-data` at path `/usr/share/unicode/UnicodeData.txt` (see https://packages.debian.org/sid/all/unicode-data/filelist for the list of files). 

On NixOS it’s a bit trickier. I just notice that I am running a different version of the code, guess I wrote that when switching to NixOS, that reads supports an environment variable: <https://gist.github.com/nomeata/b927440678e905fb433460f38e6f86ce>, which I set in my NixOS configuration:
```
  environment.variables = {
    UNICODE_DATA = "${pkgs.unicode-character-database}/share/unicode";
  };
```

**Comment by jpolchlo** [comment]
Hey, @nomeata, thanks for the pointer.  I found a file on my system thanks to your reply titled `UnicodeData.txt`, but it's under `/usr/share/texmf-dist`, which seems decidedly nonstandard.  I'll have to see if this file fits the bill.  I can probably update the docstring for this module with some of these pointers once I have this figured out the rest of the way if that's useful.

**Comment by nomeata** [comment]
What is your distribution?

But yes, such a PR would be useful

**Comment by nomeata** [comment]
Maybe https://packages.gentoo.org/packages/app-i18n/unicode-data would be the canonical package? Where does it put the file?

**Comment by jpolchlo** [comment]
Yup.  That's it.  Got thrown by the `app-i18n` category.  Was not familiar with the abbreviation.  I'll make a documentation PR.
