### ISSUE TITLE
Create a migration guide for `X.H.StatusBar` in the release announcement 

### ISSUE THREAD

**Issue by TheMC47** [xmonad/xmonad-contrib#880]
### Problem Description

https://github.com/xmonad/xmonad-contrib/pull/878 introduced a breaking change in the signature of `dynamicSBs`. We need to help users migrate their existing configurations.

We can use this issue to gather typical patterns and what needs to be done.

**Comment by TheMC47** [comment]
I greatly overestimated the usage patterns. I think people will figure out changing `IO` to `X`. Closing this

@slotThe FYI

**Comment by geekosaur** [comment]
> people will figure out changing `IO` to `X`.

I think you underestimate the number of users we have who don't know Haskell and will be completely flummoxed by this.

**Comment by TheMC47** [comment]
Should we amend the release notes?

**Comment by geekosaur** [comment]
Might be worth doing.

Cabal's packaged release notes point to the release notes on `master`, so they can be amended when needed. I don't think we need to go _that_ far, but it might be worth thinking about.

**Comment by slotThe** [comment]
> > people will figure out changing `IO` to `X`.
>
> I think you underestimate the number of users we have who don't know Haskell and will be completely flummoxed by this.

I reckon that users who don't know much (or any) Haskell are either not using these dynamic functions, or just funneling a pure function to them and calling `pure` (which is what I do as well). Nothing should break in that case, save for people who have their bar spanner (with the call to `pure`) in a separate function with an explicit type signature

**Comment by slotThe** [comment]
Ah, I see we are [advising users](https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Hooks/StatusBar.hs#L429) to have a separate definition with the `pure` already built in :/ (This should be fixed in the docs, btw).
