### ISSUE TITLE
Make X.L.Reflect flip some directional messages

### ISSUE THREAD

**Issue by leana8959** [xmonad/xmonad-contrib#912]
### Problem Description
I use the `XMonad.Layout.Reflect` module to put the master pane of my `Tall` layout on the right. The issue is, since the underlying layout isn't really flipped, the `Expand` and `Shrink` messages are of the wrong direction.

I'm not aware of a way to inject a function that transforms the message of the type that's defined upstream, so I have implemented another `LayoutModifier`.
```hs
data ReflectMsg a = ReflectMsg deriving (Show, Read)

reflectMsg :: l a ->  ModifiedLayout ReflectMsg l a
reflectMsg = ModifiedLayout ReflectMsg

instance LayoutModifier ReflectMsg a where
  handleMessOrMaybeModifyIt m mess
    | Just Shrink <- fromMessage mess = return . Just . Right $ SomeMessage Expand
    | Just Expand <- fromMessage mess = return . Just . Right $ SomeMessage Shrink
    -- Handle the rest by passing it on
    | otherwise = do mm <- handleMess m mess
                     return (Left <$> mm)
```

I think it would be a nice touch to flip this kind of message out of the box (to be discussed, not sure if it's a good idea), or have some sort of mechanism that allows users to opt-in/out, or even inject their own message overrides that depends on the flip.

What do you think ?

Have a nice day :)

**Comment by geekosaur** [comment]
The simplest way to deal with this doesn't seem to be very scalable: if a new layout (or even an existing one you didn't think about) adds a new message that needs to be "flipped", what happens?

I think I actually ran into this at one point with a different layout — the `Mirror` and `Reflect` layouts aren't the only ones which can cause these kinds of issues, which is another scalability concern — thought about it, and found a different way to eliminate the issue instead on the grounds that the whole question is kinda cursed.

This isn't really an xmonad/contrib issue, it's pretty much inevitable in any general purpose mechanism based on transformer stacks of some variety. With flexibility comes complexity.

**Comment by LSLeary** [comment]
The issue is in part born of message dynamacy. Ideally `LayoutClass` would be split into separate layouting and message handling classes, *the latter also keyed in the message type*. If you created a new layout you'd give it instances for (relevant) existing message types; if you created a new message type you'd give it instances for (relevant) existing layouts.

**Comment by leana8959** [comment]
I see, thanks a lot for the feedback !

I suppose I shall close this issue then.

**Comment by geekosaur** [comment]
We're not saying it's not a problem, just that it's nontrivial to fix in the general case.
