### ISSUE TITLE
Hackage docs seem outdated?

### ISSUE THREAD

**Issue by chrissound** [xmonad/xmonad-contrib#96]
http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Doc-Configuring.html

That seems different to (I'm assuming it's the source):
https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Doc/Configuring.hs

The github source has no reference to "defaultConfig" but the hackage page does.

**Comment by f1u77y** [comment]
docs on xmonad.org are outdated but hackage docks are still up-to-date for 0.12

**Comment by davama** [comment]
I had opened a ticket regarding updating xmonad.org docs but it was suggested to repoint the docs to hackage #83

**Comment by chrissound** [comment]
Didn't realize those docs aren't actually on hackage! They are the top results in google though.

**Comment by pjones** [comment]
I think the docs on xmonad.org should just be a redirect to hackage.  This is something I'll look into while we prepare for the v0.13 release.

**Comment by pjones** [comment]
xmonad.org was updated just after the 0.13 release.  Closing this.
